### ISSUE TITLE
Docker Image Build java.lang.NullPointerException: configs value

### ISSUE THREAD

**Issue by cegeka-jd** [eclipse-platform/eclipse.platform.ui#1001]
Build Docker Image stopped working, details below.

To reproduce: New workspace -> new general project -> new file -> Dockerfile

FROM quay.io/wildfly/wildfly:29.0.0.Final-jdk17

Right click Dockerfile -> Run As -> Docker Image Build 

Currently using Docker Desktop 4.22.0

Error log:
 
eclipse.buildId=4.28.0.20230608-1200
java.version=20.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=nl_BE
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data C:\cegeka\workspaces\waas\container-images -product org.eclipse.epp.package.jee.product

org.eclipse.core.jobs
Error
Thu Aug 10 08:41:25 CEST 2023
An internal error occurred during: "Building Docker Image".

java.lang.NullPointerException: configs value
	at java.base/java.util.Objects.requireNonNull(Objects.java:259)
	at org.mandas.docker.client.messages.ImmutableRegistryConfigs$Builder.addConfig(ImmutableRegistryConfigs.java:145)
	at org.mandas.docker.client.messages.ImmutableRegistryConfigs$Builder.addConfig(ImmutableRegistryConfigs.java:116)
	at org.mandas.docker.client.DockerConfigReader.authForAllRegistries(DockerConfigReader.java:140)
	at org.mandas.docker.client.auth.ConfigFileRegistryAuthSupplier.authForBuild(ConfigFileRegistryAuthSupplier.java:107)
	at org.mandas.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1413)
	at org.eclipse.linuxtools.internal.docker.core.DockerConnection.buildImage(DockerConnection.java:1478)
	at org.eclipse.linuxtools.internal.docker.ui.jobs.BuildDockerImageJob.run(BuildDockerImageJob.java:163)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by akurtakov** [comment]
Please report this to https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/ as this is where docker plugin is developed. Please make sure to attach Dockerfile to be used for reproducing the issue.

**Comment by akurtakov** [comment]
For the record building on Linux worked and I dont' have access to Windows machine to test. 
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/574788/ca3e5958-2470-4a61-a1a4-cdd34a04764f)
