### ISSUE TITLE
Random failing VirtualTableViewerTest.testRenameWithSorter and VirtualTableViewerTest.testContains 

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.ui#1005]
The test `org.eclipse.jface.tests.viewers.VirtualTableViewerTest.testRenameWithSorter` randomly fails, e.g. https://download.eclipse.org/eclipse/downloads/drops4/I20230810-1800/testresults/html/org.eclipse.jface.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
sorted first expected:<0-[0 name-999]9> but was:<0-[9 name-]9>

junit.framework.ComparisonFailure: sorted first expected:<0-[0 name-999]9> but was:<0-[9 name-]9>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.TestCase.assertEquals(TestCase.java:253)
at org.eclipse.jface.tests.viewers.VirtualTableViewerTest.testRenameWithSorter(VirtualTableViewerTest.java:244)
```

**Comment by HeikoKlare** [comment]
The test `org.eclipse.jface.tests.viewers.VirtualTableViewerTest.testContains` also randomly fails, e.g., 
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1086/checks?check_run_id=16671995346 
```
element must be available on the viewer
junit.framework.AssertionFailedError: element must be available on the viewer
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at org.eclipse.jface.tests.viewers.TableViewerTest.testContains(TableViewerTest.java:200)
```

**Comment by vogella** [comment]
Seems to fails all the time on Mac. @sratz could you have a look if this can be fixed or if it should be disabled on Mac?

**Comment by BeckerWdf** [comment]
also reported in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1283
