### ISSUE TITLE
ClassCastException:  ExpandableNode cannot be cast to class MarkerSupportItem

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1008]
I configured problem filters to show all items and then it still did not show all items (i have not seen that behavior before). then i clicked on "Show 1.001...2000" (reproducible with higher numbers too)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/b4652cb1-0888-4205-934f-21ed4056447f)
and got
```
java.lang.ClassCastException: 
class org.eclipse.jface.viewers.internal.ExpandableNode 
cannot be cast to class 
org.eclipse.ui.internal.views.markers.MarkerSupportItem
(org.eclipse.jface.viewers.internal.ExpandableNode is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @612406a0; org.eclipse.ui.internal.views.markers.MarkerSupportItem is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @658fdcf7)
	at org.eclipse.ui.internal.views.markers.ExtendedMarkersView.getOpenableMarkers(ExtendedMarkersView.java:586)
	at org.eclipse.ui.internal.views.markers.ExtendedMarkersView.openSelectedMarkers(ExtendedMarkersView.java:1155)
	at org.eclipse.ui.internal.views.markers.ExtendedMarkersView$4.open(ExtendedMarkersView.java:572)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:800)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:797)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1115)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:296)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:331)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

**Comment by jukzi** [comment]
@iloveeclipse  regression from https://github.com/eclipse-platform/eclipse.platform.ui/issues/818 ?

**Comment by jukzi** [comment]
When i configure the view to show 20000 elements i know what i am doing and do not expect to get asked for every 1000 to expand!

**Comment by iloveeclipse** [comment]
> @iloveeclipse regression from #818 ?

Sure. Should be easy to fix.

> When i configure the view to show 20000 elements i know what i am doing and do not expect to get asked for every 1000 to expand!

Correct. This filter can be removed / replaced by using custom limit on the viewer that currently uses global preference. 

@raghucssit : please check this both issues.

**Comment by iloveeclipse** [comment]
> When i configure the view to show 20000 elements i know what i am doing and do not expect to get asked for every 1000 to expand!

To avoid tracking multiple issues in one ticket I've created https://github.com/eclipse-platform/eclipse.platform.ui/issues/1010.
