### ISSUE TITLE
SoftLimit: provide extra context menus to expand all/all recursive

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1025]
from https://github.com/eclipse-platform/eclipse.platform.ui/issues/818
Right click on an element should show a context menu - but on a soft limit line it also expands the list - losing the context of the click.

Would be good if the context menu allows to
* show all 
* show all recursive

And it must NOT show the typical actions that make no sense on a soft limit node.

**Comment by jukzi** [comment]
Using the context menu actions on a softlimit currently run into errors like
```
org.eclipse.core.commands.ExecutionException: Error executing 'org.eclipse.ui.ide.markers.copyMarkerResourceQualifiedName': java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)


```
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/fdb4c8a9-3433-465b-9743-f0b2ba2574fa)

**Comment by Phillipus** [comment]
> Would be good if the context menu allows to
> - show all

That is something I immediately wanted when I tested it in our RCP app. +1

Or at least the API to show all.

**Comment by laeubi** [comment]
Instead of context menu one could use SWT `Link` and then use 

[Show more ...](url) | [Show all ...](url) instead of the confusing `Show 61...70 (318)`

**Comment by Phillipus** [comment]
Regarding context menus. We have a `TreeViewer` that is created inside of a `ViewPart`. The context menu items for the tree are created in the `ViewPart` and we need to access `ColumnViewer#isExpandableNode` to ensure not to create our context menu in this case. `ColumnViewer#isExpandableNode` is protected. If it was public or static that would help.

BTW, docs for `TreeViewer` say `This class is not intended to be subclassed by clients`. I have to ignore that advice most times to do anything useful.

**Comment by iloveeclipse** [comment]
> `ColumnViewer#isExpandableNode` is protected. If it was public or static that would help

It **is** public now, it was an oversight, thanks for raising this item.

**Comment by laeubi** [comment]
> > `ColumnViewer#isExpandableNode` is protected. If it was public or static that would help
> 
> It **is** public now, it was an oversight, thanks for raising this item.

I don't think it is/was an oversight, the whole intent was as requested by @mickaelistria to not make the fact public, the method was added because it was argued that **extenders** of a viewer still need to know/use that so it was made a protected method, but usual users of a viewer should never need to know there is an `ExpandableNode`, if this is still needed this more show there is still a problem like with the selection we recently see, so maybe @Phillipus can explain *why* he still need to add special check in the code, e.g. for a contextmenu it might be suitable enough to make a *positive* check (e.g. only create it if it is one of the model objects) anyways instead of blacklisting that single node, but given one uses the current selection it should now hopefully be empty anyways for a `ExpandableNode`

**Comment by mickaelistria** [comment]
`ColumnViewer#isExpandableNode` shouldn't need to be public. context-menu should be fully disabled, internally in the viewer, for the expandable node. External contributors shouldn't participate to context-menu.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1041 would make this issue less critical or even not relevant.

**Comment by mickaelistria** [comment]
I have indeed opened https://github.com/eclipse-platform/eclipse.platform.ui/issues/1044 ; I am convinced that anything that even expose the idea that there is a "Show ..." item via API is an anti-pattern and that we, or someone else, are likely to regret it later when we decide to modify how the viewer work.
