### ISSUE TITLE
SoftLimit: Viewer.fireSelectionChanged() is fired with ExpandableNode instead of EMPTY selection

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1027]
```
An error has occurred. See error log for more details.
class org.eclipse.jface.viewers.internal.ExpandableNode cannot be cast to class org.eclipse.jdt.internal.junit.model.TestElement (org.eclipse.jface.viewers.internal.ExpandableNode is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6f94fb9d; org.eclipse.jdt.internal.junit.model.TestElement is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1981d861)
```
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/f67156d7-4f6f-4eff-b4ac-acc38f5cd19a)

**Comment by laeubi** [comment]
@jukzi can you share a full stacktrace?

I though it was discussed in the initial change that actually the default handlers should not be called, I assume that its an `ISelectionHandler` here that is still called while it should behave as if the selection was changed to an empty one...

**Comment by jukzi** [comment]
```
java.lang.ClassCastException: class org.eclipse.jface.viewers.internal.ExpandableNode cannot be cast to class org.eclipse.jdt.internal.junit.model.TestElement (org.eclipse.jface.viewers.internal.ExpandableNode is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6f94fb9d; org.eclipse.jdt.internal.junit.model.TestElement is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1981d861)
	at org.eclipse.jdt.internal.junit.ui.TestViewer.handleSelected(TestViewer.java:470)
	at org.eclipse.jdt.internal.junit.ui.TestViewer$TestSelectionListener.selectionChanged(TestViewer.java:93)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionProviderMediator.fireSelectionChanged(SelectionProviderMediator.java:135)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionProviderMediator.doSelectionChanged(SelectionProviderMediator.java:118)
	at org.eclipse.jdt.internal.ui.viewsupport.SelectionProviderMediator$InternalListener.selectionChanged(SelectionProviderMediator.java:44)
	at org.eclipse.jface.viewers.Viewer$1.run(Viewer.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2137)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1669)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1106)
	at org.eclipse.jface.viewers.TreeViewer.handleExpandableNodeClicked(TreeViewer.java:1170)
	at org.eclipse.jface.viewers.ColumnViewer.handleMouseDown(ColumnViewer.java:671)
	at org.eclipse.jface.viewers.ColumnViewer$1.mouseDown(ColumnViewer.java:115)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:196)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

```

**Comment by laeubi** [comment]
@jukzi I adjusted the title to reflect the real issue, this should be fixed in the viewer to handle a selection of the expandable node like an empty selection.

**Comment by iloveeclipse** [comment]
@raghucssit , please take a look.
