### ISSUE TITLE
[mac] UI freezes when fiddling with in-place editing (TableViewer, ColumnViewerEditorActivationStrategy, EditingSupport, macOS)

### ISSUE THREAD

**Issue by buchen** [eclipse-platform/eclipse.platform.ui#1069]
### The problem

The SWT/JFace application **freezes (no longer accepts input, shows beachball) and uses 100 % of CPU** (according to process monitor) when doing in-place editing rapidly/multiple times with a **TableViewer, EditingSupport, TextCellEditor and a ColumnViewerEditorActivationStrategy that activates on double click**.

Check out this recording - the issues happens roughly 25 seconds into the video. The app freezes.

<details>
<summary>Screen recording</summary>

https://github.com/eclipse-platform/eclipse.platform.ui/assets/587976/74ae3b2b-795f-4811-bc7e-7e370947d102

</details>

### Versions

Eclipse: https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230827-1800/  (latest integration build of 27 August 2023)
macOS: Ventura 13.5 (22G74)

### Steps to reproduce the behavior

* Run sample application (source code below)
* Double click multiple times on cells to activate/deactivate cell editor
* Application freezes, uses 100% CPU

### Observations

* The problem looks specific  to macOS (that's where I see it and get it reported)
* I was not able to reproduce it with a plain SWT Table (Snippets 88 and 124) - only with TableViewer/EditingSupport/ColumnViewerEditorActivationStrategy
* The main thread hangs here (see full thread dump below)
```
"main" #1 prio=5 os_prio=31 cpu=123579.35ms elapsed=158.54s tid=0x000000011e008a00 nid=0x103 runnable  [0x000000016f0eb000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1147)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1139)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2642)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6320)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2264)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2511)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6444)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5692)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5831)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3986)
	at org.eclipse.swt.snippets.TestSnippet.main(TestSnippet.java:110)
```

### Sample source code and full thread dump

<details>
<summary>The Sample code (based on snippets)</summary>

```java
package org.eclipse.swt.snippets;

import java.util.List;

import org.eclipse.jface.viewers.ArrayContentProvider;
import org.eclipse.jface.viewers.CellEditor;
import org.eclipse.jface.viewers.ColumnLabelProvider;
import org.eclipse.jface.viewers.ColumnViewerEditor;
import org.eclipse.jface.viewers.ColumnViewerEditorActivationEvent;
import org.eclipse.jface.viewers.ColumnViewerEditorActivationStrategy;
import org.eclipse.jface.viewers.EditingSupport;
import org.eclipse.jface.viewers.TableViewer;
import org.eclipse.jface.viewers.TableViewerColumn;
import org.eclipse.jface.viewers.TableViewerEditor;
import org.eclipse.jface.viewers.TextCellEditor;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class TestSnippet
{
    private static final class TestEditingSupport extends EditingSupport
    {
        private final TableViewer viewer;
        private final CellEditor editor;

        private TestEditingSupport(TableViewer viewer)
        {
            super(viewer);
            this.viewer = viewer;
            this.editor = new TextCellEditor(viewer.getTable());
        }

        @Override
        protected void setValue(Object element, Object value)
        {
            ((Item) element).name = (String) value;
            viewer.update(element, null);
        }

        @Override
        protected Object getValue(Object element)
        {
            return ((Item) element).name;
        }

        @Override
        protected CellEditor getCellEditor(Object element)
        {
            return editor;
        }

        @Override
        protected boolean canEdit(Object element)
        {
            return true;
        }
    }

    static class Item
    {
        public Item(String name)
        {
            this.name = name;
        }

        String name;
    }

    public static void main(String[] args)
    {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setText("Test Snippet");
        shell.setLayout(new FillLayout());

        TableViewer tableViewer = new TableViewer(shell, SWT.FULL_SELECTION | SWT.HIDE_SELECTION);

        TableViewerColumn column1 = new TableViewerColumn(tableViewer, SWT.NONE);
        column1.setLabelProvider(ColumnLabelProvider.createTextProvider(e -> ((Item) e).name));
        column1.getColumn().setWidth(500);

        var editingSupport = new TestEditingSupport(tableViewer);

        column1.setEditingSupport(editingSupport);

        tableViewer.setContentProvider(ArrayContentProvider.getInstance());
        tableViewer.setInput(List.of(new Item("one"), new Item("two"), new Item("three")));

        ColumnViewerEditorActivationStrategy activationStrategy = new ColumnViewerEditorActivationStrategy(tableViewer)
        {
            @Override
            protected boolean isEditorActivationEvent(ColumnViewerEditorActivationEvent event)
            {
                return event.eventType == ColumnViewerEditorActivationEvent.TRAVERSAL
                                || event.eventType == ColumnViewerEditorActivationEvent.MOUSE_DOUBLE_CLICK_SELECTION
                                || (event.eventType == ColumnViewerEditorActivationEvent.KEY_PRESSED
                                                && event.keyCode == SWT.CR)
                                || event.eventType == ColumnViewerEditorActivationEvent.PROGRAMMATIC;
            }
        };

        int feature = ColumnViewerEditor.TABBING_HORIZONTAL | ColumnViewerEditor.TABBING_MOVE_TO_ROW_NEIGHBOR
                        | ColumnViewerEditor.TABBING_VERTICAL | ColumnViewerEditor.KEYBOARD_ACTIVATION;

        TableViewerEditor.create(tableViewer, null, activationStrategy, feature);

        shell.setSize(300, 300);
        shell.open();

        while (!shell.isDisposed())
        {
            if (!display.readAndDispatch())
                display.sleep();
        }
        display.dispose();
    }

}
```

</details>

<details>
<summary>Thread dump</summary>

```
2023-08-28 16:30:40
Full thread dump OpenJDK 64-Bit Server VM (17.0.5+8-LTS mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x0000600003b52800, length=12, elements={
0x000000011e008a00, 0x000000011d902c00, 0x000000011d905400, 0x000000011f014400,
0x000000011f016c00, 0x000000011f017200, 0x000000011f017800, 0x000000011f017e00,
0x000000011f020400, 0x000000011d012200, 0x000000011d903200, 0x000000016ad10a00
}

"main" #1 prio=5 os_prio=31 cpu=123579.35ms elapsed=158.54s tid=0x000000011e008a00 nid=0x103 runnable  [0x000000016f0eb000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1147)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1139)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2642)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6320)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:236)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2264)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2511)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6444)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5692)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5831)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:117)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3986)
	at org.eclipse.swt.snippets.TestSnippet.main(TestSnippet.java:110)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=0.12ms elapsed=158.51s tid=0x000000011d902c00 nid=0x4d03 waiting on condition  [0x000000016ffce000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@17.0.5/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@17.0.5/Reference.java:253)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@17.0.5/Reference.java:215)

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.05ms elapsed=158.51s tid=0x000000011d905400 nid=0x4c03 in Object.wait()  [0x00000001701da000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.5/Native Method)
	- waiting on <0x000000061e410178> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.5/ReferenceQueue.java:155)
	- locked <0x000000061e410178> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.5/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@17.0.5/Finalizer.java:172)

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.14ms elapsed=158.50s tid=0x000000011f014400 nid=0x5a03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=1.22ms elapsed=158.50s tid=0x000000011f016c00 nid=0x7b03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=31 cpu=2.16ms elapsed=158.50s tid=0x000000011f017200 nid=0x7903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #7 daemon prio=9 os_prio=31 cpu=733.29ms elapsed=158.50s tid=0x000000011f017800 nid=0x7703 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"C1 CompilerThread0" #10 daemon prio=9 os_prio=31 cpu=341.35ms elapsed=158.50s tid=0x000000011f017e00 nid=0x5c03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"Sweeper thread" #11 daemon prio=9 os_prio=31 cpu=0.03ms elapsed=158.50s tid=0x000000011f020400 nid=0x5e03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Notification Thread" #12 daemon prio=9 os_prio=31 cpu=0.03ms elapsed=158.49s tid=0x000000011d012200 nid=0x6003 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Common-Cleaner" #13 daemon prio=8 os_prio=31 cpu=0.28ms elapsed=158.49s tid=0x000000011d903200 nid=0x7303 in Object.wait()  [0x000000017155e000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.5/Native Method)
	- waiting on <0x000000061e428178> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.5/ReferenceQueue.java:155)
	- locked <0x000000061e428178> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@17.0.5/CleanerImpl.java:140)
	at java.lang.Thread.run(java.base@17.0.5/Thread.java:833)
	at jdk.internal.misc.InnocuousThread.run(java.base@17.0.5/InnocuousThread.java:162)

   Locked ownable synchronizers:
	- None

"Attach Listener" #15 daemon prio=9 os_prio=31 cpu=0.40ms elapsed=12.31s tid=0x000000016ad10a00 nid=0x7f07 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=31 cpu=15.31ms elapsed=158.51s tid=0x000000011ce05b10 nid=0x5003 runnable  

"GC Thread#0" os_prio=31 cpu=1.79ms elapsed=158.53s tid=0x000000011cf06be0 nid=0x2f03 runnable  

"GC Thread#1" os_prio=31 cpu=1.81ms elapsed=158.04s tid=0x000000011e8830c0 nid=0xb403 runnable  

"GC Thread#2" os_prio=31 cpu=1.72ms elapsed=158.04s tid=0x000000011e87aea0 nid=0xb503 runnable  

"GC Thread#3" os_prio=31 cpu=1.86ms elapsed=158.04s tid=0x000000011e887540 nid=0xb603 runnable  

"GC Thread#4" os_prio=31 cpu=1.80ms elapsed=158.04s tid=0x000000011e87a540 nid=0xb703 runnable  

"GC Thread#5" os_prio=31 cpu=1.98ms elapsed=158.04s tid=0x000000011e88ced0 nid=0xb903 runnable  

"GC Thread#6" os_prio=31 cpu=1.52ms elapsed=158.04s tid=0x000000011e87c970 nid=0xba03 runnable  

"GC Thread#7" os_prio=31 cpu=2.07ms elapsed=158.04s tid=0x000000011e87d6c0 nid=0xbb03 runnable  

"GC Thread#8" os_prio=31 cpu=2.10ms elapsed=158.04s tid=0x000000011e87cef0 nid=0xbc03 runnable  

"G1 Main Marker" os_prio=31 cpu=0.02ms elapsed=158.53s tid=0x000000011cf07290 nid=0x3803 runnable  

"G1 Conc#0" os_prio=31 cpu=0.01ms elapsed=158.53s tid=0x000000011cf07b20 nid=0x3603 runnable  

"G1 Refine#0" os_prio=31 cpu=0.03ms elapsed=158.53s tid=0x000000011cf09c50 nid=0x3303 runnable  

"G1 Service" os_prio=31 cpu=11.43ms elapsed=158.53s tid=0x000000011cf0a4f0 nid=0x4103 runnable  

"VM Periodic Task Thread" os_prio=31 cpu=40.04ms elapsed=158.49s tid=0x000000011ce083a0 nid=0x7503 waiting on condition  

JNI global refs: 98, weak refs: 0

```
</details>

**Comment by darkmattercoder** [comment]
Is that ever going to be addressed? This bug is open quite a while (sic!) now....

**Comment by HeikoKlare** [comment]
> Is that ever going to be addressed?

Since the issue is open for quite a while, I guess that consumers actively involved into Eclipse development are not affected by it (or don't consider it a severe issue) and will thus not invest into fixing it. So you probably have to chose between analyzing and fixing the issue on your own or actively finding/funding someone doing that work for you.

**Comment by ralappp** [comment]
FYI from a downstream perspective: this issue was just hit again in Portfolio Performance on macOS Sonoma 14.8.2 (M1) with PP 0.83.2 / SWT 4971r15 / Azul Zulu JRE 21.0.5 — reported as [portfolio-performance/portfolio#5705](https://github.com/portfolio-performance/portfolio/issues/5705). Symptoms match this issue exactly: in-place rename via TableViewer + TextCellEditor, fast double-click followed by a second click inside the selected text, main thread spinning at 100% CPU, force quit required.

I captured a `sample` of the frozen process. The Java thread dump above stops at `objc_msgSendSuper` (the JNI boundary), but the native sample goes deeper into AppKit and identifies the specific spin location. Top frames on the main thread for the entire 1923-sample capture:

```
DispatchQueue_1: com.apple.main-thread
  ...
  Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSendSuper__...  (in libswt-pi-cocoa-4971r15.jnilib)
    -[NSTextView mouseDown:]                                       (in AppKit)
      -[NSTextView _bellerophonTrackMouseWithMouseDownEvent:...]   (in AppKit)
        -[NSTextSelectionNavigation textSelectionsInteractingAtPoint:...]  (in UIFoundation)
          -[NSTextSelectionNavigation _lineFragmentInfoForPoint:...]       (in UIFoundation)
            -[NSTextLayoutManager enumerateTextLayoutFragmentsFromLocation:options:usingBlock:]
              [tight loop in objc_sync_enter/exit, objc_loadWeak,
               NSTextContentStorage synchronizeTextLayoutManagers:]
```

The `_bellerophonTrack...` path is the TextKit 2 mouse tracking implementation that became the default for NSTextView in macOS Ventura. The spin happens inside `textSelectionsInteractingAtPoint:` (the same method Apple tracks under FB11898356 for unrelated correctness bugs), which lines up with the timing dependency reported here — a second `mouseDown:` arriving before TextKit 2 has settled the selection from the first click.

This also matches the cross-version pattern in the PP forum reports (none on Monterey, present on Ventura/Sonoma/Sequoia, no fix observed on macOS 26 Tahoe so far), which is consistent with TextKit 2 becoming the default for NSTextView in Ventura.

**Possible direction for a SWT-side mitigation**: opting the in-place editor's `NSTextView` out of TextKit 2 (e.g. via `setUsesTextKit2:NO`, or by routing through the TextKit 1 initializer) should send `mouseDown:` through the legacy `NSLayoutManager` code path and avoid `_bellerophonTrack...` entirely. Wouldn't fix the underlying AppKit bug but would side-step it for SWT until Apple addresses it.

Full process sample attached. Application-level workarounds via `defaults write ... NSTextKit_textViewUsesTextKit2ByDefault -bool NO` and `NSUseTextKit2 -bool NO` did not work, which is expected since SWT instantiates `NSTextView` natively without consulting those defaults.

Happy to test patches on this Mac if useful.

---
*Note: the process sample interpretation and write-up of this comment were assisted by Claude AI.*

[PP-sample.txt](https://github.com/user-attachments/files/28091264/PP-sample.txt)

**Comment by buchen** [comment]
Thanks @ralappp for the analysis.

For now, I have forced a downgrade to TextKit 1 by calling layoutManager.

It seems to work. 🥳
I was not able to reproduce the problem so far. Of course, it is not deterministic.
I have published a test build - see https://github.com/portfolio-performance/portfolio/issues/5705#issuecomment-4521482518


```diff
diff --git a/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Shell.java b/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Shell.java
index 5c7cc8e993..823d12cd6a 100644
--- a/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Shell.java	
+++ b/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Shell.java	
@@ -776,7 +776,15 @@ void createHandle () {
 	id id = fieldEditorWindow.fieldEditor (true, null);
 	if (id != null) {
 		OS.object_setClass (id.id, OS.objc_getClass ("SWTEditorView"));
-		new NSTextView(id).setAllowsUndo(true);
+		NSTextView fieldEditor = new NSTextView(id);
+		fieldEditor.setAllowsUndo(true);
+		/*
+		 * Accessing layoutManager forces the field editor off TextKit 2 onto
+		 * TextKit 1 for its lifetime, avoiding an AppKit freeze during
+		 * mouseDown:. See eclipse.platform.ui#1069. Side-effecting call -
+		 * the returned value is intentionally unused.
+		 */
+		fieldEditor.layoutManager();
 	}
 
 }
diff --git a/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Text.java b/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Text.java
index 4cd3d99b13..1481c6a9ac 100644
--- a/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Text.java	
+++ b/bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Text.java	
@@ -587,6 +587,8 @@ void createWidget () {
 		if (fieldEditor != null && nsSecureTextViewClass != 0 && fieldEditor.isKindOfClass(nsSecureTextViewClass)) {
 			long editorClass = OS.objc_getClass("SWTSecureEditorView");
 			OS.object_setClass(fieldEditor.id, editorClass);
+			/* Force TextKit 1 on the secure field editor too (see Shell.createHandle). */
+			new NSTextView(fieldEditor).layoutManager();
 		}
 	}
 	doubleClick = true;
```

**Comment by buchen** [comment]
@HeikoKlare BTW, is there some documentation how to integrate a patched SWT version into a Maven Tycho RCP application? I ended up adding an update site to org.eclipse.swt, forcing the same qualifier (because other bundles have an exact dependency) and ordering this in the target platform definition first.

**Comment by HeikoKlare** [comment]
There are different options for using a modified SWT version (or any other bundle) depending on the situation/goal:
- **Already or to-be-built product**: if you have an already built product or want to build one and want to patch that, you can integrate an updated version of a bundle with a feature patch (see, e.g., https://wiki.eclipse.org/JDT_UI/Howto/Create_Feature_Patch). You have to create that feature patch and deploy it to an update site, so that you can install it into your product
- **To-be-built product**: if you want to a build a product with the modified SWT bundle, you may use a feature patch like described above, but you could directly integrate it into your build or use the update site to which you deployed it in your product build (instead of installing it later on). Another option might be to deploy the patched bundle to an update site (without a feature patch) and then create your own update site out of all the dependencies, but the feature patch option should be less effort and more suited for the case.
- **Runtime product during development**: when you start a product out of an IDE in a development setup, you can simply import the SWT projects (host + fragment) into the workspace and start the product with the patched SWT version from that workspace. That's usually the first step for testing changes before you do the higher-effort integration into a deployable product.

**Comment by buchen** [comment]
Thanks @HeikoKlare for the hint about feature patches. I couldn't make Tycho consume the feature patch from a separate update site but was able to build it if the feature patch is part of the project itself. I will report what users will report.

**Comment by Phillipus** [comment]
It's easy enough to reproduce this consistently on a Mac in Eclipse:

1. Open a Debug Configuration dialog
2. Go to the "Environment" tab
3. Ensure that there is already a Variable and Value entry in the table
4. Double-click on a table cell to edit it. Single click on it.
5. Repeat (4) a few times until the beach ball arrives...

**Comment by buchen** [comment]
Just FYI: I am distributing a version of SWT that includes this patch as part of my [RCP application](https://github.com/portfolio-performance/portfolio) to thousands of users. So far no further complaints about the UI freezing in-place editor. It seems safe.
