### ISSUE TITLE
WizardDialog: Widget is disposed

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1094]
upon RefactoringWizardDialog.finishPressed():

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:450)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Label.setImage(Label.java:348)
	at org.eclipse.jface.dialogs.TitleAreaDialog.setTitleImage(TitleAreaDialog.java:692)
	at org.eclipse.jface.wizard.WizardDialog.hardClose(WizardDialog.java:898)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:845)
	at org.eclipse.ltk.internal.ui.refactoring.RefactoringWizardDialog.finishPressed(RefactoringWizardDialog.java:109)
```

**Comment by jukzi** [comment]
relates to https://bugs.eclipse.org/bugs/show_bug.cgi?id=202534
