### ISSUE TITLE
Unhandled event loop exception reported during "Open Implementation" action

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1107]
Open any Java type, e.g. ArrayList and try to "Ctrl+Click -> Open Implementation" => "Unhandled event loop exception" error will be reported to the log.

This is a regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1077.

Whatever the code was trying to to with the monitors (and if they provided any meaningful progress) is a different story, but so far I haven't seen issues trying to use "Open Implementation" action.

```
eclipse.buildId=4.30.0.I20230912-1800
java.version=17.0.6-internal
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /data/4x_platform_workspace -os linux -ws gtk -arch x86_64

org.eclipse.ui
Error
Wed Sep 13 09:26:58 CEST 2023
Unhandled event loop exception

java.lang.IllegalStateException: beginTask should only be called once per instance. At least call done() before further invocations
	at org.eclipse.jface.action.StatusLineManager$1.beginTask(StatusLineManager.java:157)
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.lambda$0(AccumulatingProgressMonitor.java:148)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:166)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:368)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$7(WorkbenchWindow.java:2346)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2344)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementImplementationHyperlink.openImplementations(JavaElementImplementationHyperlink.java:290)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaElementImplementationHyperlink.open(JavaElementImplementationHyperlink.java:146)
	at org.eclipse.jface.text.hyperlink.MultipleHyperlinkPresenter$LinkListInformationControl.openSelectedLink(MultipleHyperlinkPresenter.java:354)
	at org.eclipse.jface.text.hyperlink.MultipleHyperlinkPresenter$LinkListInformationControl$4.mouseUp(MultipleHyperlinkPresenter.java:326)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.IllegalStateException: beginTask(Searching for implementors of 'java.util.ArrayList'..., 10) was called here previously
	at org.eclipse.jface.action.StatusLineManager$1.beginTask(StatusLineManager.java:162)
	... 42 more
```

**Comment by jukzi** [comment]
> Whatever the code was trying to to with the monitors (and if they provided any meaningful progress) is a different story, but so far I haven't seen issues trying to use "Open Implementation" action.

Try the same on `Object` with an older eclipse version. => heavy freeze for minutes.

**Comment by mickaelistria** [comment]
> Try the same on Object with an older eclipse version. => heavy freeze for minutes.

Not having correct results is a regression compared to having correct results after a freeze.

**Comment by jukzi** [comment]
> Not having correct results is a regression compared to having correct results after a freeze.

Sure. Just to fix all those freezes, we temporarily need an indicator where they are.

**Comment by jukzi** [comment]
fun fact: org.eclipse.core.runtime.SlicedProgressMonitor.beginTask(String, int) has the same IllegalStateException on second call.

Still searching for a solution - the super duper org.eclipse.core.runtime.SubMonitor.convert(IProgressMonitor, String, int) calls beginTask on a passed instance, which is clearly forbidden :-(

**Comment by iloveeclipse** [comment]
> Still searching for a solution

There are two things that can be done **independently**:
1) Replace `throw new IllegalStateException` with logging in [StatusLineManager](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1077/files/e59868b99027ae4541aaca8b445f8b617b1583d8#diff-f30725416a7bfb0cd57f5ce71a869395ad62f46e70f22b9c93f7882304a71dd4), as requested in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1077#issuecomment-1715170259
2) Find the root cause of this issue.

If the later one takes more time, please fix the first one ASAP.

I have currently IDE with the broken status line, which goes not away:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/1ca4077c-a4d3-4189-b67e-e76b1300743b)

**Comment by iloveeclipse** [comment]
Interestingly, I see sooner or later after restart **without** using "Open Implementation" broken status line (no errors **logged**!).

Now it looks like this:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/ca61bf11-5c7e-4aee-b19d-a6127526c4f8)

**Comment by jukzi** [comment]
What is the difference for "Ctrl+Click -> Open Implementation" and CTRL+T? Same popup opens, but slightly different progressmonitor.
