### ISSUE TITLE
Compare editor logs warning on open

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1125]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1115
Open any text file, change, save and compare with the local history (same with git history) => warning reported to the error log.

```
eclipse.buildId=4.30.0.I20230917-1800
java.version=17.0.6-internal

org.eclipse.jface
Warning
Mon Sep 18 09:10:27 CEST 2023
beginTask should only be called once per instance. At least call done() before further invocations

java.lang.IllegalStateException: beginTask should only be called once per instance. At least call done() before further invocations
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:148)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:483)
	at org.eclipse.compare.rangedifferencer.RangeComparatorLCS.findDifferences(RangeComparatorLCS.java:30)
	at org.eclipse.compare.rangedifferencer.RangeDifferencer.findDifferences(RangeDifferencer.java:100)
	at org.eclipse.compare.rangedifferencer.RangeDifferencer.findRanges(RangeDifferencer.java:289)
	at org.eclipse.compare.rangedifferencer.RangeDifferencer.findRanges(RangeDifferencer.java:365)
	at org.eclipse.compare.rangedifferencer.RangeDifferencer.findRanges(RangeDifferencer.java:345)
	at org.eclipse.compare.internal.merge.DocumentMerger.lambda$0(DocumentMerger.java:408)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.IllegalStateException: beginTask(Computing Differences..., 1890) was called here previously
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:155)
	at org.eclipse.compare.internal.merge.DocumentMerger.lambda$0(DocumentMerger.java:406)
	... 1 more
```

**Comment by jukzi** [comment]
like in jdt
DocumentMerger.lambda$0(DocumentMerger.java:408) calls beginTask and then
RangeComparatorLCS.findDifferences(RangeComparatorLCS.java:30) calls SubMonitor.convert which is forbidden by javadoc.

**Comment by iloveeclipse** [comment]
Remaining issue: with files from git there is yet another place where monitor warning is reported:
```
eclipse.buildId=4.30.0.I20230918-1800
java.version=17.0.6-internal

org.eclipse.jface
Warning
Tue Sep 19 11:47:27 CEST 2023
beginTask should only be called once per instance. At least call done() before further invocations

java.lang.IllegalStateException: beginTask should only be called once per instance. At least call done() before further invocations
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:148)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:483)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:449)
	at org.eclipse.egit.core.synchronize.GitSyncCache.mergeAllDataIntoCache(GitSyncCache.java:68)
	at org.eclipse.egit.core.synchronize.GitSyncCache.getAllData(GitSyncCache.java:61)
	at org.eclipse.egit.core.synchronize.GitSyncCache.getAllData(GitSyncCache.java:54)
	at org.eclipse.egit.core.synchronize.GitResourceVariantTreeSubscriber.init(GitResourceVariantTreeSubscriber.java:105)
	at org.eclipse.egit.ui.internal.synchronize.ModelAwareGitSynchronizer.createResourceMappingContext(ModelAwareGitSynchronizer.java:218)
	at org.eclipse.egit.ui.internal.synchronize.ModelAwareGitSynchronizer$2.run(ModelAwareGitSynchronizer.java:101)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.IllegalStateException: beginTask(Fetching data from git repositories, 1) was called here previously
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:155)
	at org.eclipse.egit.core.synchronize.GitResourceVariantTreeSubscriber.init(GitResourceVariantTreeSubscriber.java:101)
	... 3 more
```

**Comment by jukzi** [comment]
> Remaining issue: with files from git there is yet another place where monitor warning is reported:

Can you replace beginTask with setTaskName(), please?

**Comment by iloveeclipse** [comment]
> Can you replace beginTask with setTaskName(), please?

Jörg, I'm not sure what do you mean by that.

**Comment by jukzi** [comment]
in GitResourceVariantTreeSubscriber.java:101, i think you have commit rights there.

**Comment by iloveeclipse** [comment]
OK, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=582435 & https://git.eclipse.org/r/c/egit/egit/+/204433

**Comment by iloveeclipse** [comment]
Fixed with latest SDK/egit builds

**Comment by vogella** [comment]
> Fixed with latest SDK/egit builds

Similar issue in nightly Egit build, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=582511
