### ISSUE TITLE
IllegalStateException toggling whitespace on/off in diff editor

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1144]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1115.

Open diff editor and toggle "Ignore whitespace" on/off - every time warning below is logged.

```
java.lang.IllegalStateException: beginTask should only be called once per instance. At least call done() before further invocations
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:148)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:483)
	at org.eclipse.core.runtime.SubMonitor.convert(SubMonitor.java:449)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.lambda$7(StructureDiffViewer.java:532)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.IllegalStateException: beginTask(Generating Structure Differences, 100) was called here previously
	at org.eclipse.jface.operation.AccumulatingProgressMonitor.beginTask(AccumulatingProgressMonitor.java:155)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.lambda$7(StructureDiffViewer.java:531)
	... 1 more
```

**Comment by iloveeclipse** [comment]
@jukzi : could you please check this one?
