### ISSUE TITLE
Both Synchronizing and populating “Synchronize view” of “Team Sync Perspective” often hangs

### ISSUE THREAD

**Issue by ideas-into-software** [eclipse-platform/eclipse.platform.ui#1315]
- Both Synchronizing and populating “Synchronize view” of “Team Sync Perspective” often hangs – regardless if going through “Populate” or “Synchronize”;
- In `Progress` view, `Minimizing synchronization model` and `Updating Synchronize view for Git without local changes.` can be seen;
- I suspected this may have something to do with EMF files (Ecore or XMI) in one of the projects present in workspace, but I cannot verify with 100% certainty that this is somehow related – those files are present and committed, there are no changes in those files, yet same problem occurs;
- In all cases when this problem occurs, it causes Eclipse to stop responding and, when this happens, killing of Eclipse process is required in order to continue;
- Regardless of version of Eclipse and plugins used, frequency of occurrence of this problem completely disrupts normal work flow;
- Please see attached screenshots, screencasts, and log samples for details;

## Setup
**Eclipse IDE**: 
    • Version 2023-09 (4.29.0)
    • Build id: 4.29.0.20230907-1200
**JGit**: 6.7.0.202309050840-r
**EGit**: 6.7.0.202309050840-r
**OS**: Ubuntu 22.04.3 LTS
**Hardware**: Dell Precision 7560, Intel® Xeon(R) W-11855M CPU, 64 GB RAM, M.2 SSD disks

In case more details are needed, I also saved output from Eclipse IDE installation details “Configuration” tab: see attached `eclipse-20230907-1200_bndtools-7.0.0.REL_configuration.txt` file.

## Attachments

[Team-Sync-Perspective_issues_screenshots.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/13404866/Team-Sync-Perspective_issues_screenshots.zip)
[Team-Sync-Perspective_issues_logs.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/13404868/Team-Sync-Perspective_issues_logs.zip)
[Team-Sync-Perspective_issues_screencasts.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/13404872/Team-Sync-Perspective_issues_screencasts.zip)
[eclipse-20230907-1200_bndtools-7.0.0.REL_configuration.txt](https://github.com/eclipse-platform/eclipse.platform.ui/files/13404870/eclipse-20230907-1200_bndtools-7.0.0.REL_configuration.txt)

**Comment by merks** [comment]
Please use `jstack <process-id>` to collect stack traces of the process.   Then we can see exactly what each thread is doing.  On Windows you can see the process ID in the Task Manager's Details tab.

**Comment by ideas-into-software** [comment]
@merks

As per your request, here are five samples taken when this problem occurred.

Sample no. 1 and 2 refers to same process - i.e. 2nd taken several minutes after 1st was taken, in case that can be useful.

The other 3 samples are separate events when this problem occurred - i.e. 3 times in a row on same day.

This problem occurs in well over 50% cases when I am about to prepare a commit, so until it is fixed I am forced to switch to a different IDE (for staging and committing step).

Thank you for your help.

[Team-Sync-Perspective_issues_jstack.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/13790064/Team-Sync-Perspective_issues_jstack.zip)

**Comment by merks** [comment]
It looks like the main thread is showing progress (or in some cases idle) but the other threads are busy with EMF Compare things, one of which appears to be doing network communication:
```
"EMFCompare-ResolvingThread-0" #357 prio=5 os_prio=0 cpu=430.02ms elapsed=85.61s tid=0x00007fee5019e850 nid=0x3564d runnable  [0x00007feebcdfc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.SocketDispatcher.read0(java.base@17.0.6/Native Method)
	at sun.nio.ch.SocketDispatcher.read(java.base@17.0.6/SocketDispatcher.java:47)
	at sun.nio.ch.NioSocketImpl.tryRead(java.base@17.0.6/NioSocketImpl.java:261)
	at sun.nio.ch.NioSocketImpl.implRead(java.base@17.0.6/NioSocketImpl.java:312)
	at sun.nio.ch.NioSocketImpl.read(java.base@17.0.6/NioSocketImpl.java:350)
	at sun.nio.ch.NioSocketImpl$1.read(java.base@17.0.6/NioSocketImpl.java:803)
	at java.net.Socket$SocketInputStream.read(java.base@17.0.6/Socket.java:966)
	at java.io.BufferedInputStream.fill(java.base@17.0.6/BufferedInputStream.java:244)
	at java.io.BufferedInputStream.read1(java.base@17.0.6/BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(java.base@17.0.6/BufferedInputStream.java:343)
	- locked <0x0000000733fed708> (a java.io.BufferedInputStream)
	at sun.net.www.http.HttpClient.parseHTTPHeader(java.base@17.0.6/HttpClient.java:824)
	at sun.net.www.http.HttpClient.parseHTTP(java.base@17.0.6/HttpClient.java:759)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(java.base@17.0.6/HttpURLConnection.java:1688)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@17.0.6/HttpURLConnection.java:1589)
	at org.eclipse.emf.ecore.resource.impl.URIHandlerImpl.createInputStream(URIHandlerImpl.java:207)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:358)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getPackageForURI(XMLHandler.java:2601)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getFactoryForPrefix(XMLHandler.java:2488)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectByType(XMLHandler.java:1365)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createTopObject(XMLHandler.java:1534)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1056)
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.processElement(XMIHandler.java:82)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1038)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:727)
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.startElement(XMIHandler.java:190)
	at org.eclipse.emf.compare.ide.internal.utils.ForwardingXMLHandler.startElement(ForwardingXMLHandler.java:383)
	at org.eclipse.emf.compare.ide.internal.utils.ForwardingXMLDefaultHandler.startElement(ForwardingXMLDefaultHandler.java:179)
	at org.eclipse.emf.compare.ide.internal.utils.NotifyingParserPool$NamespaceDeclarationNotifyingXMLDefaultHandler.startElement(NotifyingParserPool.java:202)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(java.xml@17.0.6/AbstractSAXParser.java:518)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(java.xml@17.0.6/XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(java.xml@17.0.6/XMLDocumentFragmentScannerImpl.java:2726)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(java.xml@17.0.6/XMLDocumentScannerImpl.java:605)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(java.xml@17.0.6/XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(java.xml@17.0.6/XMLDocumentFragmentScannerImpl.java:542)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(java.xml@17.0.6/XML11Configuration.java:889)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(java.xml@17.0.6/XML11Configuration.java:825)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(java.xml@17.0.6/XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(java.xml@17.0.6/AbstractSAXParser.java:1224)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(java.xml@17.0.6/SAXParserImpl.java:637)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(java.xml@17.0.6/SAXParserImpl.java:326)
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.emf.compare.ide.ui.internal.logical.resolver.SynchronizedResourceSet.loadResource(SynchronizedResourceSet.java:183)
	at org.eclipse.emf.compare.ide.ui.internal.logical.resolver.LocalResolveComputation.run(LocalResolveComputation.java:78)
	at org.eclipse.emf.compare.ide.ui.internal.logical.resolver.ResourceComputationScheduler$3.run(ResourceComputationScheduler.java:406)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.6/Executors.java:539)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.6/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.6/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)
```
Then after several minutes, it still appears to be reading from the network.

The other set of three traces show the same problem.

It's maybe unhelpful, but do you really need the Synchronization view of the Team Perspective?  I generally only use the Git perspective with the Staging view for viewing and for committing to my Git repositories...

Otherwise you will need to open an issue here because this appears to be purely an EMF compare issue and I cannot move this issue to that organization:

https://github.com/eclipse-emf-compare/emf-compare

**Comment by merks** [comment]
BTW, I suspect that some model is not installed in your IDE and EMF's resource implementation is allowing the handler to try to loading the namespace URI as a resource, which is the default behavior but can be disabled as seen here:

https://github.com/eclipse-emf/org.eclipse.emf/blob/5eae1280091bfa2fb5971dac7032e995ab9939e6/plugins/org.eclipse.emf.ecore.xmi/src/org/eclipse/emf/ecore/xmi/impl/XMLHandler.java#L514
