### ISSUE TITLE
Failure of ResourceInitialSelectionTest.testSingleSelectionAndOneInitialSelectionWithInitialPattern

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#1337]
Failed in [this build](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/7029540124/job/19127333573?pr=1301) of #1301 

```java
org.eclipse.ui.tests.dialogs.ResourceInitialSelectionTest.testSingleSelectionAndOneInitialSelectionWithInitialPattern -- Time elapsed: 0.092 s <<< ERROR!
org.eclipse.core.internal.resources.ResourceException: Problems encountered while deleting resources.
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:821)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:365)
	at org.eclipse.ui.tests.dialogs.ResourceInitialSelectionTest.doTearDown(ResourceInitialSelectionTest.java:386)
	at org.eclipse.ui.tests.harness.util.UITestCase.tearDown(UITestCase.java:214)
```

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-platform/eclipse.platform.ui/issues/294
