### ISSUE TITLE
Failure of LinkHelperTest.testLinkHelperEditorActivation

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#1338]
Failed in [this build](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/7029540124/job/19127333734?pr=1301) of #1301 

```java
org.eclipse.ui.tests.navigator.LinkHelperTest.testLinkHelperEditorActivation -- Time elapsed: 3.883 s <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.eclipse.ui.tests.navigator.LinkHelperTest.testLinkHelperEditorActivation(LinkHelperTest.java:97)
```

**Comment by fedejeanne** [comment]
No reported failures in 1+ years. Closing.

**Comment by trancexpress** [comment]
Seen again here: https://download.eclipse.org/eclipse/downloads/drops4/I20260331-0810/testresults/html/org.eclipse.ui.tests.navigator_ep440I-unit-linux-x86_64-java26_linux.gtk.x86_64_26.html

```
	expected: <1> but was: <2>

org.opentest4j.AssertionFailedError: expected: <1> but was: <2>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
at org.eclipse.ui.tests.navigator.LinkHelperTest.testLinkHelperEditorActivation(LinkHelperTest.java:106)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1612)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1612) 
```

Workspace log doesn't have test start and end, so its hard to tell what is relevant. Probably this covers both test methods in the test case:

https://download.eclipse.org/eclipse/downloads/drops4/I20260331-0810/testresults/ep440I-unit-linux-x86_64-java26_linux.gtk.x86_64_26/org.eclipse.ui.tests.navigator.NavigatorTestSuite.txt

```
EditorActivation start
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (1) activate: null (0)
before activate 1
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file1.txt) (1) activate: null (0)
EditorActivation 1 Done: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file1.txt) (1) activate: null (0)
before activate 2
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (1) activate: null (0)
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (2) activate: null (0)
EditorActivation 2 Done: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (2) activate: null (0)
SelectionChange start
activateEditor: findSel: null (0) activate: [L/p2/file1.txt] (1)
before set 2
activateEditor: findSel: null (0) activate: [L/p2/file2.txt] (2)
before set 3
activateEditor: findSel: null (0) activate: [L/p2/file1.txt] (1)
SelectionChange Done: findSel: null (0) activate: [L/p2/file1.txt] (1)
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file1.txt) (1) activate: null (0)
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (2) activate: null (0)
```

Running the test case locally (passes), the output is:

```
EditorActivation start
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (1) activate: null (0)
before activate 1
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file1.txt) (1) activate: null (0)
EditorActivation 1 Done: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file1.txt) (1) activate: null (0)
before activate 2
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (1) activate: null (0)
EditorActivation 2 Done: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (1) activate: null (0)
SelectionChange start
activateEditor: findSel: null (0) activate: [L/p2/file1.txt] (1)
before set 2
activateEditor: findSel: null (0) activate: [L/p2/file2.txt] (2)
before set 3
activateEditor: findSel: null (0) activate: [L/p2/file1.txt] (1)
SelectionChange Done: findSel: null (0) activate: [L/p2/file1.txt] (1)
```

So this for a fail:

```
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (1) activate: null (0)
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (2) activate: null (0)
```

And this for a pass:

```
findSelection: findSel: org.eclipse.ui.part.FileEditorInput(/p2/file2.txt) (1) activate: null (0)
```
