### ISSUE TITLE
IllegalStateException reported in the log on opening files or navigating in browser

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1398]
- Start Eclipse 4.30
- Open any svg file 
- Warning below reported into the log
```
java.lang.IllegalStateException: call to beginTask() missing
	at org.eclipse.jface.action.StatusLineManager$1.worked(StatusLineManager.java:221)
	at org.eclipse.ui.internal.browser.BrowserViewer$3.changed(BrowserViewer.java:421)
	at org.eclipse.swt.browser.WebKit.lambda$15(WebKit.java:2492)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5039)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4519)
```

Same in green:
- Start Eclipse 4.30 on Linux
- Open "Internal browser"
- Set any url and go there
- **Multiple** warnings like above reported in the log

This is a regression/side effect of https://github.com/eclipse-platform/eclipse.platform.ui/pull/1077.

**Comment by iloveeclipse** [comment]
@jukzi : could you please check?

**Comment by jukzi** [comment]
can not reproduce,
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/08f6a23b-b42a-409c-a838-7b6b9963ff30)
also i don't see an obvious error in the code

need more info

**Comment by iloveeclipse** [comment]
> need more info

You have to run on Linux, the browser support code is platform specific.

**Comment by jukzi** [comment]
i dont have linux, sorry. if it only on linux it may be an error in 
WebKit.webkit_notify_progress(long, long) `/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/browser/WebKit.java`

that the events are not in the expected order. but its hard to tell without debugging it, i see no obvious error there

**Comment by iloveeclipse** [comment]
I still see warnings, not always, only by back navigation, with slightly different stack:

```
java.lang.IllegalStateException: call to beginTask() missing
	at org.eclipse.jface.action.StatusLineManager$1.worked(StatusLineManager.java:221)
	at org.eclipse.ui.internal.browser.BrowserViewer$3.changed(BrowserViewer.java:427)
	at org.eclipse.swt.browser.WebKit.lambda$15(WebKit.java:2492)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
```

I've opened "Internal Web Browser", typed "heise.de", clicked through few links and then back. At some point in time errors started to appear...

**Comment by jukzi** [comment]
Please try ` progressWorked = 0;` after every  ` monitor.done();`

**Comment by iloveeclipse** [comment]
> Please try ` progressWorked = 0;` after every ` monitor.done();`

See https://github.com/eclipse-platform/eclipse.platform.ui/pull/1410, which is almost same as https://github.com/eclipse-platform/eclipse.platform.ui/pull/1401 except commit message.

This time I believe I've tested all possible navigation cases in the browser, it **seems** to mute the warnings. I believe something on Heise is timing dependent (async calls in javascript, self-reloading ads etc?) because I did navigation tests before on same page and there were no warnings reported... So I'm not even yet sure it is fully fixed...

**Comment by iloveeclipse** [comment]
**Seem** to work now with I20231213-1800 after https://github.com/eclipse-platform/eclipse.platform.ui/pull/1410. Closing.
