### ISSUE TITLE
Random failure of AbstractTreeViewerTest.testContains

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#1443]
Failed on build of #1404 

```java
element must be available on the viewer
java.lang.AssertionError: element must be available on the viewer
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.jface.tests.viewers.AbstractTreeViewerTest.testContains(AbstractTreeViewerTest.java:342)
...
```

**Comment by HeikoKlare** [comment]
Duplicate of: #1005

**Comment by HeikoKlare** [comment]
fwiw: failure was not in AbstractTreeViewerTest but in VirtualLazyTreeViewerTest
