### ISSUE TITLE
Random failure of TableViewerTest.testContains

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#1444]
Failed on a build of #1404 

```java
element must be available on the viewer
java.lang.AssertionError: element must be available on the viewer
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.jface.tests.viewers.TableViewerTest.testContains(TableViewerTest.java:203)
...
```

**Comment by HeikoKlare** [comment]
Duplicate of #1183.

**Comment by HeikoKlare** [comment]
fwiw: failing test is not in TableViewerTest but in VirtualTableViewerTest
