### ISSUE TITLE
ChooseWorkspaceDialog resolved path issues

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1513]
no reason to Log an exception when user enters illegal path:
```
java.nio.file.InvalidPathException: Illegal char <*> at index 39: C:\Users\jkubitz\platforM-2024-01-10\ws*
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.io.File.toPath(File.java:2401)
	at org.eclipse.ui.internal.ide.ChooseWorkspaceDialog.getUnexpectedPathHint(ChooseWorkspaceDialog.java:466)
```

and the resolved path is still wrong:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/652296b9-d156-4068-8715-12bffe6cbe64)

and still does not show the right capitalization:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/9f986c59-4451-4873-9228-4613c374e316)

**Comment by HeikoKlare** [comment]
This is related to the behavior described in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1492#issuecomment-1896111775 as it has the same reason.

The `InvalidPathException` thrown here needs to be handled:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/f0cb36209711d78732393efd852275f17e71a867/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/ChooseWorkspaceDialog.java#L466

**Comment by laeubi** [comment]
@jukzi what happens if you try to press OK here...?
@HeikoKlare I think invalid path should result in the launch button to be disabled as well.

**Comment by jukzi** [comment]
eclipse starts with error: ![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/987555f5-f264-455a-9528-3c7f760f487b)

**Comment by jukzi** [comment]
and it can not recover-- i am stuck in 
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/a66ef9a5-a5da-404f-ba1e-cc0abee5d852)
after another restart :-(

**Comment by jukzi** [comment]
```
!SESSION 2024-01-19 10:15:03.620 -----------------------------------------------
eclipse.buildId=4.31.0.I20240118-1800
java.version=21.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.eclipse.emf.ecore 2 0 2024-01-19 10:15:05.861
!MESSAGE Both 'org.eclipse.cbi.p2repo.p2.maven' and 'org.eclipse.m2e.model.edit' register a package for 'http://maven.apache.org/POM/4.0.0'

!ENTRY org.eclipse.osgi 4 0 2024-01-19 10:15:06.501
!MESSAGE Application error
!STACK 1
java.nio.file.InvalidPathException: Illegal char <*> at index 50: C:\Users\jkubitz\platform-2024-01-10\eclipse\hello*
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at java.base/java.io.File.toPath(File.java:2401)
	at org.eclipse.ui.internal.ide.ChooseWorkspaceDialog.getUnexpectedPathHint(ChooseWorkspaceDialog.java:466)
	at org.eclipse.ui.internal.ide.ChooseWorkspaceDialog.lambda$10(ChooseWorkspaceDialog.java:444)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:183)
	at org.eclipse.ui.internal.ide.ChooseWorkspaceDialog.createWorkspaceBrowseRow(ChooseWorkspaceDialog.java:458)
	at org.eclipse.ui.internal.ide.ChooseWorkspaceDialog.createDialogArea(ChooseWorkspaceDialog.java:195)
	at org.eclipse.jface.dialogs.TitleAreaDialog.createContents(TitleAreaDialog.java:166)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1092)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.eclipse.ui.internal.ide.ChooseWorkspaceDialog.prompt(ChooseWorkspaceDialog.java:138)
	at org.eclipse.ui.internal.ide.application.IDEApplication.showChooseWorkspaceDialog(IDEApplication.java:440)
	at org.eclipse.ui.internal.ide.application.IDEApplication.promptForWorkspace(IDEApplication.java:371)
	at org.eclipse.ui.internal.ide.application.IDEApplication.checkInstanceLocation(IDEApplication.java:285)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:142)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

```

**Comment by HeikoKlare** [comment]
You have to manually correct the preferences in configuration/.settings/org.eclipse.ui.ide.prefs until the bug is fixed
See https://github.com/eclipse-platform/eclipse.platform.ui/issues/1492#issuecomment-1896111775

**Comment by jukzi** [comment]
thanks

**Comment by merks** [comment]
I guess -data would still work too.
