### ISSUE TITLE
Random failing PlatformUITest#testCreateAndRunWorkbench()

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.ui#1517]
The test case `org.eclipse.ui.tests.rcp.PlatformUITest#testCreateAndRunWorkbench()` has been randomly failing in recent builds. One recent failure happened in this build: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1514/checks?check_run_id=20614845943

```
Async from qualified thread did not run during startup.  See RCPTestWorkbenchAdvisor.preStartup() expected:<true> but was:<false>
java.lang.AssertionError: Async from qualified thread did not run during startup.  See RCPTestWorkbenchAdvisor.preStartup() expected:<true> but was:<false>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.eclipse.ui.tests.rcp.PlatformUITest.testCreateAndRunWorkbench(PlatformUITest.java:72)
```

**Comment by vogella** [comment]
## Why the Phaser approach was failing

The initial fix attempt used `java.util.concurrent.Phaser` to synchronize the async/sync operations, but this approach had fundamental issues:

### Problem 1: Timing vs. Execution
The Phaser was counting arrivals when operations were **scheduled**, not when they **executed**:
```java
display.asyncExec(() -> {
    asyncWithDisplayAccess = !isSTARTED();
});
// Phaser counted down here - but the runnable hasn't executed yet!
asyncPhaser.arriveAndDeregister();
```

This meant `postStartup()` could mark `started=true` before the runnables actually ran on the UI thread, defeating the entire purpose of the synchronization.

### Problem 2: Event Processing Issues
The inline event processing using `Display.getCurrent()` and `readAndDispatch()` wasn't reliable during the startup phase, leading to timeouts.

### Solution: CountDownLatch
The fix uses `CountDownLatch` that counts down **inside** the runnables after they execute:
```java
display.asyncExec(() -> {
    asyncWithDisplayAccess = !isSTARTED();
    displayAccessLatch.countDown();  // Count down AFTER execution
});
```

This ensures `postStartup()` waits for actual execution, not just scheduling. The approach is:
1. Initialize latch with count=2 (for async and sync with DisplayAccess)
2. Each runnable counts down after setting its variable
3. `postStartup()` waits for latch to reach zero
4. Then process remaining events
5. Finally mark started=true

**Test Results:** The test now passes consistently across 5 consecutive runs locally.

Fix pushed to PR #3429.

**Comment by HeikoKlare** [comment]
Failed again in recent build: https://github.com/eclipse-platform/eclipse.platform.ui/pull/3475/checks?check_run_id=57536221357

@vogella fyi

```
Multiple Failures (1 failure)
 org.opentest4j.AssertionFailedError: Async from qualified thread did not run during startup.  See RCPTestWorkbenchAdvisor.preStartup() ==> expected: <true> but was: <false>
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: Async from qualified thread did not run during startup.  See RCPTestWorkbenchAdvisor.preStartup() ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:80)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:44)
	at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:38)
	at org.junit.jupiter.api.Assertions.assertAll(Assertions.java:2944)
	at org.eclipse.ui.tests.rcp.PlatformUITest.testCreateAndRunWorkbench(PlatformUITest.java:63)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	Suppressed: org.opentest4j.AssertionFailedError: Async from qualified thread did not run during startup.  See RCPTestWorkbenchAdvisor.preStartup() ==> expected: <true> but was: <false>
		at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
		at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
		at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
		at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
		at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:214)
		at org.eclipse.ui.tests.rcp.PlatformUITest.lambda$3(PlatformUITest.java:71)
		at org.junit.jupiter.api.AssertAll.lambda$assertAll$0(AssertAll.java:68)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
		at org.junit.jupiter.api.AssertAll.assertAll(AssertAll.java:77)
		... 7 more
WARNING: Timeout waiting for async/sync operations with DisplayAccess
```

**Comment by vogella** [comment]
Maybe timeout to short? WARNING: Timeout waiting for async/sync operations with DisplayAccess
