### ISSUE TITLE
org.eclipse.ui.tests DNF

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.ui#154]
https://download.eclipse.org/eclipse/downloads/drops4/I20220618-0340/testresults/ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11/org.eclipse.ui.tests.UiTestSuite.txt 

```
!ENTRY org.eclipse.ui.tests 4 0 2022-06-18 11:16:17.799
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ui.tests [309]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.ui.tests [osgi.identity; osgi.identity="org.eclipse.ui.tests"; type="osgi.bundle"; version:Version="3.15.700.v20220610-1735"; singleton:="true"] because it is exposed to package 'org.osgi.service.component' from resources org.eclipse.osgi.services [osgi.identity; type="osgi.bundle"; version:Version="3.10.200.v20210723-0643"; osgi.identity="org.eclipse.osgi.services"] and org.osgi.service.component [osgi.identity; type="osgi.bundle"; version:Version="1.5.0.202109301733"; osgi.identity="org.osgi.service.component"] via two dependency chains.

Chain 1:
  org.eclipse.ui.tests [osgi.identity; osgi.identity="org.eclipse.ui.tests"; type="osgi.bundle"; version:Version="3.15.700.v20220610-1735"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.osgi.services)(bundle-version>=3.3.100))
     |
    provide: osgi.wiring.bundle: org.eclipse.osgi.services
  org.eclipse.osgi.services [osgi.identity; type="osgi.bundle"; version:Version="3.10.200.v20210723-0643"; osgi.identity="org.eclipse.osgi.services"]

Chain 2:
  org.eclipse.ui.tests [osgi.identity; osgi.identity="org.eclipse.ui.tests"; type="osgi.bundle"; version:Version="3.15.700.v20220610-1735"; singleton:="true"]
    require: (&(osgi.extender=osgi.component)(version>=1.2)(!(version>=2.0)))
     |
    provide: osgi.extender; osgi.extender="osgi.component"; version:Version="1.5.0"; uses:="org.osgi.service.component"
  org.apache.felix.scr [osgi.identity; type="osgi.bundle"; version:Version="2.2.2"; osgi.identity="org.apache.felix.scr"]
    import: (&(osgi.wiring.package=org.osgi.service.component)(&(version>=1.5.0)(!(version>=1.6.0))))
     |
    export: osgi.wiring.package: org.osgi.service.component
  org.osgi.service.component [osgi.identity; type="osgi.bundle"; version:Version="1.5.0.202109301733"; osgi.identity="org.osgi.service.component"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

```

**Comment by akurtakov** [comment]
@HannesWell any idea what's going on?

**Comment by HannesWell** [comment]
I saw that exact error with PR https://github.com/eclipse-platform/eclipse.platform.ui/pull/42 before I adjusted the Manifest.MF.
Switching from Require-Bundle to Import-Package fixed it.

So the problem should vanish with the next I-build.
Unfortunately the last I-build happened after I submitted the prerequ-TP update and before I could complete the mentioned PR.

**Comment by akurtakov** [comment]
OK. Triggered new I-build.

**Comment by HannesWell** [comment]
Looks like the test-failures are gone for the latest I-build:
https://download.eclipse.org/eclipse/downloads/drops4/I20220618-1000/
