### ISSUE TITLE
Exceptions when refreshing virtual tree after updating model

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform.ui#170]
To reproduce run the following snippet and click on the "change tree" button:

```
public class TestLazyTreeViewer {

	public static void main(String[] args) {
		Display display = new Display();
		Shell shell = new Shell(display);
		shell.setText("test tree viewer");
		shell.setSize(600, 400);
		shell.setLayout(new FillLayout());
		Composite composite = new Composite(shell, SWT.NONE);
		composite.setLayout(new GridLayout(1, false));

		String root1 = "tree1";
		Map<String, List<String>> tree1 = createTree(root1, 15, 2, 2);
		Map<String, List<String>> tree2 = createTree(root1, 15, 2, 1);
		Map[] trees = { tree1, tree2 };

		AtomicInteger treeIndex = new AtomicInteger(0);

		TreeViewer viewer = new CheckboxTreeViewer(composite, SWT.VIRTUAL);
		GridData gridData = new GridData();
		gridData.minimumHeight = 300;
		gridData.minimumWidth = 500;
		gridData.grabExcessVerticalSpace = true;
		gridData.grabExcessHorizontalSpace = true;
		viewer.getTree().setLayoutData(gridData);
		viewer.setContentProvider(new ILazyTreeContentProvider() {
			@Override
			public void updateElement(Object parent, int index) {
				if (parent == null) {
					throw new NullPointerException("parent cannot be null");
				}
				Map<String, List<String>> tree = trees[treeIndex.get() % 2];
				List<String> children = tree.get(parent);
				if (children != null) {
					if (index < children.size()) {
						String child = children.get(index);
						viewer.replace(parent, index, child);
						List<String> grandchildren = tree.get(child);
						if (grandchildren != null) {
							viewer.setChildCount(child, grandchildren.size());
						}
					}
				} else {
					viewer.setChildCount(parent, 0);
				}
			}

			@Override
			public void updateChildCount(Object element, int currentChildCount) {
				Map<String, List<String>> tree = trees[treeIndex.get() % 2];
				List<String> children = tree.get(element);
				if (children != null) {
					if (children.size() != currentChildCount) {
						viewer.setChildCount(element, children.size());
					}
				} else {
					viewer.setChildCount(element, 0);
				}
			}

			@Override
			public Object getParent(Object element) {
				return null;
			}
		});

		TreeViewerColumn viewerColumn = new TreeViewerColumn(viewer, SWT.NONE);
		viewerColumn.getColumn().setWidth(300);
		viewerColumn.getColumn().setText("column 1");
		viewerColumn.setLabelProvider(new ColumnLabelProvider());

		viewer.getTree().setHeaderVisible(true);
		viewer.getTree().setLinesVisible(true);
		viewer.setAutoExpandLevel(3);

		viewer.setInput(root1);

		Button button = new Button(composite, SWT.BORDER);
		button.setText("change tree");
		button.addSelectionListener(new SelectionAdapter() {
			@Override
			public void widgetSelected(SelectionEvent e) {
				treeIndex.incrementAndGet();
				viewer.refresh();
			}
		});
		gridData = new GridData();
		gridData.minimumWidth = 500;
		gridData.grabExcessVerticalSpace = false;
		gridData.grabExcessHorizontalSpace = true;
		button.setLayoutData(gridData);

		shell.open();
		shell.pack();

		while (!shell.isDisposed()) {
			if (!display.readAndDispatch())
				display.sleep();
		}
		display.dispose();
	}

	private static Map<String, List<String>> createTree(String root, int c1, int c2, int c3) {
		Map<String, List<String>> tree = new HashMap<>();
		String[] children = createStrings(root + ":child", c1);
		tree.put(root, Arrays.asList(children));
		for (String child : children) {
			String[] grandchildren = createStrings(root + ":grandchild", c2);
			tree.put(child, Arrays.asList(grandchildren));
			for (String grandchild : grandchildren) {
				String[] grandgrandchildren = createStrings(root + ":grandgrandchildren", c3);
				tree.put(grandchild, Arrays.asList(grandgrandchildren));
			}
		}
		return tree;
	}

	private static String[] createStrings(String prefix, int n) {
		String[] strings = new String[n];
		for (int i = 0; i < n; ++i) {
			strings[i] = prefix + " " + i + "/" + n;
		}
		return strings;
	}
}
```

There is a widget disposed exception:

```
Exception in thread "main" org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:480)
	at org.eclipse.swt.widgets.Widget.getData(Widget.java:591)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.gatherState(CheckboxTreeViewer.java:188)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.gatherState(CheckboxTreeViewer.java:199)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.gatherState(CheckboxTreeViewer.java:199)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.preservingSelection(CheckboxTreeViewer.java:405)
	at org.eclipse.jface.viewers.TreeViewer.setChildCount(TreeViewer.java:386)
	at test.jface.TestLazyTreeViewer$1.updateElement(TestLazyTreeViewer.java:64)
	at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:998)
	at org.eclipse.jface.viewers.TreeViewer.lambda$1(TreeViewer.java:258)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Tree.checkData(Tree.java:373)
	at org.eclipse.swt.widgets.TreeItem.getItems(TreeItem.java:821)
	at org.eclipse.jface.viewers.TreeViewer.getChildren(TreeViewer.java:160)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalFindItem(AbstractTreeViewer.java:1878)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalFindItem(AbstractTreeViewer.java:1880)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doFindItem(AbstractTreeViewer.java:924)
	at org.eclipse.jface.viewers.StructuredViewer.findItems(StructuredViewer.java:761)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalFindItems(AbstractTreeViewer.java:191)
	at org.eclipse.jface.viewers.TreeViewer.replace(TreeViewer.java:435)
	at test.jface.TestLazyTreeViewer$1.updateElement(TestLazyTreeViewer.java:61)
	at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:998)
	at org.eclipse.jface.viewers.TreeViewer.lambda$1(TreeViewer.java:258)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Tree.checkData(Tree.java:373)
	at org.eclipse.swt.widgets.TreeItem.getChecked(TreeItem.java:529)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.gatherState(CheckboxTreeViewer.java:191)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.gatherState(CheckboxTreeViewer.java:199)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.gatherState(CheckboxTreeViewer.java:199)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.preservingSelection(CheckboxTreeViewer.java:405)
	at org.eclipse.jface.viewers.TreeViewer.setChildCount(TreeViewer.java:386)
	at test.jface.TestLazyTreeViewer$1.updateElement(TestLazyTreeViewer.java:64)
	at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:998)
	at org.eclipse.jface.viewers.TreeViewer.lambda$1(TreeViewer.java:258)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Tree.checkData(Tree.java:373)
	at org.eclipse.swt.widgets.TreeItem.getChecked(TreeItem.java:529)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.gatherState(CheckboxTreeViewer.java:191)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.gatherState(CheckboxTreeViewer.java:199)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.preservingSelection(CheckboxTreeViewer.java:405)
	at org.eclipse.jface.viewers.TreeViewer.setChildCount(TreeViewer.java:386)
	at test.jface.TestLazyTreeViewer$1.updateElement(TestLazyTreeViewer.java:64)
	at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:998)
	at org.eclipse.jface.viewers.TreeViewer.lambda$1(TreeViewer.java:258)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Tree.checkData(Tree.java:373)
	at org.eclipse.swt.widgets.TreeItem.getItems(TreeItem.java:821)
	at org.eclipse.jface.viewers.TreeViewer.getChildren(TreeViewer.java:160)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.applyState(CheckboxTreeViewer.java:141)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.applyState(CheckboxTreeViewer.java:151)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.preservingSelection(CheckboxTreeViewer.java:409)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1459)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:526)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1418)
	at test.jface.TestLazyTreeViewer$2.widgetSelected(TestLazyTreeViewer.java:108)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5794)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5025)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4477)
	at test.jface.TestLazyTreeViewer.main(TestLazyTreeViewer.java:121)
```

We have something similar in our product (but not quite the same, I've not found the essential difference) that produces NPEs with current platform UI and SWT. In particular ```org.eclipse.jface.viewers.ILazyTreeContentProvider.updateElement(Object, int)``` is called with the ```parent``` argument having ```null``` value.

Prior to this SWT commit, the snippet above crashes (might need to expand and select a nested item to run into the GTK+ crash):  https://git.eclipse.org/c/platform/eclipse.platform.swt.git/commit/?id=616d50c48b448df3043e67770a72d3e6c5467004 (same if ```Tree.fixAccessibility()``` is changed to return ```false```)

We see the NPEs, instead of crashes, starting with that commit.

I don't have a Windows machine to test how the snippet behaves on WIndows. I'm not knowledgeable on virtual trees/tables, but from my POV the snippet doesn't do unexpected operations. Documentation from ```org.eclipse.jface.viewers.ILazyTreeContentProvider``` seems to be followed by the code...

**Comment by trancexpress** [comment]
@iloveeclipse is there anyone left in platform UI that can give us a hint as to how a virtual tree is meant to be implemented in JFace? The above seems to me basic use of the API yet basic operations fail. Trying to workaround those problems results in yet more problems.

**Comment by trancexpress** [comment]
If I define a wrapper class for the strings in the reproducer snippet, I don't see a problem anymore. With the older SWT there are still crashes in GTK+. But I don't see exceptions.

There must be some hashing problem here. I.e. if elements replaced via ```ILazyTreeContentProvider.updateElement()``` are the same as old elements, some hash map gets confused?

**Comment by laeubi** [comment]
@trancexpress what specifically do you want to know, I'm using virtual tree on Windows/Linux without a problem for a while, the only thing form your snippet I noticed it that you are missing the `viewer.setUseHashlookup(true);` what is recommended for "lazy" viewers.

**Comment by trancexpress** [comment]
> @trancexpress what specifically do you want to know, I'm using virtual tree on Windows/Linux without a problem for a while, the only thing form your snippet I noticed it that you are missing the `viewer.setUseHashlookup(true);` what is recommended for "lazy" viewers.

Thanks, I'll try this. But otherwise the snippet is standard usage for a virtual tree viewer? Its odd to me that I would be getting exceptions left and right, I assumed I'm doing something wrong in the snippet.

**Comment by laeubi** [comment]
I just can remember that I have had problems with CheckboxTreeViewer, I don't think it works well with virtual trees, if I just replace `CheckboxTreeViewer` with a plain `TreeViewer` everything works fine.

**Comment by wimjongman** [comment]
You can't just return null for the parent and get away with it. It is in the Javadoc. The tree should be populated with some kind of *Resource* model. Inside the model, you can keep track of the parent and the actual tree object.

Please see all the JFace snippets here:

https://wiki.eclipse.org/JFaceSnippets#Snippet047_-_Virtual_Lazy_Tree_Viewer

```
getParent:
"Returns the parent for the given element, or null indicating that the parent can't be 
computed. In this case the tree-structured viewer can't expand a given node correctly if requested."
```
