### ISSUE TITLE
MultiVariablePageTest fails on all platforms

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1736]
for example
https://download.eclipse.org/eclipse/downloads/drops4/I20240306-1800/testresults/html/org.eclipse.ui.tests_ep432I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

```
junit.framework.AssertionFailedError: org.eclipse.ui.textEditorScope expected:<true> but was:<false>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:174)
at junit.framework.TestCase.assertEquals(TestCase.java:317)
at org.eclipse.ui.tests.multipageeditor.MultiVariablePageTest.checkActiveContext(MultiVariablePageTest.java:242)
at org.eclipse.ui.tests.multipageeditor.MultiVariablePageTest.testContextActivation(MultiVariablePageTest.java:210)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)

```

**Comment by iloveeclipse** [comment]
This is a regression from https://github.com/eclipse-platform/eclipse.platform.swt/pull/1044.
Reverting SWT change fixes the test.

**Comment by iloveeclipse** [comment]
Fixed in https://download.eclipse.org/eclipse/downloads/drops4/I20240307-1800/testResults.php
