### ISSUE TITLE
Random failing MMenuItemTest.testElementHierarchyInContext_HandledItem

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1737]
https://download.eclipse.org/eclipse/downloads/drops4/I20240306-1800/testresults/html/org.eclipse.e4.ui.tests_ep432I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.eclipse.e4.ui.tests.workbench.MMenuItemTest.testElementHierarchyInContext_HandledItem(MMenuItemTest.java:848)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.e4.ui.tests.rules.WorkbenchContextRule$1.evaluate(WorkbenchContextRule.java:62)
```

**Comment by fedejeanne** [comment]
It failed again in #3548

**Comment by fedejeanne** [comment]
Failed again in https://github.com/eclipse-platform/eclipse.platform.ui/pull/4121
