### ISSUE TITLE
I20240312-1800 failed many junit related to "width"

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1751]
https://download.eclipse.org/eclipse/downloads/drops4/I20240312-1800/testResults.php

for example  IOConsoleFixedWidthTests or
```
java.lang.NullPointerException: Cannot load from int array because "this.fIndentation" is null
at org.eclipse.jface.text.source.LineNumberRulerColumn.getWidth(LineNumberRulerColumn.java:477)
at org.eclipse.jface.text.source.LineNumberChangeRulerColumn.getWidth(LineNumberChangeRulerColumn.java:262)
at org.eclipse.ui.internal.texteditor.LineNumberColumn.getWidth(LineNumberColumn.java:136)
at org.eclipse.jface.text.source.CompositeRuler.getWidth(CompositeRuler.java:673)
...
at org.eclipse.ant.tests.ui.editor.AntEditorTests.testAugmentMissingId(AntEditorTests.java:304)
```

There where  4 changes to "width" yesterday. (for example https://github.com/eclipse-platform/eclipse.platform.ui/pull/1716) But i could not reproduce the fails locally.

@shubhamWaghmare-sap @BeckerWdf can you investigate?

**Comment by jukzi** [comment]
don't know if its related, but logs contain a `NoSuchMethodError `that i don't understand:

```
java.lang.NoSuchMethodError: 'org.eclipse.swt.internal.SWTEventListener org.eclipse.swt.widgets.TypedListener.getEventListener()'
	at org.eclipse.ui.internal.console.ansi.participants.AnsiConsolePageParticipant.getDocument(AnsiConsolePageParticipant.java:71)

```
