### ISSUE TITLE
"Failed to retrieve Windows Defender status." at startup of Eclipse

### ISSUE THREAD

**Issue by ErikBergfurInfor** [eclipse-platform/eclipse.platform.ui#1758]
The Windows Defender status check assumes the result strings are case insensitive.

On line 319, eclipse checks for "Passive mode"
https://github.com/eclipse-platform/eclipse.platform.ui/blame/03b03d8feefa6270e575dd61eb5c25c839c36eec/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/WindowsDefenderConfigurator.java#L319

The error I get on my windows 11 workstation gives us "Passive Mode"
```
org.eclipse.core.runtime.CoreException: Failed to retrieve Windows Defender status.
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.isWindowsDefenderActive(WindowsDefenderConfigurator.java:324)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.runExclusionCheck(WindowsDefenderConfigurator.java:154)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.lambda$0(WindowsDefenderConfigurator.java:101)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: Process terminated with unexpected result:
Passive Mode
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.isWindowsDefenderActive(WindowsDefenderConfigurator.java:321)
	... 4 more
```

**Comment by BeckerWdf** [comment]
@HannesWell : Can you pls. have a look at this?

**Comment by HannesWell** [comment]
Thanks for the report. Will take of it. Shouldn't be too difficult.

**Comment by HannesWell** [comment]
@ErikBergfurInfor thanks again for your bug-report.
The issue should be fixed now. Please try out tomorrows `Integration build` from https://download.eclipse.org/eclipse/downloads/ to verify it is really fixed.

**Comment by piradix** [comment]
I get the same problem with "eclipse-SDK-4.31-win32-x86_64" :-)
But It don't more exists with "eclipse-SDK-I20240329-1800-win32-x86_64" ;-)

**Comment by bernd-wechner** [comment]
Interestingly it's May and I just got this with the Eclipse 2024‑03 R [Eclipse IDE for Enterprise Java and Web Developers](https://www.eclipse.org/downloads/packages/release/2024-03/r/eclipse-ide-enterprise-java-and-web-developers). 

Just wondering if it's safe to ignore. I'll do that for now and if I run into any issues try the integration build mentioned above.
