### ISSUE TITLE
ClassCastException when opening target definition file in compare view

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform.ui#1798]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

- Install Git integration
- Check out target file (under version control)
- Modify target file
- Open target file via the compare view

I tried:

Double-clicking on the target file in the staging view

I expected:

![Capture1](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/728bdca0-aeab-464c-b0ce-02b5f9040e80)

But got:

![Capture2](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/c34bca40-95fd-4f05-8b0e-a75d12c4ec5b)

## Here is some relevant log output

From `<workspace>/.metadata/.log`
```
java.lang.ClassCastException: class org.eclipse.jface.text.source.SourceViewer cannot be cast to class org.eclipse.jface.text.source.projection.ProjectionViewer (org.eclipse.jface.text.source.SourceViewer and org.eclipse.jface.text.source.projection.ProjectionViewer are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @35d630f)
	at org.eclipse.pde.internal.genericeditor.target.extension.reconciler.folding.TargetPlatformFoldingReconciler.install(TargetPlatformFoldingReconciler.java:33)
	at org.eclipse.ui.internal.genericeditor.CompositeReconciler.install(CompositeReconciler.java:56)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:504)
	at org.eclipse.ui.internal.genericeditor.compare.GenericEditorMergeViewer.configureTextViewer(GenericEditorMergeViewer.java:71)
	at org.eclipse.ui.internal.genericeditor.compare.GenericEditorMergeViewer$1.inputDocumentChanged(GenericEditorMergeViewer.java:53)
	at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2844)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2885)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:682)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:622)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer$ContributorInfo.updateViewerDocument(TextMergeViewer.java:809)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer$ContributorInfo.internalSetDocument(TextMergeViewer.java:764)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer$ContributorInfo.setDocument(TextMergeViewer.java:681)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.updateContent(TextMergeViewer.java:3052)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.internalRefresh(ContentMergeViewer.java:796)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.inputChanged(ContentMergeViewer.java:704)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:269)
	at org.eclipse.compare.internal.CompareContentViewerSwitchingPane.setInput(CompareContentViewerSwitchingPane.java:202)
	at org.eclipse.compare.CompareEditorInput.internalSetContentPaneInput(CompareEditorInput.java:806)
	at org.eclipse.compare.CompareEditorInput.lambda$8(CompareEditorInput.java:747)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.compare.CompareEditorInput.feed1(CompareEditorInput.java:742)
	at org.eclipse.compare.CompareEditorInput.feedInput(CompareEditorInput.java:720)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:543)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:448)
	at org.eclipse.compare.internal.CompareEditor$1.lambda$0(CompareEditor.java:366)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:166)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:679)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:616)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1492)

```

## Tested under this environment:
* OS & version: Windows 10
Eclipse SDK 4.32M1

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by ptziegler** [comment]
The [TargetPlatformFoldingReconciler](https://github.com/eclipse-pde/eclipse.pde/blob/master/ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/folding/TargetPlatformFoldingReconciler.java) expects a ProjectionViewer, but now gets a plain SourceViewer. Given that this class hasn't had meaningful changes since 7 years, I assume that the Eclipse is suddenly passing a different type.

**Comment by iloveeclipse** [comment]
Could be side effect of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1747
I will take a look.

**Comment by iloveeclipse** [comment]
> The [TargetPlatformFoldingReconciler](https://github.com/eclipse-pde/eclipse.pde/blob/master/ui/org.eclipse.pde.genericeditor.extension/src/org/eclipse/pde/internal/genericeditor/target/extension/reconciler/folding/TargetPlatformFoldingReconciler.java) expects a ProjectionViewer, but now gets a plain SourceViewer.

This is a bug in PDE from original commit db7f2238702ecee2b82ad829bfb6e1078bcefc6e.
Adding a check results in this (note also syntax highlighting added, but that only for editable files as of now, I hope add read-only (git) support later):
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/b5b37dbc-e5ca-47a5-b4ab-d4be7e9d1ca4)

I will push PDE fix.

**Comment by ptziegler** [comment]
Awesome! Thank you for looking into this problem.

**Comment by iloveeclipse** [comment]
With https://github.com/eclipse-pde/eclipse.pde/issues/1222 compare editor shows syntax highlighting also for target file diffs on git versions.

**Comment by ptziegler** [comment]
I've updated to the latest nightly build and the problem is also solved on my side. Thanks again!
