### ISSUE TITLE
NPE in WhitespaceCharacterPainter.<init>

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1804]
In case there are more mergeViewers configured, switching to the non-default one and toggling "Show Whitespace Characters" button produces the error below (3 times).
I assume this happens because the action is created with a list of viewers even if the viewers are not fully initialized yet.
So first one (initially visible) always works, all invisible show the error.
```
!ENTRY org.eclipse.ui 4 0 2024-04-09 17:50:50.792
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:180)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:147)
	at org.eclipse.jface.text.WhitespaceCharacterPainter.<init>(WhitespaceCharacterPainter.java:97)
	at org.eclipse.jface.text.WhitespaceCharacterPainter.<init>(WhitespaceCharacterPainter.java:125)
	at org.eclipse.compare.internal.ShowWhitespaceAction.showWhitespace(ShowWhitespaceAction.java:134)
	at org.eclipse.compare.internal.ShowWhitespaceAction.toggleState(ShowWhitespaceAction.java:109)
	at org.eclipse.compare.internal.TextEditorPropertyAction.run(TextEditorPropertyAction.java:74)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.ui.actions.RetargetAction.runWithEvent(RetargetAction.java:225)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:223)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:581)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:454)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1617)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
```

I will provide a simple workaround (not a real fix), but that should be enough for most cases.

**Comment by iloveeclipse** [comment]
> I assume this happens because the action is created with a list of viewers even if the viewers are not fully initialized yet.
> So first one (initially visible) always works, all invisible show the error.

Actually it looks like the opposite is the case: the **previously used** viewer is still connected to the ShowWhitespaceAction while a new one is created. There seem to be a memory leak, I see 18 ShowWhitespaceAction instances...
