### ISSUE TITLE
Random failing SmartImportTests.testConfigurationFullBuildAfterImportedProjects 

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.ui#1827]
Random failing `SmartImportTests.testConfigurationFullBuildAfterImportedProjects`, e.g., in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1823/checks?check_run_id=23971305789

```
Expected 1 full-build trigger expected:<1> but was:<0>
java.lang.AssertionError: Expected 1 full-build trigger expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.eclipse.ui.tests.datatransfer.ImportTestUtils$TestBuilder.assertFullBuildWasDone(ImportTestUtils.java:96)
	at org.eclipse.ui.tests.datatransfer.SmartImportTests.testConfigurationFullBuildAfterImportedProjects(SmartImportTests.java:326)
```

**Comment by HeikoKlare** [comment]
@fedejeanne maybe you can have a look since you recently worked on `SmartImportTests` (#1810)?

**Comment by fedejeanne** [comment]
Failed on [this check](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/8785263563/job/24105356246#step:7:20597) of #1841 (the PR is not committed yet so the names of the methods may change in the future). The important thing here is that the test that explicitly triggers a **full** build ends up failing because there were 0 full builds and 1 auto-build.

```java
java.lang.AssertionError: [Auto-build triggers expected:<0> but was:<1>] expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.eclipse.ui.tests.datatransfer.ImportTestUtils$TestBuilder.assertAll(ImportTestUtils.java:123)
	at org.eclipse.ui.tests.datatransfer.ImportTestUtils$TestBuilder.assertBuildsWereDone(ImportTestUtils.java:103)
	at org.eclipse.ui.tests.datatransfer.ImportTestUtils$TestBuilder.assertFullBuildWasDone(ImportTestUtils.java:95)
	at org.eclipse.ui.tests.datatransfer.ImportExistingProjectsWizardTest.test21FullBuildAfterImportedProjects(ImportExistingProjectsWizardTest.java:1055)
```

**Comment by HeikoKlare** [comment]
Why do you conclude that there were 0 full builds? The full-builds assertion does not fail, so there should habe been one full build as expected by the test, shouldn't it?

So there is only the additional auto build. And I do not see a reason for the assertion of not having an auto-build being valid since auto building is enabled by default and I cannot find a place in `SmartImportTests` where auto building is disabled. There is a utility to disable auto building in `ImportTestUtils`, but that does not seem to be used.

**Comment by mickaelistria** [comment]
I don't recall the details of this test, but I don't think a full-build should be expected, and what build is triggered doesn't really matter when it comes to testing the import. I imagine the import tries to ensure that the proper project get (re)configured and built after import, ie the newly imported projects and the ones that depend on it.
But this doesn't have to be a full build.
So if you think the test is better (ie still tests the interesting things) without checking for a full build, feel free to get rid of the full build check.

**Comment by fedejeanne** [comment]
> Why do you conclude that there were 0 full builds?

@HeikoKlare you're right, there was 1 full build and 1 auto-build.

> So if you think the test is better (ie still tests the interesting things) without checking for a full build, feel free to get rid of the full build check.

@mickaelistria by looking at 81b5d75c07a1d22f1471227984a50a755673203c I see it doesn't even matter if an auto-build was triggered, what it matters is that a full build is triggered because that would mean that both imported projects are **definitely** being built. This is the interesting functionality that is being tested.

 I changed `assertFullBuildWasDone` to only care about (the builder being part of the process and) the full builds and I removed `assertAutoBuildWasDone` and `assertNoBuildWasDone` because they were not being used.

I made the changes in f6070c3454cddab8d09c9f7c1412e80b75a0f191

**Comment by fedejeanne** [comment]
Failed again in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1853, this time because the builder wasn't even part of the process (the info was added in #1841 )

```java
This builder wasn't part of the building process expected:<1> but was:<0>
java.lang.AssertionError: This builder wasn't part of the building process expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.eclipse.ui.tests.datatransfer.ImportTestUtils$TestBuilder.assertFullBuildWasDone(ImportTestUtils.java:91)
	at org.eclipse.ui.tests.datatransfer.SmartImportTests.testConfigurationFullBuildAfterImportedProjects(SmartImportTests.java:326)
...
```
