### ISSUE TITLE
[Tests] ProgressViewTests.testItemOrder is flaky 

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.ui#195]
The testcase org.eclipse.ui.tests.progress.ProgressViewTests.testItemOrder keeps failing randomly in the I-build

This issue is created to track the [bug 553430](https://bugs.eclipse.org/bugs/show_bug.cgi?id=553430)

**Comment by ktatavarthi** [comment]
This test failed in the I-Build [I20220706-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220706-1800/testresults/html/org.eclipse.ui.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html) on macM1 with the below error

```
Wrong job order: arrays first differed at element [0]; expected:<1. User Job(1193)> but was:<4. Usual job 2(1196)>

Wrong job order: arrays first differed at element [0]; expected:<1. User Job(1193)> but was:<4. Usual job 2(1196)>
at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)
at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
at org.junit.Assert.internalArrayEquals(Assert.java:534)
at org.junit.Assert.assertArrayEquals(Assert.java:285)
at org.eclipse.ui.tests.progress.ProgressViewTests.testItemOrder(ProgressViewTests.java:193) 
```

**Comment by ktatavarthi** [comment]
This test failed in the I-Build [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.ui.tests_ep426I-unit-macM1-java17_macosx.cocoa.aarch64_17.html) on macM1 with the below error

```
Wrong job order: arrays first differed at element [0]; expected:<1. User Job(1193)> but was:<4. Usual job 2(1196)>

Wrong job order: arrays first differed at element [0]; expected:<1. User Job(1193)> but was:<4. Usual job 2(1196)>
at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)
at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
at org.junit.Assert.internalArrayEquals(Assert.java:534)
at org.junit.Assert.assertArrayEquals(Assert.java:285)
at org.eclipse.ui.tests.progress.ProgressViewTests.testItemOrder(ProgressViewTests.java:193) 
```
