### ISSUE TITLE
plenty test failure in ColumnViewerSelectionColorListener.handleEvent

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1955]
Hundrets of fails in I Build like

```
Argument cannot be null
java.lang.IllegalArgumentException: Argument cannot be null
at org.eclipse.swt.SWT.error(SWT.java:4903)
at org.eclipse.swt.SWT.error(SWT.java:4837)
at org.eclipse.swt.SWT.error(SWT.java:4808)
at org.eclipse.swt.graphics.GC.setBackground(GC.java:3329)
at org.eclipse.jface.viewers.internal.ColumnViewerSelectionColorListener.handleEvent(ColumnViewerSelectionColorListener.java:69)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4660)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1622)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1645)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1630)
at org.eclipse.swt.widgets.Table.drawInteriorWithFrame_inView(Table.java:1056)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:6669)
at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:812)
at org.eclipse.swt.widgets.Table.drawRect(Table.java:1231)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:6254)
at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5578)
at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5979)
at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:92)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3997)
at org.eclipse.jface.tests.viewers.ViewerTestCase.processEvents(ViewerTestCase.java:104)
at org.eclipse.jface.tests.viewers.ViewerTestCase.tearDown(ViewerTestCase.java:147)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20240611-1800/testresults/html/org.eclipse.jface.tests_ep433I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

@fedejeanne relates to current commit in stacktrace: cbda3bc3e702e6f3cbcac9042b0b46439b0454b0

**Comment by merks** [comment]
The Oomph builds which test launching the installer also fail:
```
!SESSION 2024-06-12 08:37:29.754 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.5
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties D:\Users\merks\oomph-1.34\git\oomph\plugins\org.eclipse.oomph.setup.installer.tests\target\surefire.properties -testApplication org.eclipse.oomph.setup.installer.application -product org.eclipse.oomph.setup.installer.product -nouithread -timeout 60000
Command-line arguments:  -data D:\Users\merks\oomph-1.34\git\oomph\plugins\org.eclipse.oomph.setup.installer.tests\target\work\data -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties D:\Users\merks\oomph-1.34\git\oomph\plugins\org.eclipse.oomph.setup.installer.tests\target\surefire.properties -testApplication org.eclipse.oomph.setup.installer.application -product org.eclipse.oomph.setup.installer.product -nouithread -timeout 60000

!ENTRY org.eclipse.jface 4 0 2024-06-12 08:37:34.063
!MESSAGE Unhandled event loop exception during blocked modal context.
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Argument cannot be null))
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3690)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.block(ModalContext.java:168)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:370)
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:470)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$ProgressMonitorDialogIndexLoader.loadIndex(SetupWizard.java:1569)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$IndexLoader.loadIndex(SetupWizard.java:1116)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$4.run(SetupWizard.java:924)
	at org.eclipse.oomph.ui.UIUtil$4.run(UIUtil.java:565)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3690)
	at org.eclipse.oomph.setup.internal.installer.Installer.runEventLoop(Installer.java:359)
	at org.eclipse.oomph.setup.internal.installer.InstallerDialog.show(InstallerDialog.java:434)
	at org.eclipse.oomph.setup.internal.installer.InstallerApplication.run(InstallerApplication.java:295)
	at org.eclipse.oomph.setup.internal.installer.InstallerApplication.start(InstallerApplication.java:401)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:34)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:129)
	at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
Caused by: org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Argument cannot be null)
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4072)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3690)
	at org.eclipse.oomph.setup.ui.wizards.SetupWizard$IndexLoader.awaitIndexLoad(SetupWizard.java:1481)
	at org.eclipse.oomph.setup.internal.installer.InstallerDialog$2$1.run(InstallerDialog.java:143)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	... 33 more
Caused by: java.lang.IllegalArgumentException: Argument cannot be null
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.graphics.GC.setBackground(GC.java:4194)
	at org.eclipse.jface.viewers.OwnerDrawLabelProvider.erase(OwnerDrawLabelProvider.java:195)
	at org.eclipse.jface.viewers.StyledCellLabelProvider.erase(StyledCellLabelProvider.java:266)
	at org.eclipse.jface.viewers.OwnerDrawLabelProvider$OwnerDrawListener.handleEvent(OwnerDrawLabelProvider.java:66)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:91)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4299)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1172)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1196)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1181)
	at org.eclipse.swt.widgets.Tree.CDDS_ITEMPREPAINT(Tree.java:1091)
	at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7558)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5787)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1972)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5355)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4779)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5064)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1575)
	at org.eclipse.swt.widgets.Widget.wmPaint(Widget.java:2301)
	at org.eclipse.swt.widgets.Control.WM_PAINT(Control.java:5360)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1495)
	at org.eclipse.swt.widgets.Tree.WM_PAINT(Tree.java:7168)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4780)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6149)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5064)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1575)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4824)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6149)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5064)
	at org.eclipse.swt.internal.win32.OS.SendMessage(Native Method)
	at org.eclipse.swt.widgets.Tree.setSelection(Tree.java:5173)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:321)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:2785)
	at org.eclipse.jface.viewers.StructuredViewer.setSelectionToWidget(StructuredViewer.java:1706)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:3253)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1662)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1093)
	at org.eclipse.oomph.setup.internal.installer.ProductPage$18$1.run(ProductPage.java:719)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	... 39 more
```

**Comment by merks** [comment]
If I understand the problem correctly, the JFace changes here:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/084faad1-9c06-412e-9fc0-a0c6f86317ee)

assume that these registrations from this "very far downstream" plugin are necessarily available:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/6dbd22bf-c2f1-479a-ac7d-3804a0b1c091)

But that transitively assumes there is necessarily a workbench, which is just not an appropriate general assumption for JFace itself, and is not an assumption met by the installer.

I'm not sure the appropriate solution...

**Comment by fedejeanne** [comment]
fyi @BeckerWdf @Christopher-Hermann 

@merks thank you for the analysis! One question: how come this only failed in the nightly builds and not in the PR checks?

**Comment by iloveeclipse** [comment]
Background selection colors are broken for me on Linux in all tree views if they are inactive: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1956

**Comment by laeubi** [comment]
> I'm not sure the appropriate solution...

I would simply check if they are null and if it is the case use whatever was done before....

**Comment by merks** [comment]
Sorry, the builds and how/what they actually test are often a dark mystery to me.   😭 

Apparently there are all these test.xml things that launch tests in a way  (the test framework) that only the full integration build uses them but not the verification builds:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/fe64c454-8541-44dc-aea2-e5176be99322)

**Comment by merks** [comment]
> > I'm not sure the appropriate solution...
> 
> I would simply check if they are null and if it is the case use whatever was done before....

Yes, though the problem seems sprinkled into more than one place and even the Javadoc refers to these things.

**Comment by Phillipus** [comment]
> But that transitively assumes there is necessarily a workbench, which is just not an appropriate general assumption for JFace itself, and is not an assumption met by the installer.

JFace should have no dependency on the workbench at all. See https://wiki.eclipse.org/JFace#Using_JFace_outside_the_Eclipse_platform

Are string constants like "org.eclipse.ui.workbench.SELECTED_CELL_BACKGROUND", even if optional, at least a loose dependency? And doesn't it mean that the intended behaviour is not consistent?

**Comment by jukzi** [comment]
this issue can be closed?

**Comment by BeckerWdf** [comment]
I would say: "Yes"
