### ISSUE TITLE
[Test] org.eclipse.ui.tests.navigator.resources.NestedResourcesTests.testProjectHierarchy fails on linux intermittently

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.ui#196]
The test  org.eclipse.ui.tests.navigator.resources.NestedResourcesTests.testProjectHierarchy failed on linux in the I-Build [I20220706-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220706-1800/testresults/html/org.eclipse.ui.tests.navigator_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html) with the below error

```
expected:<2> but was:<1>

java.lang.AssertionError: expected:<2> but was:<1>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.eclipse.ui.tests.navigator.resources.NestedResourcesTests.testProjectHierarchy(NestedResourcesTests.java:98) 
```

**Comment by fedejeanne** [comment]
It failed on Mac too
