### ISSUE TITLE
Unavailable/uninstalled bundle - bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView

### ISSUE THREAD

**Issue by minduch** [eclipse-platform/eclipse.platform.ui#2175]
Our project contains a plugin with 2 views that fails to load in Eclipse 2024-09 M2. (I added the Samples View too if we did something wrong, that apart of the `@Inject workbench` was fine - `@Inject` was using jakarta injekt that was corrected).

On Windows 11, the errors are logged as:

```
!ENTRY org.eclipse.e4.ui.workbench 2 0 2024-08-09 12:11:58.597
!MESSAGE Removing PartDescriptorImpl with the "com.netphantom.eclipse.project.DigestView" id and the "Digest" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.eclipse.e4.ui.workbench 2 0 2024-08-09 12:11:58.599
!MESSAGE Removing PartDescriptorImpl with the "com.netphantom.eclipse.project.ReferencesView" id and the "References" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled

!ENTRY org.eclipse.e4.ui.workbench 2 0 2024-08-09 12:11:58.599
!MESSAGE Removing PartDescriptorImpl with the "com.netphantom.eclipse.plugin.views.SampleView" id and the "Sample View" label.It points to the non available "bundleclass://org.eclipse.ui.workbench/org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled
```

I have tried zapping all Eclipse installation plus directories `.eclipse`, `.cache` and `.m2`, and workspace, then reinstalling Eclipse 2024-09 M2, 2024-06 GA and 2023-09 GA. I still keep on getting this failure. The Eclipse "version" is of `Eclipse Committers` type, Java is `Temurin 21.0.4` or for running also tried `Temurin 17.0.12` for the `Run` or `Debug` configurations.

I also get a few other exceptions I can't wrap my head around as shown below, and I also get this in earlier Eclipse 2024-06 GA. The plugins project are configured as "normal" plug-in projects + Java nature, nothing fancy with Maven or so.

```
!ENTRY org.eclipse.ui.workbench 4 2 2024-08-09 12:11:58.425
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in com.netphantom.eclipse.plugin was unable to load class com.netphantom.eclipse.plugin.Startup.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:242)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:225)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:987)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:275)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:65)
	at org.eclipse.ui.internal.WorkbenchPlugin.lambda$0(WorkbenchPlugin.java:285)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:59)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:283)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:55)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2706)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassNotFoundException: com.netphantom.eclipse.plugin.Startup cannot be found by com.netphantom.eclipse.plugin_7.7.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:643)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:223)
	... 10 more
!SUBENTRY 1 org.eclipse.equinox.registry 4 1 2024-08-09 12:11:58.426
!MESSAGE Plug-in com.netphantom.eclipse.plugin was unable to load class com.netphantom.eclipse.plugin.Startup.
!STACK 0
java.lang.ClassNotFoundException: com.netphantom.eclipse.plugin.Startup cannot be found by com.netphantom.eclipse.plugin_7.7.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:643)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:223)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:987)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:275)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:65)
	at org.eclipse.ui.internal.WorkbenchPlugin.lambda$0(WorkbenchPlugin.java:285)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:59)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:283)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:55)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2706)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
!SUBENTRY 1 org.eclipse.equinox.registry 4 1 2024-08-09 12:11:58.426
!MESSAGE Plug-in com.netphantom.eclipse.plugin was unable to load class com.netphantom.eclipse.plugin.Startup.
!STACK 0
java.lang.ClassNotFoundException: com.netphantom.eclipse.plugin.Startup cannot be found by com.netphantom.eclipse.plugin_7.7.0.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:643)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:223)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:987)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:275)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:65)
	at org.eclipse.ui.internal.WorkbenchPlugin.lambda$0(WorkbenchPlugin.java:285)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:59)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:283)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:55)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench$39.run(Workbench.java:2706)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

This code has been working fine for the last 10 or more Eclipse versions, so I don't really understand what is gone wrong. Sure, we've updated the code for Java 17 some time ago, but this has been running fine since Java 17 was introduced into Eclipse (4.19 or 4.21?).

All this when happens when launching a `Run` or `Debug` in Eclipse to launch the `org.eclipse.epp.package.committers.product` product with our plugins.

**Comment by merks** [comment]
Can you clear the log and attach the full <workspace>/.metadata/.log file here? You can delete that file before you start to reduce the log content to just the startup problems.   I just wonder if there is some more helpful detail in earlier stack trace.

**Comment by minduch** [comment]
Here is the full log (cleared before launch):

[.log](https://github.com/user-attachments/files/16562300/default.log)

The strange thing is why the classes can't be loaded, would this be due to the fact that they depend on the View's that can't be created either, due to the inaccessible (or missing) `org.eclipse.ui.internal.e4.compatibility.CompatibilityView`?

**Comment by minduch** [comment]
Do you have any clue as to how I can work-around it in e.g. older Eclipse versions, or if you could point me in the "right" direction where to look (if we've done something in our code - I know... it's a longshot)?

I have tried clearing/deleting/reinstalling both Eclipse and workspaces and directories `%USERPROFILE%\.eclipse`, `.p2` (when available for older versions), `.m2` and `.cache`. I have been working with Eclipse plugins development since version 3 and never seen such a stubborn behavior!

**Comment by merks** [comment]
Every single thing in the log appears to be trying to create an executable extension org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension where it looks for some class in some expected plugin that is supposed to provide it and simply fails to find it.   I see no logged errors about bundles failing to start because of missing dependencies.  No linkage errors or other runtime errors.  It's really as if the bundles don't actually provide the classes.  Maybe running with -clean -debug would provide information about bundles failing to start.  

Are you able to debug launch these from a development IDE?

**Comment by minduch** [comment]
No, when I start debugging or running, that is when it happens. So I'm in the "dark". I'll give the -debug option a try, I already have -clean.

**Comment by minduch** [comment]
Where do you specify -debug option? In Program Arguments or VM, like -Ddebug=true, or?

**Comment by merks** [comment]
It's a program arguments box of the arguments tab 

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html

Inspect what's in the Plug-ins tab.  Try the Validate Plug-ins button there.  

I've done silly things like disable auto build and then forgetting to enable it.

**Comment by minduch** [comment]
Done that. Added -debug to pgm args - no change (strange!). I turned on most all traces too and enabled each one. Where do trace files go (I can't find this info on the net)?

Eclipse Console output added below. I added the Program Arguments -debug -clearPersistedState, still same behavior.

[console.txt](https://github.com/user-attachments/files/16563603/console.txt)

Oh, great: ends with `org.eclipse.swt.SWTException: Failed to execute runnable (org.eclipse.swt.SWTError: No more handles [0x8007139f])`! (will uninstall suspected plugin "Tabnine" [Private+Protected AI Assistant] that probably fails due to these other errors). But Tabnine is not the cause, I'm sure.

**Comment by minduch** [comment]
I added "-debug -clear -clearPersistedState" options to eclipse.ini (2024-09 M2 version 4.33 - BTW Eclipse Marketplace app defintion calls version 4.33 "2024-06" in error - should be "2024-09" - where do I report this?).

Where are the debug files?

**Comment by merks** [comment]
Is -consoleLog in the arguments?  Then details should show in the console view.  I get confused here because we talk about debug launch but then we also talk about editing the eclipse.ini which does not sound like your launching your stuff from a development IDE.

**Comment by minduch** [comment]
Well, I tried (desperately) to find a solution, so I set -debug option in Eclipse IDE itself, no change, so I removed it.

The command line for launch configuration is:
```
C:\java\x64\jdk21\bin\javaw.exe
-XX:+ShowCodeDetailsInExceptionMessages
-agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:53906
-Dosgi.requiredJavaVersion=21
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Declipse.e4.inject.javax.warning=false
-DXXXorg.slf4j.simpleLogger.defaultLogLevel=off
-Dsun.java.command=Eclipse
-Xms256m
-Xmx4g
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Djava.security.manager=allow
-Declipse.pde.launch=true
-Dfile.encoding=UTF-8
-Dstdout.encoding=UTF-8
-Dstderr.encoding=UTF-8
-classpath "C:\Eclipse\2024-09\plugins\org.eclipse.equinox.launcher_1.6.900.v20240613-2009.jar;" org.eclipse.equinox.launcher.Main
-launcher "C:\Eclipse\2024-09\eclipse.exe"
-name Eclipse
-showsplash 600
-product org.eclipse.epp.package.committers.product
-data "C:\NP6\EclipseSamplesWorkspace"
-configuration "file:C:/NP6/EclipseSourcesWorkspace/.metadata/.plugins/org.eclipse.pde.core/NetPhantom Eclipse/"
-dev "file:C:/NP6/EclipseSourcesWorkspace/.metadata/.plugins/org.eclipse.pde.core/NetPhantom Eclipse/dev.properties"
-os win32
-ws win32
-arch x86_64
-nl en_US
-consoleLog
-debug
-clear
-clearPersistedState
```

Console view log attached: "same" thing...

[console2.txt](https://github.com/user-attachments/files/16565037/console2.txt)

**Comment by minduch** [comment]
This is how the started debug window of Eclipse "Committers" version with our 2 plugins looks like (pretty broken as nothing gets loaded):

![image](https://github.com/user-attachments/assets/bdd220ef-58fb-4d98-ae36-354297e3678b)
