### ISSUE TITLE
StickyScrollingHandlerTest.testThrottledExecution fails on mac

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2190]
https://download.eclipse.org/eclipse/downloads/drops4/I20240811-1800/testresults/html/org.eclipse.ui.editors.tests_ep433I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
Wanted but not invoked:
stickyLinesProvider.get(
400,
org.eclipse.jface.text.source.SourceViewer@296023de
);
-> at org.eclipse.ui.internal.texteditor.stickyscroll.StickyLinesProvider.get(StickyLinesProvider.java:47)

However, there was exactly 1 interaction with this mock:
stickyLinesProvider.get(
100,
org.eclipse.jface.text.source.SourceViewer@296023de
);
-> at org.eclipse.ui.internal.texteditor.stickyscroll.StickyScrollingHandler.calculateAndShowStickyLines(StickyScrollingHandler.java:151)


at org.eclipse.ui.internal.texteditor.stickyscroll.StickyLinesProvider.get(StickyLinesProvider.java:47)
at org.eclipse.ui.internal.texteditor.stickyscroll.StickyScrollingHandlerTest.testThrottledExecution(StickyScrollingHandlerTest.java:144)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
test was recently added with https://github.com/eclipse-platform/eclipse.platform.ui/pull/1949 @mickaelistria @Christopher-Hermann please check next i-Builds after everything you commit on the next day. You can find link to the current integration build here:
https://download.eclipse.org/eclipse/downloads/index.html

**Comment by jukzi** [comment]
Please also note that the toString() "SourceViewer@296023de" is not meaningfull

**Comment by jukzi** [comment]
@mickaelistria @Christopher-Hermann would you please fix?

**Comment by Christopher-Hermann** [comment]
I'm working on a Mac and locally the tests are working. I will try to find out why the tests are failing on the I build.

**Comment by Christopher-Hermann** [comment]
Test is still failing in IBuild

**Comment by Christopher-Hermann** [comment]
Let's see if the refactoring done with #2266 resolves the issue.

**Comment by jukzi** [comment]
still fails.

```
iStickyLinesProvider.getStickyLines( org.eclipse.jface.text.source.SourceViewer@55e13772, StickyLinesProperties[tabWith=4] ); Wanted 2 times: -> 
at org.eclipse.ui.internal.texteditor.stickyscroll.StickyScrollingHandlerTest.testThrottledExecution(StickyScrollingHandlerTest.java:163) But was 1 time: -> 
at org.eclipse.ui.internal.texteditor.stickyscroll.StickyScrollingHandler.calculateAndShowStickyLines(StickyScrollingHandler.java:154)

org.mockito.exceptions.verification.TooFewActualInvocations:
iStickyLinesProvider.getStickyLines(
org.eclipse.jface.text.source.SourceViewer@55e13772,
StickyLinesProperties[tabWith=4]
);
Wanted 2 times:
-> 
at org.eclipse.ui.internal.texteditor.stickyscroll.StickyScrollingHandlerTest.testThrottledExecution(StickyScrollingHandlerTest.java:163)
But was 1 time:
-> 
at org.eclipse.ui.internal.texteditor.stickyscroll.StickyScrollingHandler.calculateAndShowStickyLines(StickyScrollingHandler.java:154)
at org.eclipse.ui.internal.texteditor.stickyscroll.StickyScrollingHandlerTest.testThrottledExecution(StickyScrollingHandlerTest.java:163)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)

```


https://download.eclipse.org/eclipse/downloads/drops4/I20240929-1800/testresults/html/org.eclipse.ui.editors.tests_ep434I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

**Comment by Christopher-Hermann** [comment]
I will have a look
