### ISSUE TITLE
Multiple tests of StackRendererTest / TabStateHandlerTest / CompositePartClosingTest failing on MacOS

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.ui#2346]
Some test cases of `StackRendererTest`, `TabStateHandlerTest` and `CompositePartClosingTest` fail on MacOS in today's I-Build: https://download.eclipse.org/eclipse/downloads/drops4/I20240930-1800/testresults/html/org.eclipse.e4.ui.tests_ep434I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

Exemplary log:
```
Widget is disposed

org.eclipse.swt.SWTException: Widget is disposed
at org.eclipse.swt.SWT.error(SWT.java:4922)
at org.eclipse.swt.SWT.error(SWT.java:4837)
at org.eclipse.swt.SWT.error(SWT.java:4808)
at org.eclipse.swt.widgets.Widget.error(Widget.java:853)
at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:632)
at org.eclipse.swt.widgets.Control.getParent(Control.java:1846)
at org.eclipse.swt.widgets.Shell.getShells(Shell.java:1190)
at org.eclipse.swt.widgets.Shell.updateParent(Shell.java:2269)
at org.eclipse.swt.widgets.Shell.releaseWidget(Shell.java:1462)
at org.eclipse.swt.widgets.Widget.release(Widget.java:1439)
at org.eclipse.swt.widgets.Control.release(Control.java:2938)
at org.eclipse.swt.widgets.Widget.dispose(Widget.java:730)
at org.eclipse.e4.ui.workbench.renderers.swt.TabStateHandlerTest.tearDown(TabStateHandlerTest.java:56)
```

Since those tests were first and already failing in the GitHub Actions builds of #668, the failures are likely produced by that PR.

@marcushoepfner @vogella can you have a look please?

**Comment by vogella** [comment]
Revert https://github.com/eclipse-platform/eclipse.platform.ui/pull/2348

**Comment by jukzi** [comment]
validated in https://download.eclipse.org/eclipse/downloads/drops4/I20241007-1800/testresults/html/org.eclipse.e4.ui.tests_ep434I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
