### ISSUE TITLE
OutOfMemoryError reported by jenkins validation build after org.eclipse.ui.tests.UiTestSuite

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#2432]
See https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-2431/1/consoleFull that didn't changed code, just updated bundle versions, so the problem must be coming from either environment or code changes before.

The question is: what is causing that, and which heap space is actually used on jenkins?

```
Exception in thread "Active Thread: Equinox Container: aa943991-8bd5-44f7-a55a-1a7bc7647820" java.lang.OutOfMemoryError: Java heap space
Exception in thread "WorkbenchTestable" org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:209)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.runTest(E4Testable.java:118)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:38)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-11"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-22"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-23"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-24"
```

**Comment by iloveeclipse** [comment]
Also in https://ci.eclipse.org/platform/job/eclipse.platform.ui/view/change-requests/job/PR-2224/11/consoleFull

```
Exception in thread "WorkbenchTestable" org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.OutOfMemoryError: Java heap space)
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:209)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.runTest(E4Testable.java:118)
	at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.runTests(AbstractUITestApplication.java:38)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:79)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.mockito.internal.util.concurrent.WeakConcurrentMap.containsKey(WeakConcurrentMap.java:81)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.isMock(MockMethodAdvice.java:166)
	at java.base/java.lang.Object.equals(Object.java:163)
	at org.eclipse.e4.core.internal.di.ObjectDescriptor.hasQualifier(ObjectDescriptor.java:44)
	at org.eclipse.e4.core.internal.di.InjectorImpl.resolveArgs(InjectorImpl.java:573)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:291)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:233)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:174)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.isEnabled(HandlerServiceHandler.java:68)
	at org.eclipse.core.commands.Command.isEnabled(Command.java:832)
	at org.eclipse.ui.internal.actions.CommandAction.lambda$0(CommandAction.java:91)
	at org.eclipse.ui.internal.actions.CommandAction$$Lambda$384/0x0000000801000d78.commandChanged(Unknown Source)
	at org.eclipse.core.commands.Command$1.run(Command.java:529)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.commands.Command.fireCommandChanged(Command.java:522)
	at org.eclipse.core.commands.Command.lambda$0(Command.java:1000)
	at org.eclipse.core.commands.Command$$Lambda$216/0x0000000800edd2b8.handlerChanged(Unknown Source)
	at org.eclipse.core.commands.AbstractHandler.fireHandlerChanged(AbstractHandler.java:77)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.fireHandlerChanged(HandlerServiceHandler.java:189)
	at org.eclipse.core.commands.AbstractHandler.setBaseEnabled(AbstractHandler.java:111)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.isEnabled(HandlerServiceHandler.java:70)
	at org.eclipse.core.commands.Command.isEnabled(Command.java:832)
	at org.eclipse.ui.internal.actions.CommandAction.lambda$0(CommandAction.java:91)
	at org.eclipse.ui.internal.actions.CommandAction$$Lambda$384/0x0000000801000d78.commandChanged(Unknown Source)
	at org.eclipse.core.commands.Command$1.run(Command.java:529)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.core.commands.Command.fireCommandChanged(Command.java:522)
	at org.eclipse.core.commands.Command.lambda$0(Command.java:1000)
	at org.eclipse.core.commands.Command$$Lambda$216/0x0000000800edd2b8.handlerChanged(Unknown Source)
	at org.eclipse.core.commands.AbstractHandler.fireHandlerChanged(AbstractHandler.java:77)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.fireHandlerChanged(HandlerServiceHandler.java:189)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.handlerChanged(E4HandlerProxy.java:116)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Active Thread: Equinox Container: 882cd8a6-664e-4aea-971d-49c2b2d63bef"
Exception in thread "Worker-4" java.lang.OutOfMemoryError: Java heap space
An error has occurred. See the log file
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-2224/tests/org.eclipse.ui.tests/target/work/data/.metadata/.log.
```

Also in https://ci.eclipse.org/platform/job/eclipse.platform.ui/view/change-requests/job/PR-2424/11/consoleFull

```
  WorkbookEditorsHandlerTest.doTearDown:73 » Resource Problems encountered while deleting resources.

Tests run: 1659, Failures: 1, Errors: 5, Skipped: 196

Exception in thread "Active Thread: Equinox Container: 5e5cc6b7-0a59-4770-ba00-8313910b610d" java.lang.OutOfMemoryError: Java heap space

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-5"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Worker-15"
```

**Comment by merks** [comment]
Maybe this is related:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5056

**Comment by laeubi** [comment]
If I look at this where we exchaust thread pools:
- https://github.com/eclipse-platform/eclipse.platform/issues/1592

I just wanted to mention that each thread requires a small amount of ram as well....

**Comment by iloveeclipse** [comment]
> I just wanted to mention that each thread requires a small amount of ram as well....

I would expect jenkins runs on a very small VM with very few  (2-4?) cores, so thread pool size would be also very small and shouldn't be the root cause here.

**Comment by iloveeclipse** [comment]
> Maybe this is related: 
> https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5056

Hmm. I don't see OOM's on JDT tests which **are** known to be memory sensitive, and OOMs in UI tests **seem** to happen on / after specific testsuite, so it look like a code regression on our (platform / UI) side.

**Comment by laeubi** [comment]
> I would expect jenkins runs on a very small VM with very few (2-4?) cores, so thread pool size would be also very small and shouldn't be the root cause here.

This is a common misunderstanding with ForkJoinPools... If threads are blocked (e.g. the are waiting for I/O or waiting for other threads to join), then **new** threads are spwaned untill the configured concurrency level is fulfilled again, [see here](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ForkJoinPool.html)

>  The pool attempts to maintain enough active (or available) threads by **dynamically adding, suspending, or resuming** internal worker threads, even if some tasks are stalled waiting to join others.

The exception [given here](https://github.com/eclipse-platform/eclipse.platform/issues/1592) says "Thread limit exceeded replacing blocked worker" and the limit is by default **32767 (!)**

**Comment by iloveeclipse** [comment]
> This is a common misunderstanding with ForkJoinPools

Cool, thanks. So one part of the problem in https://github.com/eclipse-platform/eclipse.platform/issues/1592 is that the used pool is not limited in size (beside that the LocalFile.internalDelete() doesn't do what it supposed to do)?

**Comment by laeubi** [comment]
It is just a guess, if we see Thread explosion somehwere and memmory problems elsewhere, In general I/O bound tasks don'T play well with fork-join because the whole fork-join was introduced because of CPU bound (!) task usually suffer from context switch penalities. For I/O non blocking I/O is usually most faster if we asumme a shared device (e.g. harddisk / network / ...).

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-2433/1/console shows no major memory increase **after** multiple `Thread limit exceeded replacing blocked worker` errors.
So something else must be the problem here.

**Comment by mickaelistria** [comment]
Was it tried to revert https://github.com/eclipse-platform/eclipse.platform/issues/1592 in a PR and see if it makes build more successful?

**Comment by iloveeclipse** [comment]
> Was it tried to revert [eclipse-platform/eclipse.platform#1592](https://github.com/eclipse-platform/eclipse.platform/issues/1592) in a PR and see if it makes build more successful?

As mentioned, I believe we only see OOM's in platform UI tests so far. The change https://github.com/eclipse-platform/eclipse.platform/issues/1592 would also affect JDT tests, which seem not to be the case.

**Comment by jukzi** [comment]
i am just running UiTestSuite locally, and monitoring the memory. The increasing memory usage feels like some leak between tests:
![image](https://github.com/user-attachments/assets/f2248cd3-3801-4a61-8f01-b5e4e8993148)

**Comment by mickaelistria** [comment]
> As mentioned, I believe we only see OOM's in platform UI tests so far. 

Maybe that one of Platform UI tests do exactly track some scalability related to intense usage of the resource model operation and does lead to OOM with the exact purpose of showing a performance issue.
But it's indeed difficult to test as its different repos...

**Comment by jukzi** [comment]
running UiTestSuit locally, i also see more and more symbols in the taskbar, feels like even whole applications are not closed after tests:
![image](https://github.com/user-attachments/assets/c13f3fc4-4f20-445e-a53c-ce6ac451f82a)

**Comment by jukzi** [comment]
I took a heapdump during UiTestSuit  and can not see any singular Object containing to much memory, but it can be seen that many String are duplicate the same count:
![image](https://github.com/user-attachments/assets/f49d65e9-31db-48f5-a064-5d46fc017c79)
That feels like a general Leak of a greater instance too.
The root of an exampe duplicate string is in e4, sounds like a leak in e4 contexts:
![image](https://github.com/user-attachments/assets/708557e0-c342-47b0-b026-fb7b4e5538b5)

**Comment by akurtakov** [comment]
The jdt bits should not be used in platform tests to reduce cross repo cycling dependencies . https://github.com/eclipse-platform/eclipse.platform.ui/pull/2609 is work towards it.

**Comment by iloveeclipse** [comment]
Any objections to merge https://github.com/eclipse-platform/eclipse.platform.ui/pull/2433 to see memory use in the console? Currently PR build fails due OOM :-)

**Comment by akurtakov** [comment]
> Any objections to merge #2433 to see memory use in the console? Currently PR build fails due OOM :-)

It should help and show things in the console for the PR too, right?

**Comment by iloveeclipse** [comment]
Yes

**Comment by akurtakov** [comment]
My thinking - if the PR fails with OOM itself and gives all the details for investigation there is no need to merge it as doing more would not help with OOM and investigation can continue on the PR itself till it actually improves the situation.

**Comment by jukzi** [comment]
> running UiTestSuit locally, i also see more and more symbols in the taskbar

Leak: Example ImportArchiveOperationTest alone opens a lot of windows (using openTestWindow().run) without ever closing them. I guess this is regression from 2ebbbe9cdab971d70511a23c5a4ba4dca34538dc @akurtakov  because the superclass UITestCase may have closed those windows using UITestCase.closeTestWindows

**Comment by akurtakov** [comment]
I'll fix ImportArchiveOperationTest now. Funny, that I worked on this one while investigating the problem.

**Comment by jukzi** [comment]
tested that a revert close those windows.

**Comment by akurtakov** [comment]
#2610 should reduce the frequency of the problem but we have been seeing OOMs before it too so this issue should stay open till we see no OOMs for couple of weeks at least

**Comment by jukzi** [comment]
There is still heap memory leaked and even some windows not closed after tests.
![image](https://github.com/user-attachments/assets/a263ca64-8fe2-4fdd-9f30-9dce8d8f62c5)

**Comment by iloveeclipse** [comment]
> There is still heap memory leaked and even some windows not closed after tests

Any chance to see which test leaks what?

**Comment by akurtakov** [comment]
Seems like https://github.com/eclipse-platform/eclipse.platform.ui/pull/2609 brought memory consumption down enough to make build not OOM anymore (for now). 
@jukzi Can you show us heap memory usage after this patch too?

**Comment by iloveeclipse** [comment]
> Seems like #2609 brought memory consumption down enough to make build not OOM anymore (for now). @jukzi Can you show us heap memory usage after this patch too?

With the PR https://github.com/eclipse-platform/eclipse.platform.ui/pull/2433 rebased on 78615b83bfb39e49f20724c0dc78c1eab47c6c53 we see following picture:

**before** 78615b83bfb39e49f20724c0dc78c1eab47c6c53
```
#################################################
testOpenCloseView
########### Memory usage reported by JVM ########
   1.073.741.824 bytes max heap
   1.070.596.096 bytes heap allocated
     681.852.864 bytes free heap
     388.743.232 bytes used heap
#################################################
```
**OOM!**

**after** 78615b83bfb39e49f20724c0dc78c1eab47c6c53
```
#################################################
testOpenCloseView
########### Memory usage reported by JVM ########
   1.073.741.824 bytes max heap
     300.941.312 bytes heap allocated
     168.866.408 bytes free heap
     132.074.904 bytes used heap
#################################################
```
**No OOM!**

**Comment by akurtakov** [comment]
Removing o.e.jdt.ui from the equation and reducing allocated heap by ~700MB is very suspicious and probably points to something huge not being cleaned up there.

**Comment by iloveeclipse** [comment]
I guess automatic detection of JRE's on startup is one of the pain points, we had to explicitly disable that job in all JDT/PDE repos where Java tooling is present.

**Comment by merks** [comment]
How likely is that to be painful for a user with many JDKs!

**Comment by jukzi** [comment]
> @jukzi Can you show us heap memory usage after this patch too?

see https://github.com/eclipse-platform/eclipse.platform.ui/issues/2615 as a continuation

**Comment by iloveeclipse** [comment]
> How likely is that to be painful for a user with many JDKs!

Not really, given a reasonable sized RAM or proper JVM arguments. 4GB RAM (or 1GB max heap default == 1/4 RAM) is surely not suitable anymore for a serious work. However with already 8GB max heap you don't see any problem at all also on large workspaces.

**Comment by iloveeclipse** [comment]
I believe this can be closed now.
