### ISSUE TITLE
[test] NPE in BarContentAssistProcessor

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2453]
logged when locally running org.eclipse.ui.genericeditor.tests.CompletionTest
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.jface.text.IDocument.getLength()" because the return value of "org.eclipse.jface.text.ITextViewer.getDocument()" is null
	at org.eclipse.ui.genericeditor.tests.contributions.BarContentAssistProcessor.computeCompletionProposals(BarContentAssistProcessor.java:45)
	at org.eclipse.ui.genericeditor.tests.contributions.LongRunningBarContentAssistProcessor.computeCompletionProposals(LongRunningBarContentAssistProcessor.java:36)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

```

**Comment by nettozahler** [comment]
This one seems to be trivial to me and so is the bugfix. But maybe I have overlooked sth.
