### ISSUE TITLE
UIDialogsAuto.testAbout failed in I20241029-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2466]
Failed in multiple platforms

```
java.lang.ArithmeticException: / by zero
at org.eclipse.ui.tests.harness.util.DialogCheck.verifyButtonText(DialogCheck.java:159)
at org.eclipse.ui.tests.harness.util.DialogCheck.verifyCompositeText(DialogCheck.java:133)
at org.eclipse.ui.tests.harness.util.DialogCheck.verifyCompositeText(DialogCheck.java:141)
at org.eclipse.ui.tests.harness.util.DialogCheck.verifyCompositeText(DialogCheck.java:141)
at org.eclipse.ui.tests.harness.util.DialogCheck.verifyCompositeText(DialogCheck.java:141)
at org.eclipse.ui.tests.harness.util.DialogCheck.verifyCompositeText(DialogCheck.java:141)
at org.eclipse.ui.tests.harness.util.DialogCheck.assertDialogTexts(DialogCheck.java:88)
at org.eclipse.ui.tests.dialogs.UIDialogsAuto.testAbout(UIDialogsAuto.java:73)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20241029-1800/testresults/html/org.eclipse.ui.tests_ep434I-unit-linux-x86_64-java23_linux.gtk.x86_64_23.html
https://download.eclipse.org/eclipse/downloads/drops4/I20241029-1800/testresults/html/org.eclipse.ui.tests_ep434I-unit-win32-x86_64-java17_win32.win32.x86_64_17.html
...

**Comment by jukzi** [comment]
already fixed by https://github.com/eclipse-platform/eclipse.platform.ui/commit/bbd9101ffd7f646fcdfafab2ddc66288758650a4
