### ISSUE TITLE
NPE at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.getFixedSides()

### ISSUE THREAD

**Issue by NikitaIsalkar** [eclipse-platform/eclipse.platform.ui#2526]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

1. Launch our Eclipse based application.
2. Click on minimize button for any view (for example, Project Explorer).
3. After minimizing this view, we get icons on either side of the window.
4. Click on View icon, after clicking on the icon I should be able to see the view, but instead I am getting NullPointerException in TrimStack.getFixedSides(method) and UI is behaving unusual.
 Furthermore, in some instances the icons are hidden, they only show up after I restart my application.

Please see : We have upgraded RCP from 4.6.3 to 4.15 and we are getting this issue after the upgrade. 

I expected: *<After minimizing the window, when I click on view icon, i should be able to see the view>*

But got: *<I got NullPointerException in TrimStack.getFixedSides(method) and UI is behaving unusual.>*

## Here is some relevant log output

From `<workspace>/.metadata/.log`
```
java.lang.NullPointerException
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.getFixedSides(TrimStack.java:1180)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.getHostPane(TrimStack.java:1162)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.showStack(TrimStack.java:950)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack$2.widgetSelected(TrimStack.java:516)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at com.rocketsoftware.bi.ide.core.rcp.BiApplication.runApp(BiApplication.java:195)
	at com.rocketsoftware.bi.ide.core.rcp.BiApplication.start(BiApplication.java:81)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

## Tested under this environment:
* OS & version: Windows 10
* Eclipse IDE/Platform version (as shown in *Help > About*): Version: 2020-03 (4.15.0)
Build id: 20200313-1211
* We have upgraded RCP from 4.6.3 to 4.15, we never got this issue with RCP 4.6.3, its happening after upgrade to 4.15. 

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by jukzi** [comment]
Please report stacktrace reproducable with current release 2024-06 or better with daily build:
https://download.eclipse.org/eclipse/downloads/drops4/S-4.33RC2-202408281820/

**Comment by NikitaIsalkar** [comment]
@jukzi , I have tried with latest release and getting below stack when I am trying to restore the view.
-------------------------------------------------------------------------------------------------------------------
java.lang.NullPointerException
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.getFixedSides(TrimStack.java:1178)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.getHostPane(TrimStack.java:1160)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack.showStack(TrimStack.java:948)
	at org.eclipse.e4.ui.workbench.addons.minmax.TrimStack$2.widgetSelected(TrimStack.java:514)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4105)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1037)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3922)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3524)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at com.rocketsoftware.bi.ide.core.rcp.BiApplication.runApp(BiApplication.java:195)
	at com.rocketsoftware.bi.ide.core.rcp.BiApplication.start(BiApplication.java:81)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

**Comment by NikitaIsalkar** [comment]
While debugging, I have found that line 1177(TrimStack.java) is returning NULL, which is causing a NPE while I am trying to maximize the view.

**Comment by jukzi** [comment]
looks like you comment on this version and "trimCtrl" is null:
![image](https://github.com/user-attachments/assets/651777f3-5bdf-43ff-81cb-852f7a81afba)

**Comment by jukzi** [comment]
I can not reproduce the issue with the given instructions with a standard eclipse IDE installation.

**Comment by jukzi** [comment]
One could return the default value SWT.BOTTOM | SWT.RIGHT if trimCtrl is null, but it would be better to find out why trimCtrl is null in your use-case.

**Comment by NikitaIsalkar** [comment]
Hi @jukzi ,

I am getting below exception while launching my Application itself, before even trying to minimize the view. May you please help me with this 

Exception occurred while rendering: org.eclipse.ui.ide.perspectivestack(minimized)=org.eclipse.e4.ui.model.application.ui.menu.impl.ToolControlImpl@3d700cde (tags: [TrimStack, Draggable], contributorURI: null) (widget: null, renderer: org.eclipse.e4.ui.workbench.renderers.swt.ToolControlRenderer@790a736e, toBeRendered: true, onTop: false, visible: true, containerData: null, accessibilityPhrase: null) (contributionURI: bundleclass://org.eclipse.e4.ui.workbench.addons.swt/org.eclipse.e4.ui.workbench.addons.minmax.TrimStack, object: org.eclipse.e4.ui.workbench.addons.minmax.TrimStack@609abb2e)

**Comment by jukzi** [comment]
Sorry, i can not help with your Applications problems.
