### ISSUE TITLE
Random failing FileBuffersForFilesInLinkedFolders

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2528]
https://download.eclipse.org/eclipse/downloads/drops4/I20241120-1800/testresults/html/org.eclipse.core.filebuffers.tests_ep434I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html
```
expected:<1> but was:<0>java.lang.AssertionError: expected:<1> but was:<0>
at org.eclipse.core.filebuffers.tests.FileBufferFunctions.test16_3(FileBufferFunctions.java:1029)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by jukzi** [comment]
same in https://download.eclipse.org/eclipse/downloads/drops4/I20241126-0110/testresults/html/org.eclipse.core.filebuffers.tests_ep435I-unit-linux-x86_64-java17_linux.gtk.x86_64_17.html

**Comment by jukzi** [comment]
failed in https://download.eclipse.org/eclipse/downloads/drops4/I20250203-1800/testresults/html/org.eclipse.core.filebuffers.tests_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html with different message:
```
java.lang.AssertionError: Wrong listener notifcation in org.eclipse.core.filebuffers.tests.FileBuffersForFilesInLinkedFolders:
listener.count: 0 (expected: 1)
listener.newLocation: null
newLocation: /project/folderA/MovedLinkedFile
buffers identical: false
at org.eclipse.core.filebuffers.tests.FileBufferFunctions.test15(FileBufferFunctions.java:906)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by jukzi** [comment]
test16_3 failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20250204-1800/testresults/html/org.eclipse.core.filebuffers.tests_ep435I-unit-linux-x86_64-java23_linux.gtk.x86_64_23.html

**Comment by trancexpress** [comment]
Seen again here: https://download.eclipse.org/eclipse/downloads/drops4/I20260306-1800/reports.html#tests

https://download.eclipse.org/eclipse/downloads/drops4/I20260306-1800/testresults/html/org.eclipse.core.filebuffers.tests_ep440I-unit-linux-x86_64-java25_linux.gtk.x86_64_25.html

```
org.eclipse.core.filebuffers.tests.FileBuffersForFilesInLinkedFolders	test16_3()	Failure	expected: <1> but was: <0>

org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
at org.eclipse.core.filebuffers.tests.FileBufferFunctions.test16_3(FileBufferFunctions.java:1005)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604) 
```

Workspace log:

https://download.eclipse.org/eclipse/downloads/drops4/I20260306-1800/testresults/ep440I-unit-linux-x86_64-java25_linux.gtk.x86_64_25/org.eclipse.core.filebuffers.tests.FileBuffersTestSuite.txt

```
!ENTRY org.eclipse.core.filebuffers.tests 4 0 2026-03-06 23:51:43.121
!MESSAGE FAIL in test16_3()
!STACK 0
org.opentest4j.AssertionFailedError: expected: <1> but was: <0>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
	at org.eclipse.core.filebuffers.tests.FileBufferFunctions.test16_3(FileBufferFunctions.java:1005)
```

Console logs:

https://download.eclipse.org/eclipse/downloads/drops4/I20260306-1800/testresults/consolelogs/ep440I-unit-linux-x86_64-java25_linux.gtk.x86_64_25_consolelog.txt


```
java-test:
     [echo] Running org.eclipse.core.filebuffers.tests.FileBuffersTestSuite. Result file: /home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java25/workarea/I20260306-1800/eclipse-testing/results/ep440I-unit-linux-x86_64-java25_linux.gtk.x86_64_25/org.eclipse.core.filebuffers.tests.FileBuffersTestSuite.xml
     [echo] timout property: 7200000
     [echo] frameworkvmargs:  -Xms256m -Xmx2048m -Djava.io.tmpdir=/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java25/tmp
     [echo] vmargs: 
     [echo] extraVMargs: 
     [echo] frameworkperfargs: 
     [echo] crash loglocationarg (if any): ${loglocationarg}
     [echo] crash loglocation (if not default): 
     [java] WARNING: A restricted method in java.lang.Runtime has been called
     [java] WARNING: java.lang.Runtime::load has been called by org.eclipse.equinox.launcher.JNIBridge in an unnamed module (file:/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java25/workarea/I20260306-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.equinox.launcher_1.7.100.v20251111-0406.jar)
     [java] WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module
     [java] WARNING: Restricted methods will be blocked in a future release unless native access is enabled
     [java] 
     [java] Mar 06, 2026 11:51:39 PM org.apache.aries.spifly.BaseActivator log
     [java] INFO: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple
     [java] INFO: timeoutScreenOutputDir: /home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java25/workarea/I20260306-1800/eclipse-testing/results/ep440I-unit-linux-x86_64-java25_linux.gtk.x86_64_25/timeoutScreens
     [java] INFO: timeout: 7200000
     [java] Java Result: 1
```

I see a workspace update job and auto-build running in parallel, but I don't see how that can cause the fails here...
