### ISSUE TITLE
Random failing LargeFileTest

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2622]
https://download.eclipse.org/eclipse/downloads/drops4/I20241211-1800/testresults/html/org.eclipse.ui.editors.tests_ep435I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html

```
java.lang.AssertionError: Opening large file took too long: 644.8726ms with marker vs. 306.91605ms without
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.ui.editors.tests.LargeFileTest.openLargeFileWithAnnotation(LargeFileTest.java:135)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

cc at author of that test: @tomaswolf 
maybe just increase timeout?

**Comment by tomaswolf** [comment]
I thought a factor of 2 was already rather generous. Apparently not. In the bug report linked in the commit message when that test was created, the UI freeze was 15sec.

As the comment in the test class says, all this timing is very approximate. So either use a larger factor, or come up with a better way to test for this, or investigate why opening the file with a single marker takes more than twice as long, and then improve that to be not that slow.

**Comment by jukzi** [comment]
Performance tests using the clock time have not been shown successful with our build infrastructure as the machines tend to have to much jitter in their performance. 
If the build machine pauses for a second for unkknown reasons it is totally unrelated to the code tested.
Time should only be used as timeout after a few seconds.

**Comment by jukzi** [comment]
again in https://download.eclipse.org/eclipse/downloads/drops4/I20250113-1800/testresults/html/org.eclipse.ui.editors.tests_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html
` Opening large file took too long: 964.4072ms with marker vs. 445.42303ms without`

**Comment by jukzi** [comment]
again in https://download.eclipse.org/eclipse/downloads/drops4/I20250206-1800/testresults/html/org.eclipse.ui.editors.tests_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html
`Opening large file took too long: 977.1361ms with marker vs. 462.33417ms without`

**Comment by AzazelSensei** [comment]
Opened https://github.com/eclipse-platform/eclipse.platform.ui/pull/4314 — Widened the marker timing factor from 2x to 5x so CI jitter around 2.1x stops failing the test.

**Comment by vogella** [comment]
Stable since a while
