### ISSUE TITLE
[performance] CloseUnrelatedProjectsAction.buildConnectedComponents(IProject[]) blocks UI startup

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#2636]
org.eclipse.ui.actions.CloseUnrelatedProjectsAction.buildConnectedComponents(IProject[]) calls the following code possibly in the UI thread:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/0344b2b062792a7336fe40edaefe768595e1d3f0/bundles/org.eclipse.ui.ide/extensions/org/eclipse/ui/actions/CloseUnrelatedProjectsAction.java#L83

this leads to all classpath containers of all projects to be resolved what is a costly operation and blocks the whole IDE startup procedure see here:
- https://github.com/eclipse-pde/eclipse.pde/issues/1481

instead the computation should happen in the background and only the UI has to be updated once the operation succeeded.

**Comment by vogella** [comment]
#3871 will be reverted with #3942 

This problem exists again. I do not plan to work on this again in the near future.

**Comment by vogella** [comment]
Sampling the main thread of an Eclipse SDK every 500 ms during startup (115 samples,
Windows, Java 21) shows the UI thread BLOCKED for roughly 65 seconds, samples 26 to 102,
t=21.9s to t=86.5s. Full stack of the first blocked sample, trimmed at the bottom:

````
    "main" #1 BLOCKED (on object monitor)
      at org.eclipse.pde.internal.core.PluginModelManager.findModel(PluginModelManager.java:951)
      - waiting to lock <0x0000000605c90990> (a java.lang.Object)
      at org.eclipse.pde.internal.core.DynamicPluginProjectReferences.getDependentProjects(DynamicPluginProjectReferences.java:43)
      at org.eclipse.core.internal.resources.ProjectDescription.computeDynamicReferencesForProject(ProjectDescription.java:1037)
      at org.eclipse.core.internal.resources.ProjectDescription.getAllBuildConfigReferences(ProjectDescription.java:297)
      at org.eclipse.core.internal.resources.ProjectDescription.getAllReferences(ProjectDescription.java:252)
      at org.eclipse.core.internal.resources.Project.getReferencedProjects(Project.java:522)
      at org.eclipse.ui.actions.CloseUnrelatedProjectsAction.buildConnectedComponents(CloseUnrelatedProjectsAction.java:83)
      at org.eclipse.ui.actions.CloseUnrelatedProjectsAction.computeRelated(CloseUnrelatedProjectsAction.java:207)
      at org.eclipse.ui.actions.CloseUnrelatedProjectsAction.getSelectedResources(CloseUnrelatedProjectsAction.java:227)
      at org.eclipse.ui.actions.SelectionListenerAction.selectionIsOfType(SelectionListenerAction.java:242)
      at org.eclipse.ui.actions.CloseResourceAction.updateSelection(CloseResourceAction.java:232)
      at org.eclipse.ui.actions.BaseSelectionListenerAction.selectionChanged(BaseSelectionListenerAction.java:128)
      at org.eclipse.ui.internal.navigator.resources.actions.ResourceMgmtActionProvider.updateActionBars(ResourceMgmtActionProvider.java:276)
      at org.eclipse.ui.internal.navigator.resources.actions.ResourceMgmtActionProvider.fillActionBars(ResourceMgmtActionProvider.java:91)
      at org.eclipse.ui.navigator.NavigatorActionService.fillActionBars(NavigatorActionService.java:257)
      at org.eclipse.ui.navigator.CommonNavigatorManager.selectionChanged(CommonNavigatorManager.java:221)
      at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:148)
      at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1668)
      at org.eclipse.ui.navigator.CommonViewer.setSelection(CommonViewer.java:393)
      at org.eclipse.ui.navigator.CommonNavigator.selectReveal(CommonNavigator.java:387)
      at org.eclipse.ui.internal.navigator.actions.LinkEditorAction$2$1.run(LinkEditorAction.java:104)
      at org.eclipse.ui.internal.navigator.actions.LinkEditorAction$2.runInUIThread(LinkEditorAction.java:93)
      at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
      ... SWT event loop ...

````
