### ISSUE TITLE
[mac] GlobalTemplateVariablesDateTest failed on 2024-12-29

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#2649]
As seen here:

https://github.com/eclipse-platform/eclipse.platform.ui/runs/34961236510

the test currently as of today fails with

```
expected:<Today is 202[5]-12-29!> but was:<Today is 202[4]-12-29!>
org.junit.ComparisonFailure: expected:<Today is 202[5]-12-29!> but was:<Today is 202[4]-12-29!>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.eclipse.text.tests.templates.GlobalTemplateVariablesDateTest.assertBufferStringAndVariables(GlobalTemplateVariablesDateTest.java:137)
	at org.eclipse.text.tests.templates.GlobalTemplateVariablesDateTest.testInvalidLocale(GlobalTemplateVariablesDateTest.java:126)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by jukzi** [comment]
Was also reported on IBuild I20241229 for both Mac Builds but not windows/linux:

https://download.eclipse.org/eclipse/downloads/drops4/I20241229-1800/testresults/html/org.eclipse.text.tests_ep435I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html
https://download.eclipse.org/eclipse/downloads/drops4/I20241229-1800/testresults/html/org.eclipse.text.tests_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

jdk-21.0.5+11

**Comment by jukzi** [comment]
i filed a upstream bug to https://bugreport.java.com/bugreport

**Comment by jukzi** [comment]
see also https://technology.blog.gov.uk/2021/03/24/how-we-fixed-a-strange-week-year-bug/

**Comment by jukzi** [comment]
Not an Issue of the OS but an issue of Locale. YYYY is a locale depending `week year`, while yyyy would be the intended year.

**Comment by BeckerWdf** [comment]
> see also https://technology.blog.gov.uk/2021/03/24/how-we-fixed-a-strange-week-year-bug/

Wow. That's crazy complex.

**Comment by jukzi** [comment]
https://bugs.openjdk.org/browse/JDK-8346991
