### ISSUE TITLE
java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#355]
sometimes
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1441)
	at org.eclipse.jface.viewers.ViewerComparator.sort(ViewerComparator.java:206)
	at org.eclipse.ui.internal.progress.ProgressManagerUtil$ProgressViewerComparator.sort(ProgressManagerUtil.java:88)
	at org.eclipse.ui.internal.progress.DetailedProgressViewer.add(DetailedProgressViewer.java:180)

```

I guess this is because org.eclipse.ui.internal.progress.JobInfo.compareTo(JobTreeElement) compares getJob().getState() which might change concurrently.
It would only make sense to sort elements that are not undergoing changes while sorting..

**Comment by iloveeclipse** [comment]
There are two new test fails on all platforms, see
``` 
class org.eclipse.ui.tests.progress.ExtendedJobInfo cannot be cast to class java.lang.Comparable (org.eclipse.ui.tests.progress.ExtendedJobInfo is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @70d631d1; java.lang.Comparable is in module java.base of loader 'bootstrap')

java.lang.ClassCastException: class org.eclipse.ui.tests.progress.ExtendedJobInfo cannot be cast to class java.lang.Comparable (org.eclipse.ui.tests.progress.ExtendedJobInfo is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @70d631d1; java.lang.Comparable is in module java.base of loader 'bootstrap')
at java.base/java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
at java.base/java.util.Arrays.sort(Arrays.java:1315)
at java.base/java.util.Arrays.sort(Arrays.java:1509)
at java.base/java.util.ArrayList.sort(ArrayList.java:1749)
at org.eclipse.ui.tests.progress.JobInfoTestOrdering.testJobPriorityOrdering(JobInfoTestOrdering.java:116)
```

https://download.eclipse.org/eclipse/downloads/drops4/I20220923-1800/testresults/html/org.eclipse.ui.tests_ep426I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

**Comment by jukzi** [comment]
Thanks, Andrey, i will look into it.
