### ISSUE TITLE
Bug 371586: broken comparator. MarkerCategory

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#359]
```
Bug 371586: broken comparator. MarkerCategory [name=Errors, severity=-1, start=0, end=1322], fields: [Path (org.eclipse.ui.internal.views.markers.MarkerPathField), Description (org.eclipse.ui.internal.views.markers.MarkerProblemSeverityAndMessageField), Resource (org.eclipse.ui.internal.views.markers.MarkerResourceField), Location (org.eclipse.ui.internal.views.markers.MarkerLocationField), ID (org.eclipse.ui.internal.views.markers.MarkerIDField), Creation Time (org.eclipse.ui.internal.views.markers.MarkerCreationTimeField), Type (org.eclipse.ui.internal.views.markers.MarkerTypeField)]

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at org.eclipse.ui.internal.views.markers.MarkerSortUtil.sortStartingKElement(MarkerSortUtil.java:332)
	at org.eclipse.ui.internal.views.markers.Markers.sortMarkerEntries(Markers.java:168)
	at org.eclipse.ui.internal.views.markers.Markers.sortAndMakeCategories(Markers.java:139)
	at org.eclipse.ui.internal.views.markers.Markers.updateWithNewMarkers(Markers.java:103)
	at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.processMarkerEntries(MarkerUpdateJob.java:128)
	at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.buildMarkers(MarkerUpdateJob.java:82)
	at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.run(MarkerUpdateJob.java:54)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

eclipse.buildId=4.24.0.I20220607-0700
java.version=11.0.16.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE

**Comment by jukzi** [comment]
suspected rootcause: workspace changes which always can run in parallel and change marker
https://bugs.eclipse.org/bugs/show_bug.cgi?id=371586#c4

A possible solution would be to take a snapshot before sorting like 
https://github.com/eclipse-platform/eclipse.platform.ui/issues/355

**Comment by jukzi** [comment]
happend again while sorting many sonarlint results by description descending

Bug 371586: broken comparator. null, fields: [Description (org.sonarlint.eclipse.ui.internal.views.issues.IssueDescriptionField), Resource (org.eclipse.ui.internal.views.markers.MarkerResourceField), Path (org.eclipse.ui.internal.views.markers.MarkerPathField), Date (org.sonarlint.eclipse.ui.internal.views.issues.CreationDateField), Rule key (org.sonarlint.eclipse.ui.internal.views.issues.IssueRuleKeyField), Server issue key (org.sonarlint.eclipse.ui.internal.views.issues.ServerIssueKeyField)]

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at org.eclipse.ui.internal.views.markers.MarkerSortUtil.sortStartingKElement(MarkerSortUtil.java:332)
	at org.eclipse.ui.internal.views.markers.MarkerSortUtil.sortStartingKElement(MarkerSortUtil.java:406)
	at org.eclipse.ui.internal.views.markers.Markers.sortMarkerEntries(Markers.java:178)
	at org.eclipse.ui.internal.views.markers.Markers.sortAndMakeCategories(Markers.java:139)
	at org.eclipse.ui.internal.views.markers.Markers.updateWithNewMarkers(Markers.java:103)
	at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.processMarkerEntries(MarkerUpdateJob.java:128)
	at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.buildMarkers(MarkerUpdateJob.java:82)
	at org.eclipse.ui.internal.views.markers.MarkerUpdateJob.run(MarkerUpdateJob.java:54)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/65efd90a-2aee-49b1-a709-6c8d72e8ecae)

**Comment by iloveeclipse** [comment]
It's most likely custom org.sonarlint "Field" implementations that are not stable during sort.

**Comment by jukzi** [comment]
closing as non-eclipse (most likely `org.sonarlint.eclipse.ui.internal.views.issues.IssueDescriptionField` )
https://github.com/SonarSource/sonarlint-eclipse/blob/0656c3581d08ca0ad22a19aa1b256f86abfd3067/org.sonarlint.eclipse.ui/src/org/sonarlint/eclipse/ui/internal/views/issues/IssueDescriptionField.java#L39
