### ISSUE TITLE
AssertionFailedException: unknown saveable

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#366]
Don't know how to reproduce. i had an java editor and a compare with previous revision editor open.
```
org.eclipse.core.runtime.AssertionFailedException: unknown saveable: org.eclipse.egit.ui.internal.revision.GitCompareFileRevisionEditorInput$InternalResourceSaveableComparison@4f85b272 from part: org.eclipse.compare.internal.CompareEditor@507e4e19
	at org.eclipse.ui.internal.SaveablesList.logWarning(SaveablesList.java:300)
	at org.eclipse.ui.internal.SaveablesList.removeModel(SaveablesList.java:283)
	at org.eclipse.ui.internal.SaveablesList.removeModels(SaveablesList.java:381)
	at org.eclipse.ui.internal.SaveablesList.handleLifecycleEvent(SaveablesList.java:351)
	at org.eclipse.compare.internal.CompareEditor.handleLifecycleEvent(CompareEditor.java:734)
	at org.eclipse.egit.ui.internal.revision.GitCompareFileRevisionEditorInput$InternalResourceSaveableComparison.registerSaveable(GitCompareFileRevisionEditorInput.java:621)
	at org.eclipse.egit.ui.internal.revision.GitCompareFileRevisionEditorInput$InternalResourceSaveableComparison.handleDocumentConnected(GitCompareFileRevisionEditorInput.java:608)
	at org.eclipse.team.internal.ui.synchronize.LocalResourceTypedElement$1.handleDocumentConnected(LocalResourceTypedElement.java:150)
	at org.eclipse.team.internal.ui.synchronize.EditableSharedDocumentAdapter.connect(EditableSharedDocumentAdapter.java:95)
	at org.eclipse.compare.structuremergeviewer.StructureCreator.internalCreateStructure(StructureCreator.java:115)
	at org.eclipse.compare.structuremergeviewer.StructureCreator.lambda$0(StructureCreator.java:94)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.compare.internal.Utilities.runInUIThread(Utilities.java:805)
	at org.eclipse.compare.structuremergeviewer.StructureCreator.createStructure(StructureCreator.java:99)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$StructureInfo.createStructure(StructureDiffViewer.java:163)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$StructureInfo.refresh(StructureDiffViewer.java:141)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer$StructureInfo.setInput(StructureDiffViewer.java:112)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.compareInputChanged(StructureDiffViewer.java:350)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.lambda$1(StructureDiffViewer.java:88)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.lambda$4(StructureDiffViewer.java:326)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:74)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.compareInputChanged(StructureDiffViewer.java:324)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.compareInputChanged(StructureDiffViewer.java:312)
	at org.eclipse.jdt.internal.ui.compare.JavaStructureDiffViewer.compareInputChanged(JavaStructureDiffViewer.java:168)
	at org.eclipse.compare.structuremergeviewer.StructureDiffViewer.inputChanged(StructureDiffViewer.java:281)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.jface.viewers.StructuredViewer.setInput(StructuredViewer.java:1632)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:268)
	at org.eclipse.compare.internal.CompareStructureViewerSwitchingPane.setInput(CompareStructureViewerSwitchingPane.java:140)
	at org.eclipse.compare.CompareEditorInput.feedInput(CompareEditorInput.java:716)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:543)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:448)
	at org.eclipse.compare.internal.CompareEditor$1.lambda$0(CompareEditor.java:366)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4043)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3648)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

```

eclipse.buildId=4.24.0.I20220607-0700
java.version=11.0.16.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE

**Comment by jukzi** [comment]
was introduced with "Fix for  Bug 303795 -  compatibility: Compare editor hits NPE because of missing SaveablesLifecycleListener"
https://bugs.eclipse.org/bugs/show_bug.cgi?id=303795

**Comment by jukzi** [comment]
logged at the same instance: "Saveable ExecuteScriptJob.java was not added using a saveables lifecycle event."

**Comment by jukzi** [comment]
closing as not planned
