### ISSUE TITLE
AssertionFailedError logged during IResourceChangeListenerTest.testRefreshOtherProjectDuringRefresh()

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#368]
Exception is not thrown in the testing thread so the Test does not fail, but reproducible logs

https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/ep426I-unit-win32-java11_win32.win32.x86_64_11/org.eclipse.core.tests.resources.AutomatedTests.txt
```
junit.framework.AssertionFailedError: 4.0
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:223)
	at org.eclipse.core.tests.resources.IResourceChangeListenerTest$1Listener2.resourceChanged(IResourceChangeListenerTest.java:893)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:279)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:383)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1572)
	at org.eclipse.core.tests.resources.IResourceChangeListenerTest$3Listener1$1.run(IResourceChangeListenerTest.java:871)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by HeikoKlare** [comment]
In addition to the mentioned one, there are multiple assertions in this test class placed within listeners, thus not throwing exceptions in the testing thread. They will never lead to failing tests but only output log messages in case of regressions.

I suggest to fix the assertions along with the actual error in the test leading to the log message, so that the tests give reasonable feedback in case of regressions of the tested class. I will gladly propose a PR fixing these test issues.

@jukzi Could you please move this issue to the `eclipse.platform` repository? The test and tested class are placed there, so we could link to the issue within the proper repository.
