### ISSUE TITLE
[Tests] Random failing ProgressContantsTest.testKeepOneProperty

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.ui#370]
org.eclipse.ui.tests.progress.ProgressContantsTest.testKeepOneProperty fails in the I-build [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800) on [Windows ](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.ui.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html) and [MacM1](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.ui.tests_ep426I-unit-macM1-java17_macosx.cocoa.aarch64_17.html) with the below error

```
Only one finished job should be kept in view expected:<1> but was:<20>

junit.framework.AssertionFailedError: Only one finished job should be kept in view expected:<1> but was:<20>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.ui.tests.progress.ProgressContantsTest.testKeepOneProperty(ProgressContantsTest.java:259) 
```

**Comment by jukzi** [comment]
i can reproduce this error locally

**Comment by jukzi** [comment]
i can still reproduce this error when reverting eclipse.platform to 149a08f433580abfecff3a9cbf73250638133aa8 (2022-09-05) - before the JobManager.join changes!

**Comment by jukzi** [comment]
i can still reproduce this error when reverting eclipse.platform.ui to 180c5b6b70f00a875dfb2da6271e4bf7948d42ea (2022-09-21) - before my ui changes.

**Comment by iloveeclipse** [comment]
Unfortunately I can't reproduce on Linux, may be that is Windows specific.

> i can still reproduce this error when reverting eclipse.platform.ui to https://github.com/eclipse-platform/eclipse.platform.ui/commit/180c5b6b70f00a875dfb2da6271e4bf7948d42ea (2022-09-21) - before my ui changes.

OK, so that could be unrelated. The problem is that there is no one looking on Windows test fails, because there are too many of them, so it could be even already in 4.25.

**Comment by jukzi** [comment]
I can not reproduce it every time. it fails only like every 2nd time. When i revert my "fix #307: Progress View sometimes shows short living jobs twice" (2022-09-01) it fails far less often - but still sometimes with the same error.

**Comment by jukzi** [comment]
it also fails with https://github.com/eclipse-platform/eclipse.platform/pull/188

**Comment by jukzi** [comment]
That was a timing issue that became more visible by the changed timing behavior. In DetailedProgressViewer.remove(JobTreeElement...) doFindItem returned null even though the element was already added.

**Comment by HeikoKlare** [comment]
Test still fails randomly, see https://github.com/eclipse-platform/eclipse.platform.ui/pull/1148/checks?check_run_id=16996362086

**Comment by jukzi** [comment]
failed VerificationBuild on MacOs:
https://github.com/eclipse-platform/eclipse.platform.ui/pull/2565/checks?check_run_id=33787332251

**Comment by laeubi** [comment]
I also se this test failing, but this time it complains that 0 Jobs are running.
