### ISSUE TITLE
[Tests] ChooseWorkspaceDialogTests.testFilterDuplicatedPaths fails on Windows in the I-Build

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.ui#372]
The test org.eclipse.ui.internal.ide.ChooseWorkspaceDialogTests.testFilterDuplicatedPaths failed on [windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.ui.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html) with the below error

```
Non-unique paths were not filtered as expected expected:<[some/location1/, /some/location1/, /some/location2/]> but was:<[some/location1/, /some/location1/, /some/location1, /some/location2/, /some///location1, //some//location1//]>

java.lang.AssertionError: Non-unique paths were not filtered as expected expected:<[some/location1/, /some/location1/, /some/location2/]> but was:<[some/location1/, /some/location1/, /some/location1, /some/location2/, /some///location1, //some//location1//]>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.eclipse.ui.internal.ide.ChooseWorkspaceDialogTests.testFilterDuplicatedPaths(ChooseWorkspaceDialogTests.java:47) 
```

**Comment by iloveeclipse** [comment]
Regression from 45bd35d99895f65a8b9dca2d73cb4d816a7faaf2
