### ISSUE TITLE
e4.ui.tests.css.core DNF since 2022-10-14

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#415]
since https://download.eclipse.org/eclipse/downloads/drops4/I20221014-1800/testResults.php
tests for e4.ui.tests.css.core are not executed.

```
ENTRY org.eclipse.osgi 4 0 2022-10-16 20:05:31.242
!MESSAGE Application error
!STACK 1
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-platform-suite' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.eclipse.test.EclipseTestRunner.runTests(EclipseTestRunner.java:226)
	at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:202)
	at org.eclipse.test.CoreTestApplication.runTests(CoreTestApplication.java:52)
	at org.eclipse.test.CoreTestApplication.run(CoreTestApplication.java:35)
	at org.eclipse.test.CoreTestApplication.start(CoreTestApplication.java:43)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
	at org.eclipse.core.launcher.Main.main(Main.java:44)
Caused by: org.junit.platform.commons.PreconditionViolationException: Cannot create SuiteLauncher without at least one other TestEngine; consider adding an engine implementation JAR to the classpath
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:314)
	at org.junit.platform.suite.engine.SuiteLauncher.<init>(SuiteLauncher.java:46)
	at org.junit.platform.suite.engine.SuiteLauncher.create(SuiteLauncher.java:42)
	at org.junit.platform.suite.engine.SuiteTestDescriptor.discover(SuiteTestDescriptor.java:119)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.platform.suite.engine.DiscoverySelectorResolver.discoverSuites(DiscoverySelectorResolver.java:36)
	at org.junit.platform.suite.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:42)
	at org.junit.platform.suite.engine.SuiteTestEngine.discover(SuiteTestEngine.java:58)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 26 more

```

@akurtakov can this be related to "Update tycho-build to 3.0.0"?

**Comment by akurtakov** [comment]
No, these tests have been silently ignored for couple of releases already . E.g. https://download.eclipse.org/eclipse/downloads/drops4/R-4.25-202208311800/testresults/html/org.eclipse.e4.ui.tests.css.core_ep425I-unit-win32-java11_win32.win32.x86_64_11.html showing nothing executed. With https://github.com/eclipse-platform/eclipse.platform.ui/commit/12a93a486e88fc05625aeb2091dd62021b11b0a9 I changed them so they no longer try to execute JUnit 5 tests via JUnit 4 which obviously didn't work. 
I'm trying to get this one fixed and IMHO it's better obviously failing than being silently ignored.

**Comment by akurtakov** [comment]
For the record - even 4.23 silently failing https://download.eclipse.org/eclipse/downloads/drops4/R-4.23-202203080310/testresults/html/org.eclipse.e4.ui.tests.css.core_ep423I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by akurtakov** [comment]
Also for broader knowledge - I-build tests are executed without tycho being involved at all in the running process. This happens via https://wiki.eclipse.org/Platform-releng/Eclipse_Test_Framework .

**Comment by jukzi** [comment]
Is this fail related?
https://github.com/eclipse-platform/eclipse.platform/actions/runs/3263781910/jobs/5363380945

` Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.1.0-SNAPSHOT:compile (default-compile) on project org.eclipse.e4.core.services: Compilation failure -> [Help 1]`

**Comment by laeubi** [comment]
```
09:09:10.680 [INFO] Compiling 34 source files to /home/runner/work/eclipse.platform/eclipse.platform/runtime/bundles/org.eclipse.e4.core.services/target/classes
Warning: 161 [WARNING] /home/runner/work/eclipse.platform/eclipse.platform/runtime/bundles/org.eclipse.e4.core.services/src/org/eclipse/e4/core/internal/services/MessageFactoryServiceImpl.java:[169] 
	} else if (!annotation.contributorURI().isEmpty()) {
	                       ^^^^^^^^^^^^^^^^
The method contributorURI() from the type Message has been deprecated since version 4.26 and marked for removal
Warning: 161 [WARNING] /home/runner/work/eclipse.platform/eclipse.platform/runtime/bundles/org.eclipse.e4.core.services/src/org/eclipse/e4/core/internal/services/MessageFactoryServiceImpl.java:[176] 
	annotation.contributorURI(), locale, rbProvider);
	           ^^^^^^^^^^^^^^^^
The method contributorURI() from the type Message has been deprecated since version 4.26 and marked for removal
2 problems (2 warnings)
```
**error: warnings found and -failOnWarning specified**

**Comment by jukzi** [comment]
i.e. every commit that deprecated an API for removal should remove all calls to it?  @vogella

**Comment by laeubi** [comment]
> i.e. every commit that deprecated an API for removal should remove all calls to it? @vogella

Ideally yes, with **-failOnWarning** it seems mandatory.

**Comment by merks** [comment]
It seems to me that if it's only deprecated, clients might be using it and the framework should still support using that value.  

Is the suppression not properly respected?

![image](https://user-images.githubusercontent.com/208716/196145039-5142dc40-d5b5-4d63-bb2a-c6ac82ed861d.png)

**Comment by laeubi** [comment]
> It seems to me that if it's only deprecated, clients might be using it and the framework should still support using that value.

Using it is still supported ... The compiler emits a warning and that build is configured to treat warnings as errors.

**Comment by merks** [comment]
The `@SuppressWarnings("deprecation")` is supposed to suppress the warning.  In the IDE, ecj does that properly.  But I would expect **all** compilers to respect this standard annotation.  What am I missing?

**Comment by laeubi** [comment]
> The `@SuppressWarnings("deprecation")` is supposed to suppress the warning. In the IDE, ecj does that properly. But I would expect **all** compilers to respect this standard annotation. What am I missing?

At least here it is stated that a deprecation with `forRemoval=true`, the compiler generates a _removal_ warning instead of a _deprecation_ warning.

https://docs.oracle.com/javase/9/core/enhanced-deprecation1.htm#JSCOR-GUID-97A6BB09-6F7D-4ED0-BF53-22D40757B0B2

**Comment by merks** [comment]
I see!  You learn something new every day!!

So org.eclipse.e4.core.internal.services.MessageFactoryServiceImpl.createInstance(Locale, Class<M>, Message, ResourceBundleProvider)  should be like this:
```
	@SuppressWarnings({ "deprecation", "removal" })
	private <M> M createInstance(Locale locale, Class<M> messages, Message annotation,
			ResourceBundleProvider rbProvider) {
```

**Comment by laeubi** [comment]
Bust instead of suppress one better remove the deprecated reference, I think that why it is treated differently so you get warned even if you have previously suppressed the warning.

**Comment by akurtakov** [comment]
All the last comments seem totally unrelated to this isue. Would you please move them to another issue?

**Comment by merks** [comment]
It seems things digressed after this unanswered question:

https://github.com/eclipse-platform/eclipse.platform.ui/issues/415#issuecomment-1280539507

**Comment by akurtakov** [comment]
> Is this fail related? https://github.com/eclipse-platform/eclipse.platform/actions/runs/3263781910/jobs/5363380945
> 
> ` Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.1.0-SNAPSHOT:compile (default-compile) on project org.eclipse.e4.core.services: Compilation failure -> [Help 1]`

No relations I can see.

**Comment by jukzi** [comment]
> I'm trying to get this one fixed and IMHO it's better obviously failing than being silently ignored.

To be used to see failing tests distracts from new errors.

**Comment by akurtakov** [comment]
I agree with you and do as much as I can to have the builds clean. Just ignoring failures so they are not reported is not the answer either. What we need is more people helping with this kind of work but unfortunately there aren't many volunteers.

**Comment by merks** [comment]
@akurtakov This test runs fine for me locally.  How could I help here?  I.e., how to even reproduce such a problem?

**Comment by akurtakov** [comment]
One has to run them using EclipseTestRunner (https://github.com/eclipse-platform/eclipse.platform.releng/blob/master/bundles/org.eclipse.test/src/org/eclipse/test/EclipseTestRunner.java ) as this is the way I-build starts tests. 
Having Eclipse application launch configuration running org.eclipse.test.uitestapplicatoin with both org.eclipse.test and org.eclipse.e4.ui.tests.css.core in workspace and arguments ```-testpluginname org.eclipse.e4.ui.tests.css.core -classname org.eclipse.e4.ui.tests.css.core.CssCoreTestSuite -consoleLog``` is how I managed to debug it last time I checked.
It failed with the very same error as it fails in I-build and visible at https://download.eclipse.org/eclipse/downloads/drops4/I20221103-1800/testresults/ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17/org.eclipse.e4.ui.tests.css.core.CssCoreTestSuite.txt . 
I didn't manage to investigate it further since figuring how to actually being able to debug it.

**Comment by merks** [comment]
@akurtakov Before I dig deeper, might it be the case that it's failing because of the removal of "public"?

![image](https://user-images.githubusercontent.com/208716/199929110-58fb5eb8-a00f-441b-b3ad-162d1c71b3e1.png)

**Comment by akurtakov** [comment]
No, from https://junit.org/junit5/docs/snapshot/user-guide/ "Test classes, test methods, and lifecycle methods are not required to be public, but they must not be private." 
The issue with discovery of junit-platform-suite engine not finding out additional engine to use to actually run the tests.  Jupiter  in this case is on the classpath but for some reason not found.

**Comment by merks** [comment]
Okay, yes, matches what I see looking at the stack trace in the logs...

**Comment by merks** [comment]
@akurtakov 

I could not reproduce the problem locally but debugging I noticed that at this point, my stack diverges from the stack trace in the log.  Here's the debug stack:

![image](https://user-images.githubusercontent.com/208716/199940114-aa37fb69-9bbf-43f4-bb1f-3b5adc468864.png)

versus the log:
```
	at org.junit.platform.suite.engine.SuiteTestEngine.discover(SuiteTestEngine.java:58)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
```

So I tried disabling bundle that provides that class:

![image](https://user-images.githubusercontent.com/208716/199940682-69b90448-b60d-464f-af9c-13df330b12f0.png)

That shows a constraint violation:

![image](https://user-images.githubusercontent.com/208716/199941240-70ba54f5-5b1f-4895-83b8-a61bb0d6e0e9.png)

But then I do see a stack trace very similar to what's in the build logs:

```
org.junit.platform.commons.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath
	at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:314)
	at org.junit.platform.launcher.core.DefaultLauncher.<init>(DefaultLauncher.java:55)
	at org.junit.platform.launcher.core.LauncherFactory.createDefaultLauncher(LauncherFactory.java:134)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
	at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:109)
	at org.eclipse.test.EclipseTestRunner.runTests(EclipseTestRunner.java:212)
	at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:194)
	at org.eclipse.test.UITestApplication.lambda$0(UITestApplication.java:102)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$1(E4Testable.java:127)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3984)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3600)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.test.UITestApplication.run(UITestApplication.java:48)
	at org.eclipse.test.UITestApplication.start(UITestApplication.java:117)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

So my sense is that junit-jupiter-engine is not available (has not been installed or fails to start)...

Maybe one thing to try is to add an explicit bundle dependency on that in the test's MANIFEST.MF.  What do you think?  Does any other theory for what's wrong  strike you from this observation?  Something else I should try?

**Comment by akurtakov** [comment]
I have tried adding pretty much everything junit* to the test manifest without success. Unfortunately, I don't know much more on the topic than what I already shared.

**Comment by mickaelistria** [comment]
I can reproduce the failure with steps described in https://github.com/eclipse-platform/eclipse.platform.ui/issues/415#issuecomment-1303117694 .

**Comment by merks** [comment]
> I can reproduce the failure with steps described in [#415 (comment)](https://github.com/eclipse-platform/eclipse.platform.ui/issues/415#issuecomment-1303117694) .

@mickaelistria  Did you see this strange failure?

https://github.com/eclipse-platform/eclipse.platform.ui/pull/437#issuecomment-1303274486

**Comment by mickaelistria** [comment]
@merks I didn't try with Maven, I'm running it directly using the coretestapplication via a launch configuration. I think we should avoid surefire and all that stuff at the moment, because it's mostly unrelated and adding some more layers.

I debugged and can see that `new ServiceLoaderTestEngineRegistry().loadTestEngines()` in JUnit's `SuiteLauncher.create()` doesn't detect any test engine; although it's using the test bundle classloader. I'm not very familiar with the ServiceLoader, but it could be that some specific configuration is requested for it to work with OSGi. Maybe we should even feed the ServiceLoader directly witht the desired service definition (would be the JupiterEngine here).

**Comment by merks** [comment]
@mickaelistria Yes indeed, the surefire failure also suggests some type of class loading issue also related to the service loader which does seem to be the root of the problem with the test runner launches...

**Comment by mickaelistria** [comment]
Looks like we're in a case where ServiceLoader doesn't work in OSGi because JUnit doesn't declare the capability/requirement in its MANIFEST.
@tjwatson is https://blog.osgi.org/2013/02/javautilserviceloader-in-osgi.html still relevant? Is there an existing setting in the container to auto-register services during bundle installation or activation so ServiceLoader can work without having to modifyupstream jars?

**Comment by merks** [comment]
@mickaelistria

At this point in the code it should create a class loader capable of loading any of the engines and set it into the thread's context:

![image](https://user-images.githubusercontent.com/208716/199981295-d22a8f27-711a-478d-a785-11413729469e.png)

It should find the engines using OSGi lookup like this:

![image](https://user-images.githubusercontent.com/208716/199982107-e3a9df77-e7dd-41eb-b9f6-be51df54054a.png)

The test service loader should (and does) use that class loader which lists the jupiter engine bundle:

![image](https://user-images.githubusercontent.com/208716/199982545-6f259b8f-84b3-4930-9536-f81545f7198a.png)

That how it works at my end and why it works....

So looking at org.eclipse.test.EclipseTestRunner.getPlatformEngines() to see if it's finding the service, which definitely exists, might help shed further light on the problem:

![image](https://user-images.githubusercontent.com/208716/199983339-74a12207-ec05-4506-993c-2777ec345940.png)

**Comment by mickaelistria** [comment]
It's not really a problem of classloader; I believe the right ones are used (or almost the right one). It's a problem that ServiceLoader can only work well with ModuleLoader or with some LazyClassPathLookupIterator (which calls getResource on the classloader), and the OSGi loader doesn't have access to the resource of the dependencies or other bundles.
So when the ServiceLoader calls `classloader.getResource("META-INF/services/org.junit.platform.engine.TestEngine` transitively from the SuiteLauncher, it then finds nothing in the provided bundle classloader. The bundle can be augmented to re-define this service internally -just like Tycho does more or less- but then it reveals that the EclipseTestRunner just creates another classloader to wraps the default bundle one and that leads to the returned class not being a match (same .class file and name, but loaded from a different classloader; so actually not same class). I'm looking at whether the usual bundle classloader can be used instead of the wrapper. If this can work, it will help fixing this issue, and others.

**Comment by mickaelistria** [comment]
1 part of the fix is https://github.com/mickaelistria/eclipse.platform.ui/pull/new/declare-jupiter-engine (so service is now known to this classloader);
another part of the fix is https://github.com/eclipse-platform/eclipse.platform.releng/pull/145 which makes that the actual bundle classloader is used in order to load test classes.

**Comment by mickaelistria** [comment]
I've pushed a new version of https://github.com/eclipse-platform/eclipse.platform.releng/pull/145 which makes specific changes in the tests useless.
The trick is to inject JUnit content in the contextClassLoader, but keeping the current bundle classloader as priority.

**Comment by mickaelistria** [comment]
And everything is now working! https://download.eclipse.org/eclipse/downloads/drops4/I20221104-1200/testresults/html/org.eclipse.e4.ui.tests.css.core_ep426I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
