### ISSUE TITLE
Eclipse "Refreshing Workspace" forever, blocking any other actions

### ISSUE THREAD

**Issue by davidmichaelkarr** [eclipse-platform/eclipse.platform.ui#483]
I installed 2022-12 today, and I went through the same steps that I do for every release:
* Export preferences and mylyn task list from existing instance
* Install new version
* Launch new version
* Import preferences and task list
* Install plugins (spring, decompiler, emacs+, bash, MoreUnit, Spotbugs, Docker Tooling)
* Show Git Repositories View, which shows the same repositories as the previous version
* Start importing projects

When I start importing projects, Eclipse starts building projects, and this whole process takes quite a while, but it eventually completes.  I open the Progress View to watch it.

Now, with 2022-12, it appears to be "stuck" in this process, and I have to restart Eclipse to get it to resume. In fact, I can't even exit Eclipse normally. I have to kill the process.

It gets stuck on a "Refreshing Workspace" action in the Progress View.  I've even tried clicking the "Stop" box, and it goes into "Cancel Requested", but it never stops.

I did notice that the status area in the bottom right refers to "Classpath Actions", I believe, and that never goes away.

I looked at the Eclipse log after I killed the process, and it showed this:
```
!MESSAGE TimeoutException
!STACK 0
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at org.springframework.tooling.ls.eclipse.commons.LSP4ECommandExecutor.executeClientCommand(LSP4ECommandExecutor.java:37)
	at org.springframework.tooling.jdt.ls.commons.classpath.SendClasspathNotificationsJob.flush(SendClasspathNotificationsJob.java:178)
	at org.springframework.tooling.jdt.ls.commons.classpath.SendClasspathNotificationsJob.run(SendClasspathNotificationsJob.java:149)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.moreunit 4 0 2022-12-09 17:11:20.645
!MESSAGE java.lang.IllegalArgumentException: Compilation unit name must end with .java, or one of the registered Java-like extensions
	at org.eclipse.jdt.internal.core.PackageFragment.getCompilationUnit(PackageFragment.java:289)
	at org.eclipse.jdt.internal.core.JavaModelManager.createCompilationUnitFrom(JavaModelManager.java:1104)
	at org.eclipse.jdt.core.JavaCore.createCompilationUnitFrom(JavaCore.java:3762)
	at org.moreunit.elements.EditorPartFacade.getCompilationUnit(EditorPartFacade.java:52)
	at org.moreunit.annotation.MoreUnitAnnotationModel$1.run(MoreUnitAnnotationModel.java:185)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I included both traces to be sure, but I'm pretty sure that the second one is not important.

This process of importing all of my existing repositories required two additional restarts like this, as it got stuck twice in the same way.
![image](https://user-images.githubusercontent.com/5566419/206822104-82ce0e90-463b-4aab-bbae-6324e84325a4.png)
![image](https://user-images.githubusercontent.com/5566419/206822108-b3f7385a-f15c-4dd3-999a-df49dd5638e2.png)

**Comment by mickaelistria** [comment]
The issue seems to involve STS and MoreUnit. Please reach out to there support first; or please provide steps to reproduce with plain Eclipse SDK.
