### ISSUE TITLE
Use ctrl+e Quick Switch Editor to report java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by lyh061619** [eclipse-platform/eclipse.platform.ui#487]
at work Use ctrl+e Quick Switch Editor to report Error executing 'org.eclipse.ui.window.openEditorDropDown': java.lang.IllegalArgumentException

os:
windows 10

eclipse version:
4.26.0.20221201-1200

Installed plug-ins:
![20221215085531](https://user-images.githubusercontent.com/15118571/207747340-6a9fd675-e5d1-4c18-b4a9-f956b338ffea.png)

![20221214224215](https://user-images.githubusercontent.com/15118571/207744523-292566b2-dca6-415a-be34-198700510fbb.png)

I tried to delete the workspace and the reconstruction problem still exists,
The abnormal information is as follows:

!ENTRY org.eclipse.e4.ui.workbench 4 0 2022-12-14 22:17:10.891
!MESSAGE Execution exception for: ParameterizedCommand(Command(org.eclipse.ui.window.openEditorDropDown,Quick Switch Editor,
		Open the editor drop down list,
		Category(org.eclipse.ui.category.window,Window,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.window.openEditorDropDown"),
		,,true),null) in 
	context chain: WorkbenchContext -> TrimmedWindowImpl (IDEWindow) Context -> PerspectiveImpl (org.eclipse.debug.ui.DebugPerspective) Context -> PartImpl (org.eclipse.e4.ui.compatibility.editor)  removeOnHide org.eclipse.m2e.editor.MavenPomEditorContext -> MultiPageEditorSite (org.eclipse.ui.internal.genericeditor.ExtensionBasedTextEditor)
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'org.eclipse.ui.window.openEditorDropDown': java.lang.IllegalArgumentException
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:308)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:580)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:647)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:439)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:96)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1286)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1065)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1594)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4865)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:345)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4743)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3640)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.openWizardDialog(AbstractMarketplaceWizardCommand.java:146)
	at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.execute(AbstractMarketplaceWizardCommand.java:73)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4256)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3642)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.IllegalArgumentException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 66 more
Caused by: java.lang.IllegalArgumentException
	at java.base/sun.nio.fs.WindowsPath.subpath(WindowsPath.java:701)
	at java.base/sun.nio.fs.WindowsPath.subpath(WindowsPath.java:42)
	at org.eclipse.ui.internal.WorkbookEditorsHandler.getPathSegment(WorkbookEditorsHandler.java:264)
	at org.eclipse.ui.internal.WorkbookEditorsHandler.generateLabelText(WorkbookEditorsHandler.java:247)
	at org.eclipse.ui.internal.WorkbookEditorsHandler.generateColumnLabelTexts(WorkbookEditorsHandler.java:215)
	at org.eclipse.ui.internal.WorkbookEditorsHandler.getInput(WorkbookEditorsHandler.java:111)
	at org.eclipse.ui.internal.FilteredTableBaseHandler.openDialog(FilteredTableBaseHandler.java:217)
	at org.eclipse.ui.internal.FilteredTableBaseHandler.execute(FilteredTableBaseHandler.java:131)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 70 more

**Comment by mickaelistria** [comment]
@lyh061619 Thanks for the report. Does it happen in case you have only a basic text editor open? I suspect not, if so can you try to identify which editors need to be open for this error to happen?
@fapdash Can you please investigate this? The stack seems to hint it's a regression from your recent development; probably a corner-case.

**Comment by fapdash** [comment]
@lyh061619 Can please you look at the list of open editors (Ctrl+3, enter "Editors")? There should be at least two editors that have the same title (same file / class name). Can you please post the absolute paths of those files?

@mickaelistria I'm investigating, the error definitely happens in the code that I contributed.

**Comment by fapdash** [comment]
I found one reproduction where one of the files with the same name is located in the root directory.
Eg. `C:\some\folder\file.txt` and `D:\file.txt` are opened in editor tabs and Quick Switch Editor is triggered.

@lyh061619 Could this be the way you are hitting the error or is this something different?

**Comment by lyh061619** [comment]
> @lyh061619 Thanks for the report. Does it happen in case you have only a basic text editor open? I suspect not, if so can you try to identify which editors need to be open for this error to happen? @fapdash Can you please investigate this? The stack seems to hint it's a regression from your recent development; probably a corner-case.

Yes, I have multiple editors. Now try to locate which editor is in trouble

**Comment by lyh061619** [comment]
@mickaelistria 
Yes, I open multiple editors and open a lot of files. Now all of them are closed (ctrl+e Use ctrl+e Quick Switch Editor can be used at present). However, I am still trying to reproduce to determine which editor is in trouble. Unfortunately, I cannot reproduce successfully

**Comment by harawata** [comment]
In my case, it happens when I split the editor (Window > Editor > Toggle Split Editor).
Split editors are listed as two editors with the same name.

**Comment by fapdash** [comment]
@harawata Edit: I managed to reproduce it, thank you for your report!

**Comment by harawata** [comment]
@fapdash ,

Here is the exact steps:

1. Downloaded eclipse-java-2022-12-R-macosx-cocoa-x86_64.dmg
2. Copy Eclipse.app to /Applications
3. Open Eclipse.app 
4. Create a new workspace in an empty folder
5. Create a new Java project with a name 'test'
6. Create a new Java class 'Test.java' in the package 'test'. -> Test.java is opened in a Java editor.
7. Press Cmd + E -> Editor list pops up
8. Choose Window > Editor > Toggle Split Editor (Horizontal)
9. Press Cmd + E -> No editor list (an exception is added in the Error Log)
10. Choose Window > Editor > Toggle Split Editor (Horizontal) -> Split cancelled
11. Press Cmd + E -> Editor list pops up

[EDIT] I just saw your comment updated. :D

**Comment by lyh061619** [comment]
@fapdash The file with the same name appears in the editor. I'm not sure this is caused by this problem. As mentioned above, when splitting the editing window vertically and horizontally, ctrl+e cannot be used, and the problem of splitting the editor window disappears. ctrl+e works normally

**Comment by fapdash** [comment]
@lyh061619 @harawata Okay, then it sounds to me that https://github.com/eclipse-platform/eclipse.platform.ui/pull/491 should fix your problem. Please have a look if you have the capacity.
As described [in the PR](https://github.com/eclipse-platform/eclipse.platform.ui/pull/491#issuecomment-1355986499) it would be possible to differentiate between the split editors in Ctrl+E but since I don't use this feature it would be great to have your input. :)

**Comment by lyh061619** [comment]
@fapdash Thank you for your timely handling ^_^

**Comment by harawata** [comment]
Thank you @fapdash !

I just did a quick test and Cmd+E worked even when I split the editor, so that's good.

As to the expected behavior, I personally expect one entry in the editor list even if the editor is split.
There probably is a good reason why split editors are listed independently and it does not bother me much, so I'm OK with the current behavior.

BTW, I noticed that "clone editor" command seems to cause the same (or similar) problem [1].
I've never used that command, so it's not a blocker issue for me. I just thought you should know.

[1] I assigned a shortcut key to the command for testing

**Comment by vogella** [comment]
Thanks @fapdash for the fix, @harawata please check in next I-build from https://download.eclipse.org/eclipse/downloads/

**Comment by harawata** [comment]
Hi @vogella ,

Thank you, but there still are corner cases, it seems.

1. Open a file, then clone the same editor twice (i.e. there are three editors opened for the same file)
2. Open a file and split the editor, then clone the editor (the order may not matter)

You should close all the other editors before testing.
The error does not occur if there is another editor opened for a different file with the same name.

The assumption made in the below comment may not always be valid.
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e998f9a4e30e323a58d3625ae8f85ae7862ab2ec/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/WorkbookEditorsHandler.java#L228-L242

**Comment by iloveeclipse** [comment]
Commit https://github.com/eclipse-platform/eclipse.platform.ui/commit/815e60e3d587c7f560422607d60a3dfe8175b82e introduces test fail on Windows

See https://download.eclipse.org/eclipse/downloads/drops4/I20221219-1800/testresults/html/org.eclipse.ui.tests_ep427I-unit-win32-java11_win32.win32.x86_64_11.html

```
Text should have folder prepended because of name clash expected:<...okEditorsHandlerTest[1]\example.txt> but was:<...okEditorsHandlerTest[2]\example.txt>

junit.framework.ComparisonFailure: Text should have folder prepended because of name clash expected:<...okEditorsHandlerTest[1]\example.txt> but was:<...okEditorsHandlerTest[2]\example.txt>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.TestCase.assertEquals(TestCase.java:253)
at org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest.testMultipleFilesWithNameCollisionAndEditorSplit(WorkbookEditorsHandlerTest.java:137)
```

**Comment by fapdash** [comment]
The test fails because in the test under Linux the order of the editors (MRU order) is different from the behavior under Windows.
Under Linux the editor order in the popup differs between the test run and a manual split through the UI. The test result under Windows is the behavior that I see when splitting an editor manually on Linux. In both cases the active editor is one of the split editors, but the previously active editor is not the same.
When I run the tests on Windows emulated through WINE the same discrepancy between tests and manual behavior happens.

This is the code loading the sorted references from the `activationList`:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/a537256520dfbfebc2c63895410cef5a47e39cf2/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/WorkbenchPage.java#L1083-L1090

The content of the `activationList` differs between the test run and the runtime Eclipse.
The activation list should contain the split editors but in the test under Linux it contains one split editor and one other editor.

The quick and dirty solution would be to rewrite that test so it doesn't verify the order of the editors in the Quick Switch Editor popup.

**Comment by mickaelistria** [comment]
Test is not failing any more.
