### ISSUE TITLE
org.eclipse.ui.tests.navigator.OpenTest | testNavigatorExtensionEnablement fails since I20230126-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#531]
- The last "successful" test was at I20230125-1800 https://download.eclipse.org/eclipse/downloads/drops4/I20230125-1800/testResults.php       
- The first failing is I20230126-1800 https://download.eclipse.org/eclipse/downloads/drops4/I20230126-1800/testResults.php

See
https://download.eclipse.org/eclipse/downloads/drops4/I20230126-1800/testresults/html/org.eclipse.ui.tests.navigator_ep427I-unit-win32-java17_win32.win32.x86_64_17.html
```
Graphic is disposed

org.eclipse.swt.SWTException: Graphic is disposed
at org.eclipse.swt.SWT.error(SWT.java:4918)
at org.eclipse.swt.SWT.error(SWT.java:4833)
at org.eclipse.swt.SWT.error(SWT.java:4804)
at org.eclipse.swt.graphics.Image.getImageData(Image.java:1350)
at org.eclipse.swt.internal.ImageList.set(ImageList.java:372)
at org.eclipse.swt.internal.ImageList.add(ImageList.java:52)
at org.eclipse.swt.widgets.Tree.imageIndex(Tree.java:3749)
at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7524)
at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5797)
at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1961)
at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5365)
at org.eclipse.swt.widgets.Control.windowProc(Control.java:4799)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1576)
at org.eclipse.swt.widgets.Control.windowProc(Control.java:4844)
at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6142)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)
at org.eclipse.swt.internal.ole.win32.IAccessible.get_accRole(IAccessible.java:41)
at org.eclipse.swt.accessibility.Accessible.get_accRole(Accessible.java:2570)
at org.eclipse.swt.accessibility.Accessible$1.method13(Accessible.java:176)
at org.eclipse.swt.internal.ole.win32.COMObject.callback13(COMObject.java:183)
at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1576)
at org.eclipse.swt.widgets.Control.windowProc(Control.java:4844)
at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6142)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
at org.eclipse.swt.internal.win32.OS.SendMessage(Native Method)
at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7646)
at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5797)
at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1961)
at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5365)
at org.eclipse.swt.widgets.Control.windowProc(Control.java:4799)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1576)
at org.eclipse.swt.widgets.Control.windowProc(Control.java:4844)
at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6142)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5022)
at org.eclipse.swt.internal.win32.OS.SendMessage(Native Method)
at org.eclipse.swt.widgets.Tree.destroyItem(Tree.java:2658)
  at org.eclipse.swt.widgets.TreeItem.destroyWidget(TreeItem.java:310)
at org.eclipse.swt.widgets.Widget.release(Widget.java:831)
at org.eclipse.swt.widgets.Widget.dispose(Widget.java:428)
at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2730)
at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefreshStruct(AbstractTreeViewer.java:1971)
at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:684)
at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1947)
at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1904)
at org.eclipse.ui.navigator.CommonViewer.internalRefresh(CommonViewer.java:532)
at org.eclipse.jface.viewers.StructuredViewer.lambda$3(StructuredViewer.java:1482)
at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:365)
at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1482)
at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:538)
at org.eclipse.ui.navigator.CommonViewer.refresh(CommonViewer.java:352)
at org.eclipse.ui.navigator.CommonViewer.refresh(CommonViewer.java:495)
at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1418)
at org.eclipse.ui.tests.navigator.NavigatorTestBase.refreshViewer(NavigatorTestBase.java:308)
at org.eclipse.ui.tests.navigator.OpenTest.testNavigatorExtensionEnablement(OpenTest.java:72)
```

**Comment by iloveeclipse** [comment]
@SyntevoAlex , @jukzi : could also be a problem with `org.eclipse.swt.widgets.Tree` code (CC'ing you as yu both touched that area recently).

**Comment by SyntevoAlex** [comment]
According to my testing, this code path is only triggered if there's some kind of Accessibility program running on test machine.
That could be screen reader, automatic translation tool, etc - anything that tries to extract text from other programs.

I used [Accessibility Insights](https://accessibilityinsights.io/docs/windows/overview/), but it doesn't trigger this specific code path.

Here's a summary of the stack when the problem occurs:
```
org.eclipse.swt.SWTException: Graphic is disposed
at org.eclipse.swt.SWT.error(SWT.java:4804)
at org.eclipse.swt.graphics.Image.getImageData(Image.java:1350)
	Discovers that `Image` is disposed.
at org.eclipse.swt.internal.ImageList.set(ImageList.java:372)
at org.eclipse.swt.internal.ImageList.add(ImageList.java:52)
at org.eclipse.swt.widgets.Tree.imageIndex(Tree.java:3749)
at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7524)
	`TVN_GETDISPINFO` handler.
	Inspects `TreeItem.image`, which causes it to be inserted into image list.
	I understand that `TreeItem.image` is already disposed here.
<...>
at org.eclipse.swt.internal.ole.win32.IAccessible.get_accRole(IAccessible.java:41)
	Calls OS.
at org.eclipse.swt.accessibility.Accessible.get_accRole(Accessible.java:2570)
	Passes the request down to OS via `IAccessible.get_accRole`.
at org.eclipse.swt.accessibility.Accessible$1.method13(Accessible.java:176)
at org.eclipse.swt.internal.ole.win32.COMObject.callback13(COMObject.java:183)
<...>
at org.eclipse.swt.internal.win32.OS.SendMessage(Native Method)
at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7646)
	Old hack tries to restore selection, see `Tree.lockSelection`
	It calls `TVM_SETITEM` API from OS.
<...>
at org.eclipse.swt.internal.win32.OS.SendMessage(Native Method)
at org.eclipse.swt.widgets.Tree.destroyItem(Tree.java:2658)
at org.eclipse.swt.widgets.TreeItem.destroyWidget(TreeItem.java:310)
at org.eclipse.swt.widgets.Widget.release(Widget.java:831)
at org.eclipse.swt.widgets.Widget.dispose(Widget.java:428)
at org.eclipse.jface.viewers.AbstractTreeViewer.updateChildren(AbstractTreeViewer.java:2730)
<...>
```

A short summary:
1. Setting selection causes `Accessible.get_accRole()`.
   It's not reproducible for me, and I believe that it depends on actions of specific Accessibility tool.
2. Calling OS API `IAccessible.get_accRole()` triggers `TVN_GETDISPINFO`, I understand that item being deleted receives it.
3. I understand that `TreeItem.image` is disposed because item is being disposed.

I don't think that this is a new problem. Most likely, it surfaced now because some Accessibility tool was installed on test machine. @iloveeclipse can you find out which tool is that?

**Comment by SyntevoAlex** [comment]
I was using this test snippet in attempt to reproduce

```java
	static final int IMG_CX   = 16;
	static final int IMG_CY   = 16;
	static final Random random = new Random();

	static Image makeItemImage(Device device) {
		Image image = new Image(device, IMG_CX, IMG_CY);
		GC gc = new GC(image);
		gc.setBackground(new Color(random.nextInt(255),random.nextInt(255),random.nextInt(255)));
		gc.fillRectangle(0, 0, IMG_CX-1, IMG_CY-1);
		gc.drawRectangle(0, 0, IMG_CX-1, IMG_CY-1);
		gc.dispose();
		return image;
	}

	public static void main(String[] args) {
		final Display display = new Display();
		final Shell shell = new Shell(display);
		shell.setLayout (new GridLayout (1, true));

		Tree tree = new Tree(shell, SWT.MULTI);
		tree.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true));

		// This causes Tree to interact with Accessible.
		// The other way is to enable checkboxes.
		// See Tree#WM_GETOBJECT()
		tree.setHeaderVisible(true);

		for (int iItem = 0; iItem < 100; iItem++)
		{
			TreeItem item = new TreeItem(tree, 0);
			item.setText("Item #" + iItem);

			// The bug is about disposed images, so we need to have it
			item.setImage(makeItemImage(display));
		}

		Button button = new Button(shell, SWT.PUSH);
		button.setText("Test");
		button.addListener(SWT.Selection, e -> {
			TreeItem item = tree.getItem(tree.getItemCount() / 2);
			if ((tree.getSelectionCount() == 0) || (tree.getSelection()[0] != item)) {
				tree.deselectAll();
				tree.setSelection(item);
			} else {
				item.dispose();
			}
		});

		shell.setSize(200, 300);
		shell.open();

		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}

		display.dispose();
	}
```

**Comment by iloveeclipse** [comment]
> I don't think that this is a new problem. Most likely, it surfaced now because some Accessibility tool was installed on test machine. @iloveeclipse can you find out which tool is that?

Thanks Alex. I have no idea about accessibility related tools and especially what is installed on the Windows machine => I've created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2592.

If you have any concrete pointers for **what exactly** the admins should look for, it would simplify their job.

**Comment by SyntevoAlex** [comment]
Unfortunately I don't have any specific ideas. I would suggest to
1) Check any software that was installed/updates around first failure time
2) Log on to machine, run the test repeatedly and kill running programs one by one until test succeeds

**Comment by iloveeclipse** [comment]
OK, it seems that the "touch keyboard tool" or it's Polish accent confused tests :-)
After admins closed that tool and switched keyboard to english, the test seem to work again.

**Comment by SyntevoAlex** [comment]
It's not the tool that is guilty here, SWT does have a bug. Just in order to trigger this bug, very specific circumstances are needed.

Yet, unfortunately, I think that I need to focus on other issues, so I can't contribute a fix here.

**Comment by iloveeclipse** [comment]
That was clear, both points :-)
