### ISSUE TITLE
LockManager.handleException errors on shutdown

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#56]
I've seen now two times sporadic `LockManager.handleException` errors logged on shutdown of the IDE.

Looks some of the recent changes in UI/SWT area caused that, bugzilla never saw that error before.
First one was reported with  4.24.0.I20220504-0230 build, but that doesn't mean this was introduced there, because error is random (only if some workspace task runs at shutdown time).

Looks like the Display is now disposed earlier on shutdown?

Could be side effect of removing synchronization block from Display.isDisposed() via https://github.com/eclipse-platform/eclipse.platform.swt/issues/74 / https://github.com/eclipse-platform/eclipse.platform.swt/pull/75

Also could be a side effect of https://github.com/eclipse-platform/eclipse.platform.ui/issues/8.

Autobuild running during shutdown:
```
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1505)
	at org.eclipse.swt.widgets.Display.getThread(Display.java:3378)
	at org.eclipse.ui.internal.UILockListener.isUI(UILockListener.java:188)
	at org.eclipse.ui.internal.UILockListener.aboutToRelease(UILockListener.java:124)
	at org.eclipse.core.internal.jobs.LockManager.aboutToRelease(LockManager.java:88)
	at org.eclipse.core.internal.jobs.OrderedLock.doRelease(OrderedLock.java:189)
	at org.eclipse.core.internal.jobs.OrderedLock.release(OrderedLock.java:237)
	at org.eclipse.core.internal.resources.WorkManager.checkOut(WorkManager.java:167)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1523)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:176)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Same as above, but from refresh job
```
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1505)
	at org.eclipse.swt.widgets.Display.getThread(Display.java:3378)
	at org.eclipse.ui.internal.UILockListener.isUI(UILockListener.java:188)
	at org.eclipse.ui.internal.UILockListener.aboutToRelease(UILockListener.java:124)
	at org.eclipse.core.internal.jobs.LockManager.aboutToRelease(LockManager.java:88)
	at org.eclipse.core.internal.jobs.OrderedLock.doRelease(OrderedLock.java:189)
	at org.eclipse.core.internal.jobs.OrderedLock.release(OrderedLock.java:237)
	at org.eclipse.core.internal.resources.WorkManager.checkOut(WorkManager.java:167)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1523)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1579)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:219)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by laeubi** [comment]
I think this is a race condition here:

`return (!display.isDisposed()) && (display.getThread() == Thread.currentThread());`

so actually the disposed check here is a bit useless when we assume multithreading and maybe better a catch clause is used.

Beside that the check in `aboutToRelease` seems strange as it only clears out if the thread is an UI thread, but this is only true if `display.getThread() == Thread.currentThread()` so I think this could be simplified to

```
@Override
public void aboutToRelease() {
  if (ui == Thread.currentThread()) {
	  ui = null;
  }
}
```

**Comment by iloveeclipse** [comment]
Sure there is a race condition, but the errors I've reported weren't seen in last ~10 years...

**Comment by iloveeclipse** [comment]
> the check in aboutToRelease seems strange as it only clears out if the thread is an UI thread

This is intentionally, it only allows to release if the UI thread does it.

> so I think this could be simplified to

Yes, that can be done. PR?

**Comment by iloveeclipse** [comment]
My main concern here is less the errors mentioned (which should be for sure fixed), but that workbench shutdown behavior seem to be changed now.

If that is "expected", I would like to understand what exactly caused shutdown behavior change and if there are other possible side effects beside errors here (worst case: workbench or workspace states are not properly persisted etc).

**Comment by laeubi** [comment]
It *might* be that a Job is running but the test shuts down faster...

**Comment by iloveeclipse** [comment]
No, that was my main workspace, **not a test**. Just a regular shutdown in a workspace that I use every day.

**Comment by iloveeclipse** [comment]
This error is fixed now, but as expected we see now two other issues, unfortunately lacking stack traces: 
- https://github.com/eclipse-platform/eclipse.platform.resources/issues/114
- https://github.com/eclipse-platform/eclipse.platform.runtime/issues/50

I will keep this issue open to see what the stack traces added say.

**Comment by iloveeclipse** [comment]
Haven't seen that after recent changes, let assume we are fine now.
