### ISSUE TITLE
NPE when changing Eclipse theme

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.ui#60]
Steps to reproduce:

1. Start Eclipse
2. Preferences -> General -> Appearance -> Theme
3. Change from Light to Dark or vice versa
4. Apply and Close 
5. at this point most of the UI is updated, but then the "Restart for theme..." prompt comes up
6. Press restart and the below stack trace will appear numerous times.

I did this in Eclipse IDE for C/C++ 2022-06 M2. I'll report back shortly if it occurs in platform build.

```java
!ENTRY org.eclipse.jface 4 0 2022-05-05 17:40:47.496
!MESSAGE An error has occurred. See error log for more details.
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.handlers.IHandlerService.deactivateHandler(org.eclipse.ui.handlers.IHandlerActivation)" because "service" is null
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.close(FilteredPreferenceDialog.java:641)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.close(WorkbenchPreferenceDialog.java:125)
	at org.eclipse.jface.preference.PreferenceDialog$7.run(PreferenceDialog.java:927)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:889)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:461)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:233)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5798)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4481)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:414)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5798)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5029)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4481)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by jonahgraham** [comment]
Also fails with SDK for M2 (I20220428-1800) and with the 4.23 release version.

This is a regression in 4.23 compared to 4.22 and seems to be related to the change that uses this dialog (in 4.23):

![image](https://user-images.githubusercontent.com/679236/167031755-4d19c8ae-4347-4c54-96b0-89d40e0342fd.png)

vs this one in 4.22:

![image](https://user-images.githubusercontent.com/679236/167031591-9a3e16bf-5076-4be2-937f-ba84b4f30e8d.png)

Hopefully someone reading this recognizes this change and knows where to direct this bug.

**Comment by lshanmug** [comment]
The dialog was changed via bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=577476.
Adding @BeckerWdf

**Comment by BeckerWdf** [comment]
The error happens when the preference dialog is closed:

```
	@Override
	public boolean close() {
		if (showViewHandler != null) {
			IHandlerService service = PlatformUI.getWorkbench().getService(IHandlerService.class);
			service.deactivateHandler(showViewHandler);
			showViewHandler.getHandler().dispose();
			showViewHandler = null;
		}
...
	}
```

"service" is null in this case.
The cause seems to be that the restart is triggered while the dialog is open. Before the restart was triggered after the dialog was closed. So how should we fix this?
a) First close the dialog and then trigger the restart
b) Simply fix this NPE?

**Comment by laeubi** [comment]
What about asyncExec the restart? This should first close the dialog and then perform the restart...

**Comment by laeubi** [comment]
By the way regardless of the fix it might be good to check for null service return and give a better error message then running into NPE if the service is mandatory.

**Comment by BeckerWdf** [comment]
> By the way regardless of the fix it might be good to check for null service return and give a better error message then running into NPE if the service is mandatory.

But that would be another fix in another issue.
