### ISSUE TITLE
ConcurrentModificationException in FilteredResourcesSelectionDialog

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#645]
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at org.eclipse.ui.dialogs.FilteredResourcesSelectionDialog$1.compare(FilteredResourcesSelectionDialog.java:150)
	at org.eclipse.ui.dialogs.FilteredResourcesSelectionDialog$1.compare(FilteredResourcesSelectionDialog.java:1)
	at org.eclipse.ui.dialogs.FilteredResourcesSelectionDialog.lambda$1(FilteredResourcesSelectionDialog.java:459)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$HistoryComparator.compare(FilteredItemsSelectionDialog.java:2964)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:239)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1721)
	at java.base/java.util.Collections$SynchronizedList.sort(Collections.java:2542)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$ContentProvider.getSortedItems(FilteredItemsSelectionDialog.java:2585)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$ContentProvider.rememberResult(FilteredItemsSelectionDialog.java:2597)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.filterContent(FilteredItemsSelectionDialog.java:1965)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.internalRun(FilteredItemsSelectionDialog.java:1916)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.doRun(FilteredItemsSelectionDialog.java:1893)
	at org.eclipse.ui.dialogs.FilteredItemsSelectionDialog$FilterJob.run(FilteredItemsSelectionDialog.java:1881)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by iloveeclipse** [comment]
@jukzi : the stack doesn't match master. In which release is this observed, and is this reproducible in 4.27?

**Comment by jukzi** [comment]
eclipse.buildId=4.26.0.I20221123-1800
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE

**Comment by jukzi** [comment]
i can't even reproduce it in the instance where it occured. typical race condition :-(

**Comment by iloveeclipse** [comment]
So it is `collationKeyCache` that accessed from multiple threads?

**Comment by iloveeclipse** [comment]
Looks like `org.eclipse.ui.dialogs.FilteredItemsSelectionDialog.RefreshCacheJob.run(IProgressMonitor)` uses same comparator / map in parallel to UI:
![image](https://user-images.githubusercontent.com/964108/225924943-5057a22f-ccce-4d9d-9e20-383158c2cb74.png)

**Comment by jukzi** [comment]
that's what the stacktrace says. let's make it concurrenthashmap

**Comment by iloveeclipse** [comment]
> that's what the stacktrace says. let's make it concurrenthashmap

This will "fix" CME, but will not fix the already broken sort (it is unstable). Comparator should have no state, otherwise a.compare(b) will be not opposite of b.compare(a) on next call.

**Comment by jukzi** [comment]
it's not the value that changes but the cache, so the translated value will match
