### ISSUE TITLE
JavaFX preview broke in Eclipse 2023-03, javafx.embed.swt.FXCanvas cannot be found by org.eclipse.fx.ide.ui.preview_3.8.0.202204150904

### ISSUE THREAD

**Issue by crowlogic** [eclipse-platform/eclipse.platform.ui#650]
Caused by: java.lang.ClassNotFoundException: javafx.embed.swt.FXCanvas cannot be found by org.eclipse.fx.ide.ui.preview_3.8.0.202204150904
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 124 more

**Comment by iloveeclipse** [comment]
Please provide steps to reproduce.

**Comment by merks** [comment]
I would start by asking a question in their forum:

https://www.eclipse.org/forums/index.php?t=thread&frm_id=259

Or reporting a bug:

https://projects.eclipse.org/projects/technology.efxclipse/developer

But you should note that their most recent release was this one:

https://projects.eclipse.org/projects/technology.efxclipse/releases/3.9.0

I.e., they produced nothing new for 2023-03.

If this is a problem in the Platform rather than e(fx)clipse, someone will need to demonstrate what that problem is.
