### ISSUE TITLE
Cannot start Eclipse after updating from Eclipse 2022-12 (4.26) to 2023-03 (4.27) 

### ISSUE THREAD

**Issue by nimo23** [eclipse-platform/eclipse.platform.ui#651]
I updated my Eclipse installation by "Preferences > Install/Update" from 4.26 to 4.27. I always updated this way without any problems but this is the first time that it breaks my eclipse installation - I get the following `error.log` from (`Eclipse/configuration/`): 

```
!SESSION Tue Mar 21 10:53:17 CET 2023 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2023-03-21 10:53:17.415
!MESSAGE Could not find extension: reference:file:../../../../../../plugins/javax.transaction_1.1.1.v201105210645.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2023-03-21 10:53:17.417
!MESSAGE Could not find extension: reference:file:../../../../../../plugins/org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2023-03-21 10:53:17.426
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
```

I looked at the `config.ini` from (`Eclipse/configuration/config.ini`):

```
#This configuration file was written by: org.eclipse.equinox.internal.frameworkadmin.equinox.EquinoxFwConfigFileParser
#Mon Mar 20 09:48:05 CET 2023
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.27.0.20230309-1200
eclipse.p2.data.area=@config.dir/../p2/
eclipse.p2.profile=epp.package.jee
eclipse.product=org.eclipse.epp.package.jee.product
org.eclipse.equinox.simpleconfigurator.configUrl=file\:org.eclipse.equinox.simpleconfigurator/bundles.info
osgi.bundles=reference\:file\:../../../../../../plugins/org.eclipse.equinox.simpleconfigurator_1.4.200.v20221111-1340.jar@1\:start
osgi.bundles.defaultStartLevel=4
osgi.framework=file\:../Eclipse/configuration/org.eclipse.osgi/532/data/-1577097779/plugins/org.eclipse.osgi_3.18.300.v20230220-1352.jar
osgi.framework.extensions=reference\:file\:../../../../../../plugins/javax.transaction_1.1.1.v201105210645.jar,reference\:file\:../../../../../../plugins/org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
osgi.instance.area.default=@user.home/Documents/workspace
osgi.splashPath=platform\:/base/plugins/org.eclipse.epp.package.common
```

I found out that the folder of the following reference does not exist:
`
osgi.framework=file\:../Eclipse/configuration/org.eclipse.osgi/532/data/-1577097779/plugins/org.eclipse.osgi_3.18.300.v20230220-1352.jar`. 

There is no `/Eclipse/configuration/org.eclipse.osgi/532/data/.. `

It seems that Eclipse made a mistake here when updating.

OS: Mac OS (Intel)

**Comment by nimo23** [comment]
I looked at my `Eclipse/plugin`-folder and I see the following files within the `Eclipse/plugin`-folder:

- javax.transaction_1.1.1.v201105210645.jar
- org.eclipse.equinox.simpleconfigurator_1.4.200.v20221111-1340.jar
- org.eclipse.osgi_3.18.300.v20230220-1352.jar
- org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar

I tried to update eclipse `Eclipse/configuration/config.ini`, so that it points to the right location to those files within the `Eclipse/plugin`-folder:

```
..
osgi.bundles=:file\:../plugins/org.eclipse.equinox.simpleconfigurator_1.4.200.v20221111-1340.jar@1\:start
osgi.framework=file\:plugins/org.eclipse.osgi_3.18.300.v20230220-1352.jar
osgi.framework.extensions=file\:../plugins/javax.transaction_1.1.1.v201105210645.jar,reference\:file\:org.eclipse.osgi.compatibility.state_1.2.800.v20221116-1440.jar
eclipse.buildId=4.27.0.20230309-1200
..
```

However, I have troubles setting **the right paths**. I guess, I cannot use `reference\:file\:` as I need to point to `Eclipse/plugin/..` - what is the right syntax  for that path?

**Comment by elsazac** [comment]
is this resolved?

**Comment by nimo23** [comment]
The solution is simply to reinstall Eclipse and delete the old installation.
