### ISSUE TITLE
"Device is disposed" on shutdown in Throttler.throttledExec()

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#75]
Continuation of #56. If some job was running during shutdown, we might see following error:
```
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1505)
	at org.eclipse.swt.widgets.Display.getThread(Display.java:3378)
	at org.eclipse.jface.util.Throttler.throttledExec(Throttler.java:90)
	at org.eclipse.ui.internal.progress.ProgressManager.refreshJobInfo(ProgressManager.java:637)
	at org.eclipse.ui.internal.progress.ProgressManager$JobMonitor.subTask(ProgressManager.java:319)
	at org.eclipse.core.runtime.SubMonitor$RootInfo.subTask(SubMonitor.java:256)
	at org.eclipse.core.runtime.SubMonitor.subTask(SubMonitor.java:667)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1560)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:219)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
I will push a patch in a moment.

**Comment by laeubi** [comment]
@iloveeclipse I really wonder if we should have a `Optional<Thread> getDisplayThread()` that simply returns an empty optional if the device is disposed?

**Comment by iloveeclipse** [comment]
> @iloveeclipse I really wonder if we should have a `Optional<Thread> getDisplayThread()` that simply returns an empty optional if the device is disposed?

If you look on the callers you will see in most cases they just want to know if the current thread *is* UI thread (and if not, do something different), and that is already there `org.eclipse.swt.widgets.Display.getCurrent()`.

**Comment by laeubi** [comment]
> If you look on the callers you will see in most cases they just want to know if the current thread _is_ UI thread (and if not, do something different), and that is already there `org.eclipse.swt.widgets.Display.getCurrent()`.

Alright, just in the code you changed maybe it would then even be better to use `if (Display.getCurrent() == display)` ? maybe even a method `Display#isCurrent()` would be more helpful and more descriptive?

**Comment by iloveeclipse** [comment]
`Display.isInUIThread()` or `Display.isCurrentDisplayThread()`? I have no strong preference & do not plan to work on this.

**Comment by laeubi** [comment]
boolean Display.isCurrent() (in the display not static) would be enough I think but thats jsut an idea that came into my head if one really only wants to know if the current thread is the display thread ...
