### ISSUE TITLE
PartRenderingEngineTests test fails randomly

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#751]
See https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-750/1/testReport/junit/org.eclipse.e4.ui.tests.workbench/PartRenderingEngineTests/ensureCleanUpAddonCleansUp/

```
java.lang.AssertionError: CleanupAddon should ensure that partStack is not rendered anymore, as all childs have been removed
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.eclipse.e4.ui.tests.workbench.PartRenderingEngineTests.ensureCleanUpAddonCleansUp(PartRenderingEngineTests.java:2469)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.eclipse.e4.ui.tests.rules.WorkbenchContextRule$1.evaluate(WorkbenchContextRule.java:62)
```

**Comment by fedejeanne** [comment]
It failed again for **MacOS** yesterday in [this build](https://github.com/eclipse-platform/eclipse.platform.ui/pull/755/checks?check_run_id=14913892545) of #755

**Comment by iloveeclipse** [comment]
Still fails on github: https://github.com/eclipse-platform/eclipse.platform.ui/runs/16899215954

```
CleanupAddon should ensure that partStack is not rendered anymore, as all childs have been removed
java.lang.AssertionError: CleanupAddon should ensure that partStack is not rendered anymore, as all childs have been removed
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.eclipse.e4.ui.tests.workbench.PartRenderingEngineTests.ensureCleanUpAddonCleansUp(PartRenderingEngineTests.java:2469)
```

**Comment by HeikoKlare** [comment]
Still failing in same line with same message as before: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1541/checks?check_run_id=20973241710

**Comment by fedejeanne** [comment]
This one failed again for #3078 , which contains the changes from #3063
