### ISSUE TITLE
Fix random failing of PipelineChainTest

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#757]
Some tests in `PipelineChainTest` fail randomly. This is one such failures (see [check](https://github.com/eclipse-platform/eclipse.platform.ui/pull/715/checks?check_run_id=13336157987) for PR #715):

```
Wrong query sequence for interceptAdd expected:<ACGFBDE> but was:<null>
java.lang.AssertionError: Wrong query sequence for interceptAdd expected:<ACGFBDE> but was:<null>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.eclipse.ui.tests.navigator.PipelineChainTest._testInterceptAdd(PipelineChainTest.java:136)
	at org.eclipse.ui.tests.navigator.PipelineChainTest.testInterceptAdd(PipelineChainTest.java:113)
...
```

**Comment by jukzi** [comment]
I also ran into this exception:
https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5045869417/jobs/9051626843
```
Wrong query sequence for interceptUpdate expected:<ACGFBDE> but was:<null>
java.lang.AssertionError: Wrong query sequence for interceptUpdate expected:<ACGFBDE> but was:<null>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.eclipse.ui.tests.navigator.PipelineChainTest._testInterceptUpdate(PipelineChainTest.java:245)
	at org.eclipse.ui.tests.navigator.PipelineChainTest.testInterceptUpdateWithLabel(PipelineChainTest.java:226)
....
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
track:  ELEMENTS R/ id: A
track:  ELEMENTS R/ id: A
track:  ELEMENTS R/ id: A
track:  ELEMENTS R/ id: A
track:  ELEMENTS R/ id: A
track:  CHILDREN P/p1 id: A1
track:  CHILDREN P/p1 id: C
track:  CHILDREN P/p1 id: G
track:  CHILDREN P/p1 id: F
track:  CHILDREN P/p1 id: B
track:  CHILDREN P/p1 id: D
track:  CHILDREN P/p1 id: E
track:  CHILDREN P/p2 id: A1
track:  CHILDREN P/p2 id: C
track:  CHILDREN P/p2 id: G
track:  CHILDREN P/p2 id: F
track:  CHILDREN P/p2 id: B
track:  CHILDREN P/p2 id: D
track:  CHILDREN P/p2 id: E
track:  CHILDREN P/Test id: A1
track:  CHILDREN P/Test id: C
track:  CHILDREN P/Test id: G
track:  CHILDREN P/Test id: F
track:  CHILDREN P/Test id: B
track:  CHILDREN P/Test id: D
track:  CHILDREN P/Test id: E
track:  ADDS F/p1/newFolderRenamed id: A
track:  ADDS F/p1/newFolderRenamed id: C
track:  ADDS F/p1/newFolderRenamed id: G
track:  ADDS F/p1/newFolderRenamed id: F
track:  ADDS F/p1/newFolderRenamed id: B
track:  ADDS F/p1/newFolderRenamed id: D
track:  ADDS F/p1/newFolderRenamed id: E
track:  REMOVES P/Test id: A
track:  REMOVES P/Test id: C
track:  REMOVES P/Test id: G
track:  REMOVES P/Test id: F
track:  REMOVES P/Test id: B
track:  REMOVES P/Test id: D
track:  REMOVES P/Test id: E
track:  REMOVES P/p1 id: A
track:  REMOVES P/p1 id: C
track:  REMOVES P/p1 id: G
track:  REMOVES P/p1 id: F
track:  REMOVES P/p1 id: B
track:  REMOVES P/p1 id: D
track:  REMOVES P/p1 id: E
track:  REMOVES P/p2 id: A
track:  REMOVES P/p2 id: C
track:  REMOVES P/p2 id: G
track:  REMOVES P/p2 id: F
track:  REMOVES P/p2 id: B
track:  REMOVES P/p2 id: D
track:  REMOVES P/p2 id: E
```

Please note the missing 
`track:  ADDS F/p1/newFolder1`
and missing
`track:  REMOVESF/p1/newFolder1`
in the log output.
Everything happens in the single main Thread, and i don't see a reason why these events are sometimes missing on windows OS. 

The run https://github.com/eclipse-platform/eclipse.platform.ui/runs/13658066688
also is missing event output for `newFolderRenamed `

**Comment by fedejeanne** [comment]
No reported failures in 1+ years. Closing.
