### ISSUE TITLE
[win] Performance: TaskBarProgressManager.updateImage

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#780]
819 freezes reported in
https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/ep428I-unit-win32-java17_win32.win32.x86_64_17/org.eclipse.ui.tests.UiTestSuite.txt

for example:
```
!MESSAGE UI freeze of 0.81s at 12:59:03.728
!SUBENTRY 1 org.eclipse.ui.monitoring 1 0 2023-05-25 12:59:04.538
!MESSAGE Sample at 12:59:04.065 (+0.337s)
Thread 'main' tid=1 (RUNNABLE)
!STACK 0
Stack Trace
	at org.eclipse.swt.internal.ole.win32.COM.VtblCall(Native Method)
	at org.eclipse.swt.internal.ole.win32.ITaskbarList3.SetOverlayIcon(ITaskbarList3.java:31)
	at org.eclipse.swt.widgets.TaskItem.setOverlayImage(TaskItem.java:296)
	at org.eclipse.ui.internal.progress.TaskBarProgressManager.updateImage(TaskBarProgressManager.java:162)
	at org.eclipse.ui.internal.progress.TaskBarProgressManager$1.runInUIThread(TaskBarProgressManager.java:120)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:148)
	at org.eclipse.ui.progress.UIJob$$Lambda$701/0x00000008012b0f88.run(Unknown Source)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.ui.tests.harness.util.UITestCase.processEvents(UITestCase.java:245)
	at org.eclipse.ui.tests.harness.util.DialogCheck.assertDialogTexts(DialogCheck.java:89)
	at org.eclipse.ui.tests.dialogs.UIPreferencesAuto.testWorkbenchPref(UIPreferencesAuto.java:57)
```

All freezes ~ 0.9 sec.

**Comment by vogella** [comment]
Maybe do the update only every 200 / 400 ms? We have a utility class for this in JFace.

**Comment by iloveeclipse** [comment]
Note: since few days Windows tests run extremely long, I assume the Windows node is in bad shape. So be careful not to optimize something that is not slow under usual conditions.

**Comment by jukzi** [comment]
Can not reproduce locally. for example during test `UIPreferencesAuto`  updateImage() is only called 3 times and fast.
