### ISSUE TITLE
NPE in EmptyWorkspaceHelper.readProjectWizardActions()

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#781]
logged in 
https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/ep428I-unit-win32-java17_win32.win32.x86_64_17/org.eclipse.ui.tests.UiTestSuite.txt
```
----- testClose
testClose: setUp...
testClose: tearDown...


!ENTRY org.eclipse.ui 4 0 2023-05-25 12:59:33.701
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.IWorkbenchPage.getNewWizardShortcuts()" because "page" is null
	at org.eclipse.ui.internal.views.helpers.EmptyWorkspaceHelper.readProjectWizardActions(EmptyWorkspaceHelper.java:246)
	at org.eclipse.ui.internal.views.helpers.EmptyWorkspaceHelper.createEmptyArea(EmptyWorkspaceHelper.java:177)
	at org.eclipse.ui.internal.views.helpers.EmptyWorkspaceHelper.recreateEmptyArea(EmptyWorkspaceHelper.java:222)
	at org.eclipse.ui.internal.views.helpers.EmptyWorkspaceHelper.switchTopControl(EmptyWorkspaceHelper.java:314)
	at org.eclipse.ui.internal.views.helpers.EmptyWorkspaceHelper.lambda$0(EmptyWorkspaceHelper.java:299)
	at org.eclipse.ui.internal.views.helpers.EmptyWorkspaceHelper$Listener.handleEvent(EmptyWorkspaceHelper.java:329)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Tree.destroyItem(Tree.java:2709)
	at org.eclipse.swt.widgets.TreeItem.destroyWidget(TreeItem.java:310)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:831)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:428)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalRemove(AbstractTreeViewer.java:2008)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$2(AbstractTreeViewer.java:2259)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1398)
	at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:365)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1359)
	at org.eclipse.jface.viewers.AbstractTreeViewer.remove(AbstractTreeViewer.java:2259)
	at org.eclipse.jface.viewers.AbstractTreeViewer.remove(AbstractTreeViewer.java:2305)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.lambda$3(PackageExplorerContentProvider.java:978)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.runUpdates(PackageExplorerContentProvider.java:210)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.executeRunnables(PackageExplorerContentProvider.java:158)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerContentProvider.elementChanged(PackageExplorerContentProvider.java:143)
	at org.eclipse.jdt.internal.core.DeltaProcessor$3.run(DeltaProcessor.java:1757)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyListeners(DeltaProcessor.java:1745)
	at org.eclipse.jdt.internal.core.DeltaProcessor.firePostChangeDelta(DeltaProcessor.java:1578)
	at org.eclipse.jdt.internal.core.DeltaProcessor.fire(DeltaProcessor.java:1554)
	at org.eclipse.jdt.internal.core.DeltaProcessor.notifyAndFire(DeltaProcessor.java:2275)
	at org.eclipse.jdt.internal.core.DeltaProcessor.resourceChanged(DeltaProcessor.java:2165)
	at org.eclipse.jdt.internal.core.DeltaProcessingState.resourceChanged(DeltaProcessingState.java:501)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:307)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:297)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:160)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:388)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1516)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:800)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:332)
	at org.eclipse.ui.tests.harness.util.FileUtil.deleteProject(FileUtil.java:61)
	at org.eclipse.ui.tests.api.IWorkbenchPageTest.doTearDown(IWorkbenchPageTest.java:173)
	at org.eclipse.ui.tests.harness.util.UITestCase.tearDown(UITestCase.java:214)

```

Extending the NPE check of  Bug 569784 seems feasable

**Comment by BeckerWdf** [comment]
@jukzi: If you provide a pull request I can review / test it.

**Comment by jukzi** [comment]
This hopefully already fixed with https://github.com/eclipse-platform/eclipse.platform.ui/commit/b4ca239d5929571b77362e56c4ad406ed09f55b7
