### ISSUE TITLE
Random failing of SyncExecWhileUIThreadWaitsForLock.testDeadlock()

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#789]
The test failed during [this PR-Build](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/4990252225/jobs/8937663746) on May 16th 2023.

```
Unexpected list content: [] expected:<1> but was:<0>
java.lang.AssertionError: Unexpected list content: [] expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.eclipse.ui.tests.concurrency.SyncExecWhileUIThreadWaitsForLock.testDeadlock(SyncExecWhileUIThreadWaitsForLock.java:159)
```

**Comment by fedejeanne** [comment]
No reported failures for 1+ years. Closing.
