### ISSUE TITLE
Random failing of SorterTest.testSorterContentAdd()

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#794]
The test failed during a [custom build](https://github.com/fedejeanne/eclipse.platform.ui/actions/runs/5155048913/jobs/9284234729#step:7:17176) in my forked repository. It was during the freeze period for 4.29 and the code was current, so I'm creating an issue.

Here's the stack trace:

```
org.eclipse.ui.tests.navigator.SorterTest.testSorterContentAdd  Time elapsed: 0.365 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Blue[Added]Parent> but was:<Blue[]Parent>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.eclipse.ui.tests.navigator.SorterTest.testSorterContentAdd(SorterTest.java:291)
```

**Comment by fedejeanne** [comment]
@iloveeclipse you were way faster than me 😅
Thank you for merging!
