### ISSUE TITLE
Fallback Mechanism needed for corrupt workbench.xmi files

### ISSUE THREAD

**Issue by wibeck1** [eclipse-platform/eclipse.platform.ui#804]
So far, an rcp-application terminates whenever the workbench.xmi is corrupt. The class **_org.eclipse.e4.ui.internal.workbench.ResourceHandler_** handles the exception that is thrown downstream in the **_loadResource_**-Method and logs it. Usually, deleting the corrupt .xmi-file is enough to make the application run again. The user is forced to do that manually, though. Could you incorporate an automated deletion of the corrupt file and a relaunch of the application with a fresh workbench.xmi instead? Below is an exemplary stacktrace. I unfortunately cannot provide more:

org.eclipse.e4.ui.internal.workbench.ResourceHandler.getResource(ResourceHandler.java:287)
	**at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadResource(ResourceHandler.java:263)**
	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:169)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:384)
	at

Best regards

**Comment by fedejeanne** [comment]
Hello @wibeck1,
what version are you using? 

I just tested this by manually breaking my _workbench.xmi_ (I manually changed a reference in the file) and this is what happened:
* An exception got thrown (see below)
* The perspective reverted back to the default one
* The _workbench.xmi_ file got overwritten with default values

I then did a restart and there was no exception, which is to be expected since the corrupt _xmi_ file had been previously replaced by a new (default) one.

BTW this was the exception I got in the first run:
```
!ENTRY org.eclipse.e4.ui.workbench 4 0 2023-06-07 13:26:37.527
!MESSAGE Unable to load resource file:/D:/dev/platform-master/run-configurations/runtime-sdk.product/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi
!STACK 0
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.emf.ecore.xmi.UnresolvedReferenceException: Unresolved reference '_ytFXsQUlEe6BYoCJ5NUxUQ'. (file:/D:/dev/platform-master/run-configurations/runtime-sdk.product/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi, 2, 652)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.getResource(ResourceHandler.java:290)
	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadResource(ResourceHandler.java:266)
	at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:169)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:371)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:247)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:572)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
Caused by: org.eclipse.emf.ecore.xmi.UnresolvedReferenceException: Unresolved reference '_ytFXsQUlEe6BYoCJ5NUxUQ'. (file:/D:/dev/platform-master/run-configurations/runtime-sdk.product/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi, 2, 652)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleForwardReferences(XMLHandler.java:1197)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.endDocument(XMLHandler.java:1282)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endDocument(AbstractSAXParser.java:754)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:547)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	... 24 more
```

**Comment by wibeck1** [comment]
We used version **1.11.200.patched-202004221531**

So your application was able to start up without deleting the file manually, or am I wrong?

**Comment by fedejeanne** [comment]
> We used version 1.11.200.patched-202004221531

I meant the Eclipse version. I'm particularly interested in the class `org.eclipse.e4.ui.internal.workbench.ResourceHandler` and its method `loadMostRecentModel()` since that's where the fallback mechanism you're looking for is built in (see [line 181](https://github.com/eclipse-platform/eclipse.platform.ui/blob/e801f9081c90c3b27a41893c85d8ab2f86c34dff/bundles/org.eclipse.e4.ui.workbench/src/org/eclipse/e4/ui/internal/workbench/ResourceHandler.java#L181)).

> So your application was able to start up without deleting the file manually, or am I wrong?

You're correct: no human intervention needed :)

**Comment by wibeck1** [comment]
We used the following rcp-version: 4.15.0.v20200305-0155

**Comment by fedejeanne** [comment]
Ok, that's consistent with what I found on my end (I realized later that `1.11.200.patched-202004221531` was the version of the plugin `org.eclipse.e4.ui.workbench`).

In that case, I'm puzzled: the fallback mechanism was already there in v4.15. I can only imagine that since you're using a `patched` version of the plugin then maybe the fallback was inadvertently skipped?

Does your (patched?) version of `ResourceHandler` look very different from the [original one](https://github.com/eclipse-platform/eclipse.platform.ui/blob/2026901b01e57e3baf801517511f76c3ea9c0273/bundles/org.eclipse.e4.ui.workbench/src/org/eclipse/e4/ui/internal/workbench/ResourceHandler.java#L47)?

In particular: the exception should occur in line 263 and then it's `resource == null` (line 169) and then it will load the default XMI file in line 181:

```
if (restore && saveAndRestore) {
	resource = loadResource(restoreLocation); // Line 169 . resource is NULL
	// If the saved model does not have any top-level windows, Eclipse will exit
	// immediately, so throw out the persisted state and reinitialize with the defaults.
	if (!hasTopLevelWindows(resource)) {
		if (logger != null) {
			logger.error(new Exception(), // log a stack trace to help debug the corruption
					"The persisted application model has no top-level window. Reinitializing with the default application model."); //$NON-NLS-1$
		}
		resource = null;
	}
}
if (resource == null) { // Line 180: this is TRUE
	Resource applicationResource = loadResource(applicationDefinitionInstance); // Line 181: here's where the default XMI will be used (fallback)
	MApplication theApp = (MApplication) applicationResource.getContents().get(0);
	resource = createResourceWithApp(theApp);
	context.set(E4Workbench.NO_SAVED_MODEL_FOUND, Boolean.TRUE);
	initialModel = true;
} else {
	initialModel = false;
}
```

**Comment by wibeck1** [comment]
The ResourceHandler-class in our ws is the same as the orginal one. No lines changed.

**Comment by fedejeanne** [comment]
Then all I can think of is that saving into _workbench.xmi_ right before closing Eclipse failed and therefore the invalid content never got replaced.

If that's the case then you should see some error while executing the method `ResourceHandler.save()` in your logs.

**Comment by wibeck1** [comment]
I haven't found errors like this in the logs. It was reported that the file was corrupted after the application was not closed in a proper way or terminated unexpectedly, e.g. due to a sudden reboot of the OS.
