### ISSUE TITLE
Random failing ImportExistingProjectsWizardTest.test21FullBuildAfterImportedProjects

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#811]
```
Expected no auto-build triggers expected:<0> but was:<1>
java.lang.AssertionError: Expected no auto-build triggers expected:<0> but was:<1>
	at org.eclipse.ui.tests.datatransfer.ImportTestUtils$TestBuilder.assertFullBuildWasDone(ImportTestUtils.java:97)
	at org.eclipse.ui.tests.datatransfer.ImportExistingProjectsWizardTest.test21FullBuildAfterImportedProjects(ImportExistingProjectsWizardTest.java:1059)
```

**Comment by HeikoKlare** [comment]
Occurred again in recent I-Build: https://download.eclipse.org/eclipse/downloads/drops4/I20230723-1800/testresults/html/org.eclipse.ui.tests_ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html
