### ISSUE TITLE
LogEntryTest.testInvalidEntry() fails in I20230615-0550

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#829]
```
Text '' could not be parsed at index 0

java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2052)
at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1880)
at org.eclipse.ui.internal.views.log.LogEntry.processEntry(LogEntry.java:248)
at org.eclipse.pde.ui.tests.views.log.LogEntryTest.testInvalidEntry(LogEntryTest.java:94)
```

See https://download.eclipse.org/eclipse/downloads/drops4/I20230615-0550/testresults/html/org.eclipse.pde.ui.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

Regression from 41e79486f01ca271556357610bd510e125b0df76

**Comment by jukzi** [comment]
thanks for notification
