### ISSUE TITLE
Random failing AnnotationManagerTest.testRemoveQuery

### ISSUE THREAD

**Issue by Shee43** [eclipse-platform/eclipse.platform.ui#867]
In the Build [I20230517-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/), the below tests in org.eclipse.search.tests.filesearch.AnnotationManagerTest failed  
> 
on [macM1](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/testresults/html/org.eclipse.search.tests_ep428I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
> 
> ```
>java.lang.AssertionError: expected:<0> but was:<6>
>at org.junit.Assert.fail(Assert.java:89)
>at org.junit.Assert.failNotEquals(Assert.java:835)
>at org.junit.Assert.assertEquals(Assert.java:647)
>at org.junit.Assert.assertEquals(Assert.java:633)
>at org.eclipse.search.tests.filesearch.AnnotationManagerTest.testRemoveQuery(AnnotationManagerTest.java:144)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> ```

**Comment by Shee43** [comment]
In the Build [I20230703-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230703-1800/), the below tests in org.eclipse.search.tests.filesearch.AnnotationManagerTest failed

on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230703-1800/testresults/html/org.eclipse.search.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)

>```
>expected:<0> but was:<6>
>java.lang.AssertionError: expected:<0> but was:<6>
>at org.junit.Assert.fail(Assert.java:89)
>at org.junit.Assert.failNotEquals(Assert.java:835)
>at org.junit.Assert.assertEquals(Assert.java:647)
>at org.junit.Assert.assertEquals(Assert.java:633)
>at org.eclipse.search.tests.filesearch.AnnotationManagerTest.testRemoveQuery(AnnotationManagerTest.java:144)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> ```

**Comment by jukzi** [comment]
Also https://download.eclipse.org/eclipse/downloads/drops4/I20241209-1800/testresults/html/org.eclipse.search.tests_ep435I-unit-macosx-x86_64-java17_macosx.cocoa.x86_64_17.html
```
java.lang.AssertionError: expected:<0> but was:<24>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.eclipse.search.tests.filesearch.AnnotationManagerTest.testRemoveQuery(AnnotationManagerTest.java:144)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by jukzi** [comment]
also https://download.eclipse.org/eclipse/downloads/drops4/I20250102-1800/testresults/html/org.eclipse.search.tests_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

```
java.lang.AssertionError: expected:<0> but was:<6>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.eclipse.search.tests.filesearch.AnnotationManagerTest.testRemoveQuery(AnnotationManagerTest.java:145)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

**Comment by jukzi** [comment]
again in
https://download.eclipse.org/eclipse/downloads/drops4/I20250123-1800/testresults/html/org.eclipse.search.tests_ep435I-unit-macosx-aarch64-java21_macosx.cocoa.aarch64_21.html

**Comment by jukzi** [comment]
again in 
https://download.eclipse.org/eclipse/downloads/drops4/I20250205-1800/testresults/html/org.eclipse.search.tests_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html
