### ISSUE TITLE
org.eclipse.ui.tests.decorators.DecoratorAdaptableTest.testAdaptables is failing on linux

### ISSUE THREAD

**Issue by Shee43** [eclipse-platform/eclipse.platform.ui#868]
In the Build [I20230405-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800)  the below tests in org.eclipse.ui.tests.decorators.DecoratorAdaptableTests failed

on [cen64](https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800/testresults/html/org.eclipse.ui.tests_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html)
```
Adaptable test 1 has failed for object org.eclipse.ui.tests.menus.ObjectContributionClasses$A@728a2652
java.lang.AssertionError: Adaptable test 1 has failed for object org.eclipse.ui.tests.menus.ObjectContributionClasses$A@728a2652
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.ui.tests.decorators.DecoratorAdaptableTests.assertDecorated(DecoratorAdaptableTests.java:56)
at org.eclipse.ui.tests.decorators.DecoratorAdaptableTests.testAdaptables(DecoratorAdaptableTests.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by HeikoKlare** [comment]
A similar issue has occurred in [this build](https://github.com/eclipse-platform/eclipse.platform.ui/pull/950/checks?check_run_id=15202211735) for `org.eclipse.ui.tests.decorators.DecoratorAdaptableTests.testContributorResourceAdapter`:

```
Adaptable test 2 has failed for object org.eclipse.ui.tests.menus.ObjectContributionClasses$CFile@68ce8100
java.lang.AssertionError: Adaptable test 2 has failed for object org.eclipse.ui.tests.menus.ObjectContributionClasses$CFile@68ce8100
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.ui.tests.decorators.DecoratorAdaptableTests.assertDecorated(DecoratorAdaptableTests.java:56)
	at org.eclipse.ui.tests.decorators.DecoratorAdaptableTests.testContributorResourceAdapter(DecoratorAdaptableTests.java:155)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by jukzi** [comment]
again:
https://download.eclipse.org/eclipse/downloads/drops4/I20241204-1800/testresults/html/org.eclipse.ui.tests_ep435I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html
