### ISSUE TITLE
org.eclipse.search.tests.filesearch.PositionTrackerTest fails randomly

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.ui#882]
In the Build [I20220706-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220706-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on macM1

- testInsertAt0
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68) 
```
- testInsertInsideMatch
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82) 
```

**Comment by ktatavarthi** [comment]
In the Build [I20220824-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testResults.php), the below test in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on [macM1 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html) and [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
 - testInsertInsideMatch
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82) 
```

**Comment by ktatavarthi** [comment]
In the Build [I20220831-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/testresults/html/org.eclipse.search.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on macM1

- testInsertAt0
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68) 
```
- testInsertInsideMatch
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82) 
```

**Comment by ktatavarthi** [comment]
In the Build [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed 


on [macM1](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.search.tests_ep426I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)

- testInsertAt0
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68) 
```
on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.search.tests_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
- testInsertInsideMatch
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82) 
```

**Comment by Shee43** [comment]
In the Build [I20230405-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed 

on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230405-1800/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Shee43** [comment]
In the Build [I20230517-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
> 
on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
> 
> ```
>java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> ```
>
>
In the Build [I20230517-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
>
on [macM1](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800/testresults/html/org.eclipse.search.tests_ep428I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
>
>```
>java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)

**Comment by Shee43** [comment]
In the Build [I20230525-0350](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
> 
> > 
> 
 on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
>```
>java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:99)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> ```
>
In the Build [I20230525-0350](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
> 
> > 
> 
on [macM1](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.search.tests_ep428I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
> 
>  ```
> java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 >```

**Comment by Shee43** [comment]
In the Build [I20230601-1220](https://download.eclipse.org/eclipse/downloads/drops4/I20230601-1220/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
 
on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230601-1220/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)

> ```
> java.lang.AssertionError
>at org.junit.Assert.fail(Assert.java:87)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.junit.Assert.assertNotNull(Assert.java:723)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```

**Comment by Shee43** [comment]
In the Build [I20230605-0440](https://download.eclipse.org/eclipse/downloads/drops4/I20230605-0440/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed
> 
on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230605-0440/testresults/html/org.eclipse.search.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
> 
 > ```
> java.lang.AssertionError
> at org.junit.Assert.fail(Assert.java:87)
> at org.junit.Assert.assertTrue(Assert.java:42)
> at org.junit.Assert.assertNotNull(Assert.java:713)
> at org.junit.Assert.assertNotNull(Assert.java:723)
> at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:130)
> at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ```

**Comment by Shee43** [comment]
In the Build [I20230703-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230703-1800/), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed

on [mac64](https://download.eclipse.org/eclipse/downloads/drops4/I20230703-1800/testresults/html/org.eclipse.search.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)
 
> ```
>null position for match: offset=138 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/RepeatedTest.java
>java.lang.AssertionError: null position for match: offset=138 length=4 isFiltered=false >element=L/JUnitSource/junit/extensions/RepeatedTest.java
>at org.junit.Assert.fail(Assert.java:89)
>at org.junit.Assert.assertTrue(Assert.java:42)
>at org.junit.Assert.assertNotNull(Assert.java:713)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:100)
>at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> ```

**Comment by jukzi** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20230709-1800/testresults/html/org.eclipse.search.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
java.lang.AssertionError: null position for match: offset=141 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/TestSetup.java
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:100)

```

**Comment by jukzi** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20230713-1800/testresults/html/org.eclipse.search.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
```
java.lang.AssertionError: null position for match: offset=141 length=4 isFiltered=false 
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:100)
```

```
java.lang.AssertionError
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:131)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)

```

**Comment by jukzi** [comment]
errors on aarch64 and x86-64 are different (both Mac):

https://download.eclipse.org/eclipse/downloads/drops4/I20230713-1800/testresults/html/org.eclipse.search.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

```
java.lang.AssertionError: null position for match: offset=68 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/ActiveTestSuite.java
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:100)

```

**Comment by iloveeclipse** [comment]
Failed today on 3 platforms:
https://download.eclipse.org/eclipse/downloads/drops4/I20230725-1800/testresults/html/org.eclipse.search.tests_ep429I-unit-win32-java17_win32.win32.x86_64_17.html
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:131)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:68)
```

https://download.eclipse.org/eclipse/downloads/drops4/I20230725-1800/testresults/html/org.eclipse.search.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
```
null position for match: offset=68 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/ActiveTestSuite.java

java.lang.AssertionError: null position for match: offset=68 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/ActiveTestSuite.java
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:100)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

https://download.eclipse.org/eclipse/downloads/drops4/I20230725-1800/testresults/html/org.eclipse.search.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
```
null position for match: offset=110 length=4 isFiltered=false element=L/JUnitSource/junit/framework/Protectable.java

java.lang.AssertionError: null position for match: offset=110 length=4 isFiltered=false element=L/JUnitSource/junit/framework/Protectable.java
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:100)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:82)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

The problem is the AbstractDocument is not MT safe for update operations.
One can see by creating breakpoint at  org.eclipse.jface.text.AbstractDocument.set(String, long)` that there is not only UI thread hitting this code, it is also accessed from a job
```
Thread [Worker-17: Initializing Quick Diff] (Suspended (breakpoint at line 1121 in AbstractDocument))	
	Document(AbstractDocument).set(String, long) line: 1121	
	Document(AbstractDocument).set(String) line: 1116	
	LastSaveReferenceProvider.setDocumentContent(IDocument, IStorage, String, IProgressMonitor, boolean) line: 370	
	LastSaveReferenceProvider.readDocument(IProgressMonitor, boolean) line: 244	
	LastSaveReferenceProvider.getReference(IProgressMonitor) line: 125	
	DocumentLineDiffer$2.run(IProgressMonitor) line: 540	
	Worker.run() line: 63	
```
I will propose a patch

**Comment by iloveeclipse** [comment]
> I will propose a patch

Hmm, it is actually worse. The two are working on different document instances that are created on same file. Even worse, one is `org.eclipse.jface.text.Document` (not synchronized) and another one is `org.eclipse.core.internal.filebuffers.SynchronizableDocument`.

**Comment by iloveeclipse** [comment]
Just a guess, let's lock the workspace during the test, see #971, but could be something completely different

**Comment by iloveeclipse** [comment]
> Just a guess, let's lock the workspace during the test, see #971, but could be something completely different

Nope, still failing.

**Comment by BeckerWdf** [comment]
also fails https://github.com/eclipse-platform/eclipse.platform.ui/pull/939

**Comment by Shee43** [comment]
In the Build [I20230817-0230](https://download.eclipse.org/eclipse/downloads/drops4/I20230817-0230/testresults/html/org.eclipse.search.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on macM1

 * testInsertAt0

 ```
N/A

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.junit.Assert.assertNotNull(Assert.java:723)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertAtZero(PositionTrackerTest.java:136)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertAt0(PositionTrackerTest.java:70)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

* testInsertInsideMatch

```
null position for match: offset=68 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/ActiveTestSuite.java

java.lang.AssertionError: null position for match: offset=68 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/ActiveTestSuite.java
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:103)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:84)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by Shee43** [comment]
In the Build [I20230830-2200](https://download.eclipse.org/eclipse/downloads/drops4/I20230830-2200/testresults/html/org.eclipse.search.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on macM1

```
null position for match: offset=42 length=4 isFiltered=false element=L/JUnitSource/junit/framework/Test.java

java.lang.AssertionError: null position for match: offset=42 length=4 isFiltered=false element=L/JUnitSource/junit/framework/Test.java
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:103)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:84)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by Shee43** [comment]
In the Build [I20230903-1000](https://download.eclipse.org/eclipse/downloads/drops4/I20230903-1000/testresults/html/org.eclipse.search.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html), the below tests in org.eclipse.search.tests.filesearch.PositionTrackerTest failed on mac-64

 * testInsertInsideMatch
```
null position for match: offset=82 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/TestDecorator.java

java.lang.AssertionError: null position for match: offset=82 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/TestDecorator.java
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:103)
at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:84)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by iloveeclipse** [comment]
Still fails on Mac.
https://download.eclipse.org/eclipse/downloads/drops4/I20230918-1800/testresults/html/org.eclipse.search.tests_ep430I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

I will mute the test on Mac now.

**Comment by fedejeanne** [comment]
Failed again for **Windows** in this [PR build](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/7220191090/job/19672626093?pr=1309) (#1309)

```java
org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch -- Time elapsed: 0.756 s <<< FAILURE!
java.lang.AssertionError: null position for match: offset=68 length=4 isFiltered=false element=L/JUnitSource/junit/extensions/ActiveTestSuite.java
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertNotNull(Assert.java:713)
	at org.eclipse.search.tests.filesearch.PositionTrackerTest.checkInsertInsideMatch(PositionTrackerTest.java:107)
	at org.eclipse.search.tests.filesearch.PositionTrackerTest.testInsertInsideMatch(PositionTrackerTest.java:88)
...
```

**Comment by HeikoKlare** [comment]
## Reproduction

I can reproduce these failures locally as follows: The tests will not fail when executing the `PositionTrackerTest` on its own. They will only fail when executed in the `AllFileSearchTests` suite, or, more precisely, within any test suite in which the `LineAnnotationManagerTest` is executed right before the `PositionTrackerTest`. To make the failure more likely to appear, you can add a sleep (50ms or the like) right before the loop in which the assertion fails:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/d896ec06010d158dac0c737618af8dcfe0de622d/tests/org.eclipse.search.tests/src/org/eclipse/search/tests/filesearch/PositionTrackerTest.java#L138-L143

## Reason

The reason for these failures does not seem to be rooted in the `PositionTrackerTest` but in `LineAnnotationManagerTest`. That test succeeds, but internally produces hidden errors, such as the following:

```
java.lang.IllegalArgumentException: 
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:68)
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:52)
	at org.eclipse.search.internal.ui.text.FileMatch.<init>(FileMatch.java:39)
	at org.eclipse.search.tests.filesearch.LineBasedFileSearch$LineBasedTextSearchResultCollector.acceptPatternMatch(LineBasedFileSearch.java:75)
	at org.eclipse.search.internal.core.text.TextSearchVisitor.locateMatches(TextSearchVisitor.java:486)
	at org.eclipse.search.internal.core.text.TextSearchVisitor$TextSearchJob.processFile(TextSearchVisitor.java:212)
	at org.eclipse.search.internal.core.text.TextSearchVisitor$TextSearchJob.run(TextSearchVisitor.java:173)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
The reason is that this test class uses the test query class `LineBasedFileSearch`, which is broken. That class will _never_ produce a valid result for two reasons: First, it used in a multi-threaded context but is not implemented thread safe, thus leading to race conditions. Second, the following line always throws an exception due to `null` being an invalid argument:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/d896ec06010d158dac0c737618af8dcfe0de622d/tests/org.eclipse.search.tests/src/org/eclipse/search/tests/filesearch/LineBasedFileSearch.java#L75

In consequence of this (an further bugs in `LineAnnotationManagerTest`), the `LineAnnotationManagerTest` always operates on an empty search result list (which is the reason why it always succeeds), but the executed search task produces exceptions and leaks some invalid state that somehow influences subsequent searches. Due to the current test suite configuration, this is the `PositionTrackerTest`.

## Fix

As explained, from my state of analysis the fix has to be made in `LineAnnotationManagerTest` rather than in `PositionTrackerTest`. I have proposed #1428 for that.
