### ISSUE TITLE
JUnit tests in org.eclipse.jface.text.tests.contentassist are failing on Windows and Mac

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.ui#890]
This is a duplicate of [Bug 571316](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571316) - JUnit tests in org.eclipse.jface.text.tests.contentassist are failing on Windows and Mac

I will close the bug in bugzilla and this bug will be tracked here.

The JFace text tests in org.eclipse.jface.text.tests.contentassist fail in the nightly build as below

Windows
1) testCompleteActivationChar

Both Windows and Mac
1) testSyncFailureNPE

**Comment by ktatavarthi** [comment]
eclipse-platform/eclipse.platform.text#9 is a duplicate of this bug.

**Comment by ktatavarthi** [comment]
The below test failed in the IBuild [I20220601-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testResults.php)  on Windows and Mac

[Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-win32-java11_win32.win32.x86_64_11.html)
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar 
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE


Mac [x86_64 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)and  [aarch64](https://download.eclipse.org/eclipse/downloads/drops4/I20220601-1800/testresults/html/org.eclipse.jface.text.tests_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220706-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220706-1800/) on [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220706-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220817-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/) 

On [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

On Mac [x86_64 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)and  [aarch64](https://download.eclipse.org/eclipse/downloads/drops4/I20220817-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220824-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/) 

On [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

On Mac [x86_64 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html)and  [aarch64](https://download.eclipse.org/eclipse/downloads/drops4/I20220824-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below tests failed in the IBuild [I20220831-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/) 

On [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

On [MacM1 ](https://download.eclipse.org/eclipse/downloads/drops4/I20220831-1800/testresults/html/org.eclipse.jface.text.tests_ep425I-unit-macM1-java17_macosx.cocoa.aarch64_17.html)
- org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testSyncFailureNPE

**Comment by ktatavarthi** [comment]
The below test failed in the IBuild [I20220928-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/) 

On [Windows](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html)

-  org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar

**Comment by ktatavarthi** [comment]
The below tests fail in the build [I20221117-1330](https://download.eclipse.org/eclipse/downloads/drops4/I20221117-1330/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html) on Windows
  - org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
  - org.eclipse.jface.text.tests.contentassist.ContextInformationPresenterTest.testContextInfo_withStyledTextPresentation
  - org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo
  - org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_keyEsc
  - org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_validRange

**Comment by ktatavarthi** [comment]
The below tests fail in the build [I20221123-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20221123-1800/testresults/html/org.eclipse.jface.text.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html) on Windows

    org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar
    org.eclipse.jface.text.tests.contentassist.ContextInformationPresenterTest.testContextInfo_withStyledTextPresentation
    org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_keyEsc
    org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_validRange

**Comment by jukzi** [comment]
ContextInformationTest's randomly fails locally on WIndows every ~2nd time. for MAC and Linux ContextInformationTest.testContextInfo_hide_focusOut() is already disabled.

**Comment by jukzi** [comment]
Still an error:
https://download.eclipse.org/eclipse/downloads/drops4/I20230531-1800/testresults/html/org.eclipse.jface.text.tests_ep428I-unit-win32-java17_win32.win32.x86_64_17.html

```
java.lang.AssertionError: Not unique new shell found expected:<1> but was:<0>
at org.junit.Assert.assertEquals(Assert.java:647)
at org.eclipse.jface.text.tests.contentassist.AbstractContentAssistTest.findNewShell(AbstractContentAssistTest.java:235)
at org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar(AsyncContentAssistTest.java:182)

```

**Comment by jukzi** [comment]
still randomly failing on win
https://download.eclipse.org/eclipse/downloads/drops4/I20230620-1800/testresults/html/org.eclipse.jface.text.tests_ep429I-unit-win32-java17_win32.win32.x86_64_17.html

```
java.lang.AssertionError: Not unique new shell found expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.eclipse.jface.text.tests.contentassist.AbstractContentAssistTest.findNewShell(AbstractContentAssistTest.java:235)

```

**Comment by jukzi** [comment]
still randomly failing on win
https://download.eclipse.org/eclipse/downloads/drops4/I20230713-1800/testresults/html/org.eclipse.jface.text.tests_ep429I-unit-win32-java17_win32.win32.x86_64_17.html

```
java.lang.AssertionError: Not unique new shell found expected:<1> but was:<0>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.eclipse.jface.text.tests.contentassist.AbstractContentAssistTest.findNewShell(AbstractContentAssistTest.java:235)
at org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar(AsyncContentAssistTest.java:161)

```

**Comment by jukzi** [comment]
Added help_wanted flag, as this is one frequently shows up in I-builds.

**Comment by iloveeclipse** [comment]
I would propose to disable `AsyncContentAssistTest.testCompleteActivationChar`. It makes no sense to keep the test failing for years.

**Comment by jukzi** [comment]
> I would propose to disable `AsyncContentAssistTest.testCompleteActivationChar`. 

ok for me

**Comment by trancexpress** [comment]
Failed on Linux here: https://download.eclipse.org/eclipse/downloads/drops4/I20260315-1800/testresults/logs.html

https://download.eclipse.org/eclipse/downloads/drops4/I20260315-1800/testresults/html/org.eclipse.jface.text.tests_ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21.html

```
	Not unique new shell found ==> expected: <1> but was: <0>

org.opentest4j.AssertionFailedError: Not unique new shell found ==> expected: <1> but was: <0>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:563)
at org.eclipse.jface.text.tests.contentassist.AbstractContentAssistTest.findNewShell(AbstractContentAssistTest.java:236)
at org.eclipse.jface.text.tests.contentassist.AsyncContentAssistTest.testCompleteActivationChar(AsyncContentAssistTest.java:166)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) 
```

Workspace log: https://download.eclipse.org/eclipse/downloads/drops4/I20260315-1800/testresults/ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21/org.eclipse.jface.text.tests.JFaceTextTestSuite.txt

```
!SESSION 2026-03-16 00:19:58.183 -----------------------------------------------
eclipse.buildId=4.40.0.I20260315-1800
java.version=21.0.10
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.test.coretestapplication formatter=org.apache.tools.ant.taskdefs.optional.junit.XMLJUnitResultFormatter,/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260315-1800/eclipse-testing/test-eclipse/eclipse/org.eclipse.jface.text.tests.JFaceTextTestSuite.xml -testPluginName org.eclipse.jface.text.tests -className org.eclipse.jface.text.tests.JFaceTextTestSuite -timeout 7200000 -junitReportOutput /home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260315-1800/eclipse-testing/results/ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21
Command-line arguments:  -application org.eclipse.test.coretestapplication -data /home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260315-1800/eclipse-testing/test-eclipse/eclipse/jface_text_folder formatter=org.apache.tools.ant.taskdefs.optional.junit.XMLJUnitResultFormatter,/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260315-1800/eclipse-testing/test-eclipse/eclipse/org.eclipse.jface.text.tests.JFaceTextTestSuite.xml -testPluginName org.eclipse.jface.text.tests -className org.eclipse.jface.text.tests.JFaceTextTestSuite -os linux -ws gtk -arch x86_64 -consolelog -timeout 7200000 -junitReportOutput /home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260315-1800/eclipse-testing/results/ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21

!ENTRY org.eclipse.e4.ui.workbench3 1 0 2026-03-16 00:20:02.634
!MESSAGE starting DumpStackTracesTimer with timeout=7080000 at 2026-03-16 00:20:02 +0000

!ENTRY org.eclipse.jface.text 4 2 2026-03-16 00:20:06.979
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface.text".
!STACK 0
java.lang.RuntimeException: Expected Exception for junit test
	at org.eclipse.jface.text.tests.contentassist.DelayedErrorContentAssistProcessor.computeCompletionProposals(DelayedErrorContentAssistProcessor.java:31)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:385)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:384)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$11(AsyncCompletionProposalPopup.java:419)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Console output: https://download.eclipse.org/eclipse/downloads/drops4/I20260315-1800/testresults/consolelogs/ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21_consolelog.txt

```
java-test:
     [echo] Running org.eclipse.jface.text.tests.JFaceTextTestSuite. Result file: /home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260315-1800/eclipse-testing/results/ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21/org.eclipse.jface.text.tests.JFaceTextTestSuite.xml
     [echo] timout property: 7200000
     [echo] frameworkvmargs:  -Xms256m -Xmx2048m -Djava.io.tmpdir=/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/tmp
     [echo] vmargs: 
     [echo] extraVMargs: 
     [echo] frameworkperfargs: 
     [echo] crash loglocationarg (if any): ${loglocationarg}
     [echo] crash loglocation (if not default): 
     [java] Mar 16, 2026 12:20:00 AM org.apache.aries.spifly.BaseActivator log
     [java] INFO: Registered provider org.slf4j.simple.SimpleServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle slf4j.simple
     [java] INFO: timeoutScreenOutputDir: /home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260315-1800/eclipse-testing/results/ep440I-unit-linux-x86_64-java21_linux.gtk.x86_64_21/timeoutScreens
     [java] INFO: timeout: 7200000
     [java] 
     [java] (SWT:88525): Gtk-CRITICAL **: 00:20:03.396: gtk_scrolled_window_get_overlay_scrolling: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed
     [java] 
     [java] (SWT:88525): Gtk-CRITICAL **: 00:20:03.402: gtk_scrolled_window_get_overlay_scrolling: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed
     [java] 
     [java] (SWT:88525): Gtk-CRITICAL **: 00:20:03.403: gtk_scrolled_window_get_overlay_scrolling: assertion 'GTK_IS_SCROLLED_WINDOW (scrolled_window)' failed
     [java] 
     [java] (SWT:88525): Gtk-WARNING **: 00:20:22.377: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
     [java] 
     [java] (SWT:88525): Gtk-WARNING **: 00:20:23.439: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
     [java] 
     [java] (SWT:88525): Gtk-WARNING **: 00:20:24.467: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
     [java] 
     [java] (SWT:88525): Gtk-WARNING **: 00:20:25.496: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)
     [java] Mockito is currently self-attaching to enable the inline-mock-maker. This will no longer work in future releases of the JDK. Please add Mockito as an agent to your build as described in Mockito's documentation: https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#0.3
     [java] WARNING: A Java agent has been loaded dynamically (/home/jenkins/agent/workspace/AutomatedTests/ep440I-unit-linux-x86_64-java21/workarea/I20260315-1800/eclipse-testing/test-eclipse/eclipse/plugins/net.bytebuddy.byte-buddy-agent_1.18.7.jar)
     [java] WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
     [java] WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
     [java] WARNING: Dynamic loading of agents will be disallowed by default in a future release
     [java] OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```
