### ISSUE TITLE
Failure of test: CompletionTest.testCompletionService()

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#906]
The test `CompletionTest.testCompletionService()` failed for *Mac OS* in [this run](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5443629428/jobs/9900395775?pr=755) of the PR #755 :

```
Widget is disposed
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:811)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:597)
	at org.eclipse.swt.widgets.Table.getItem(Table.java:1597)
	at org.eclipse.ui.genericeditor.tests.CompletionTest$3.condition(CompletionTest.java:184)
	at org.eclipse.jface.text.tests.util.DisplayHelper.waitForCondition(DisplayHelper.java:79)
	at org.eclipse.ui.genericeditor.tests.CompletionTest.checkCompletionContent(CompletionTest.java:186)
	at org.eclipse.ui.genericeditor.tests.CompletionTest.testCompletionService(CompletionTest.java:111)
...
```

**Comment by fedejeanne** [comment]
This issue might have been solved by [PR 725 in SWT](https://github.com/eclipse-platform/eclipse.platform.swt/pull/725).
If the test doesn't fail again in the next few days, this issue can be closed.

**Comment by laeubi** [comment]
Seen here again:
https://github.com/eclipse-platform/eclipse.platform.ui/runs/15314473237

**Comment by BeckerWdf** [comment]
Fails also in https://github.com/eclipse-platform/eclipse.platform.ui/pull/939

**Comment by iloveeclipse** [comment]
It is failing in jenkins on almost every build. I'm going to disable the test.

```
Completion proposal list was unexpectedly disposed
java.lang.AssertionError: Completion proposal list was unexpectedly disposed
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.eclipse.ui.genericeditor.tests.CompletionTest$1.condition(CompletionTest.java:137)
	at org.eclipse.jface.text.tests.util.DisplayHelper.waitForCondition(DisplayHelper.java:79)
	at org.eclipse.ui.genericeditor.tests.CompletionTest.waitForProposalRelatedCondition(CompletionTest.java:140)
	at org.eclipse.ui.genericeditor.tests.CompletionTest.checkCompletionContent(CompletionTest.java:191)
	at org.eclipse.ui.genericeditor.tests.CompletionTest.testCompletionService(CompletionTest.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.ja
```

**Comment by fedejeanne** [comment]
No reported failures in 1+ years. Closing.
