### ISSUE TITLE
Failure of test: CompletionTest.testMoveCaretBackUsesAllProcessors_bug522255()

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#907]
The test ` CompletionTest.testMoveCaretBackUsesAllProcessors_bug522255()` failed for *Mac OS* in [this run](https://github.com/eclipse-platform/eclipse.platform.ui/pull/755/checks?check_run_id=14736602623) of the PR #755 :

```
Widget is disposed
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:811)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:597)
	at org.eclipse.swt.widgets.Table.getItem(Table.java:1597)
	at org.eclipse.ui.genericeditor.tests.CompletionTest$3.condition(CompletionTest.java:184)
	at org.eclipse.jface.text.tests.util.DisplayHelper.waitForCondition(DisplayHelper.java:79)
	at org.eclipse.ui.genericeditor.tests.CompletionTest.checkCompletionContent(CompletionTest.java:186)
	at org.eclipse.ui.genericeditor.tests.CompletionTest.testCompletion(CompletionTest.java:81)
	at org.eclipse.ui.genericeditor.tests.CompletionTest.testMoveCaretBackUsesAllProcessors_bug522255(CompletionTest.java:231)
```

This issue might be related to #906

**Comment by fedejeanne** [comment]
This issue might have been solved by [PR 725 in SWT](https://github.com/eclipse-platform/eclipse.platform.swt/pull/725).
If the test doesn't fail again in the next few days, this issue can be closed.

**Comment by HeikoKlare** [comment]
Also fails on builds of master branch, e.g. https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5518247705/jobs/10063260276

**Comment by HeikoKlare** [comment]
I close this as duplicate of #906 since both share the same root cause.
