### ISSUE TITLE
Random failing of HoverTest.testEnabledWhenHover()

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#926]
The test `HoverTest.testEnabledWhenHover()` failed for **Linux** in [this build](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5486542118/jobs/9996772549) of #755 .
```
org.eclipse.ui.genericeditor.tests.HoverTest.testEnabledWhenHover -- Time elapsed: 12.51 s <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.fail(Assert.java:96)
	at org.eclipse.ui.genericeditor.tests.HoverTest.getHoverShell(HoverTest.java:175)
	at org.eclipse.ui.genericeditor.tests.HoverTest.testEnabledWhenHover(HoverTest.java:90)
```

**Comment by iloveeclipse** [comment]
Fails often in github actions:
https://github.com/eclipse-platform/eclipse.platform.ui/runs/16899215954
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.fail(Assert.java:96)
	at org.eclipse.ui.genericeditor.tests.HoverTest.getHoverShell(HoverTest.java:175)
	at org.eclipse.ui.genericeditor.tests.HoverTest.testEnabledWhenHover(HoverTest.java:90)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

```
FocusControl: 
  ToolBar {} [layout=null]
    CTabFolder {} [layout=org.eclipse.swt.custom.CTabFolderLayout@738153d8]
      Composite {} [layout=org.eclipse.e4.ui.workbench.renderers.swt.SashLayout@1a3272e0]
        Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]
          Composite {} [layout=StackLayout {topControl=Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]}]
            Composite {} [layout=org.eclipse.e4.ui.workbench.renderers.swt.SashLayout@7bc3c59f]
              Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]
                Shell {data - org.eclipse.ui.genericeditor.tests.HoverTest1695059443047/enabledWhen.txt} [layout=org.eclipse.e4.ui.workbench.renderers.swt.TrimmedPartLayout@6db2a260]
Shells: 
  inactive, invisible: Shell {PartRenderingEngine's limbo} [layout=null] @ Rectangle {0, 10000, 800, 640}
  active, visible: Shell {data - org.eclipse.ui.genericeditor.tests.HoverTest1695059443047/enabledWhen.txt} [layout=org.eclipse.e4.ui.workbench.renderers.swt.TrimmedPartLayout@6db2a260] @ Rectangle {0, 0, 1024, 768}
  inactive, invisible: Shell {} [layout=null] @ Rectangle {0, 0, 800, 640}
Client area: Rectangle {0, 0, 1280, 1024}
Cursor location: Point {306, 102}
CursorControl: 
  StyledText {} [layout=null]
    Canvas {} [layout=org.eclipse.jface.text.source.SourceViewer$RulerLayout@56b66cc6]
      Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]
        Composite {} [layout=StackLayout {topControl=Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]}]
          Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]
            ContributedPartRenderer$1 {} [layout=FillLayout {type=SWT.VERTICAL}]
              CTabFolder {} [layout=org.eclipse.swt.custom.CTabFolderLayout@6f076c53]
                Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]
                  Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]
                    Composite {} [layout=org.eclipse.e4.ui.workbench.renderers.swt.SashLayout@1a3272e0]
                      Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]
                        Composite {} [layout=StackLayout {topControl=Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]}]
                          Composite {} [layout=org.eclipse.e4.ui.workbench.renderers.swt.SashLayout@7bc3c59f]
                            Composite {} [layout=FillLayout {type=SWT.HORIZONTAL}]
                              Shell {data - org.eclipse.ui.genericeditor.tests.HoverTest1695059443047/enabledWhen.txt} [layout=org.eclipse.e4.ui.workbench.renderers.swt.TrimmedPartLayout@6db2a260]
Display @ Rectangle {0, 0, 1280, 1024}
```
