### ISSUE TITLE
FoldersAsProjectsContributionTest fails randomly on different platforms

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#946]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/945.

https://download.eclipse.org/eclipse/downloads/drops4/I20230719-1800/testresults/html/org.eclipse.ui.tests.navigator_ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html
```
N/A

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.alreadyAdded(FoldersAsProjectsContributionTest.java:66)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

https://download.eclipse.org/eclipse/downloads/drops4/I20230719-1800/testresults/html/org.eclipse.ui.tests.navigator_ep429I-unit-win32-java17_win32.win32.x86_64_17.html

```
N/A

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.notYetImported(FoldersAsProjectsContributionTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

@zelenyhleb : please try to make tests more stable.

**Comment by mickaelistria** [comment]
@zelenyhleb Can you please have a look? Usually "random" failures come from asynchronous work that requires to wait upon some event (such as job completion)

**Comment by zelenyhleb** [comment]
@mickaelistria I don't remember any async things in this test, but I'll try to fix the instability. Hope it's reproducible somehow

**Comment by iloveeclipse** [comment]
@zelenyhleb : at least add proper assertion messages so that one could understand what was not OK in the test. Right now we don't even know are there too many / to less elements and especially **which** were expected and which not.

Note, it fails on Jenkins on unrelated PR's too:

https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-810/24/testReport/junit/org.eclipse.ui.tests.navigator.resources/FoldersAsProjectsContributionTest/notYetImported/

**Comment by zelenyhleb** [comment]
@iloveeclipse I prepared a PR with test improvements (#957), but I was not able to reproduce test faults on my side even with the pipeline. The only assumption I had that this is somehow related to ContributionManager item addition logic, but as I see according to the source code, it does everything synchronously. Also, I am not sure, but as I see according to https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/master/, test is stable for last few builds. Please correct me if I'm wrong.

**Comment by iloveeclipse** [comment]
> test is stable for last few builds.

The environment is unfortunately not stable. Let's see if it will fail again, with the updated assertions we would at least have some more data to work with.

**Comment by HeikoKlare** [comment]
Unfortunately, the tests still fail, but now provide enhanced data for debugging: https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5653230011/job/15315312687

**Comment by iloveeclipse** [comment]
For the record, the fails were:
```
A OpenFolderAsProjectAction contribution was not added. Contribution List is: org.eclipse.jface.action.GroupMarker,org.eclipse.jface.action.GroupMarker
java.lang.AssertionError: A OpenFolderAsProjectAction contribution was not added. Contribution List is: org.eclipse.jface.action.GroupMarker,org.eclipse.jface.action.GroupMarker
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.notYetImported(FoldersAsProjectsContributionTest.java:88)
```

```
A SelectProjectForFolderAction contribution was not added. Contribution List is: org.eclipse.jface.action.GroupMarker,org.eclipse.jface.action.GroupMarker
java.lang.AssertionError: A SelectProjectForFolderAction contribution was not added. Contribution List is: org.eclipse.jface.action.GroupMarker,org.eclipse.jface.action.GroupMarker
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.alreadyAdded(FoldersAsProjectsContributionTest.java:79)
```

**Comment by BeckerWdf** [comment]
fails also for https://github.com/eclipse-platform/eclipse.platform.ui/pull/939

**Comment by iloveeclipse** [comment]
Still failing on regular base in jenkins and on SDK builds...

jenkins (Mac & Linux):
https://github.com/eclipse-platform/eclipse.platform.ui/runs/15903858123
```
Can't explicitly create project description due to: /tmp/junit13368669576984279561/foldersasprojects.alreadyAdded.outer/foldersasprojects.alreadyAdded.inner2/.project
java.lang.AssertionError: Can't explicitly create project description due to: /tmp/junit13368669576984279561/foldersasprojects.alreadyAdded.outer/foldersasprojects.alreadyAdded.inner2/.project
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.ensureFileExists(FoldersAsProjectsContributionTest.java:248)
	at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.ensureDescriptionsExist(FoldersAsProjectsContributionTest.java:235)
	at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.alreadyAdded(FoldersAsProjectsContributionTest.java:103)
```

SDK (Mac):
https://download.eclipse.org/eclipse/downloads/drops4/I20230814-1800/testresults/html/org.eclipse.ui.tests.navigator_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html
```
Can't explicitly create project description due to: /private/var/folders/p2/3vplzt5920j0zmbvd8wlbxw80000gp/T/junit2918959077985805277/foldersasprojects.alreadyAdded.outer/foldersasprojects.alreadyAdded.inner2/.project

java.lang.AssertionError: Can't explicitly create project description due to: /private/var/folders/p2/3vplzt5920j0zmbvd8wlbxw80000gp/T/junit2918959077985805277/foldersasprojects.alreadyAdded.outer/foldersasprojects.alreadyAdded.inner2/.project
at org.junit.Assert.fail(Assert.java:89)
at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.ensureFileExists(FoldersAsProjectsContributionTest.java:248)
at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.ensureDescriptionsExist(FoldersAsProjectsContributionTest.java:235)
at org.eclipse.ui.tests.navigator.resources.FoldersAsProjectsContributionTest.alreadyAdded(FoldersAsProjectsContributionTest.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

I think if there is no insight why that happens we should disable the tests, it makes no sense to keep them running & failing.

**Comment by jukzi** [comment]
closing as the test was disabled
