### ISSUE TITLE
An Error pops up "Look up for installed JVM's has encountered a problem" everytime eclipse is opened.

### ISSUE THREAD

**Issue by elsazac** [eclipse-platform/eclipse.platform.ui#993]
Problem:
When you start eclipse an error pops up with the description  `An internal error occurred during:'look up for installed JVMs' has encountered a problem.`

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/122080218/6109b6a4-248b-493a-b440-03d541a227bd)

attaching the stack trace below:

```
java.lang.UnsupportedOperationException: remove
	at java.base/java.util.Iterator.remove(Iterator.java:102)
	at java.base/java.util.Collection.removeIf(Collection.java:577)
	at org.eclipse.jdt.internal.launching.DetectVMInstallationsJob.run(DetectVMInstallationsJob.java:66)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```

**Comment by BeckerWdf** [comment]
This should be fixed with https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/292
